### ISSUE TITLE
📰 PR data base for Giveth communications! 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1046]
[· This is a repository conformed ](https://www.notion.so/giveth/PR-Database-829918551be04ae48d5da218f1bd03a7)by Web3 communication media & podcasts, Influential Twitter Accounts, Web3 Personalities & DAO allies, aligned with the Giveth Mission and vision.  

· This database will be use to make email campaigns around Giveth launches, announcements & events, with the intention of get the work amplified with interviews, notes, Twitter Spaces opportunities & so on. 

· The first email campaign will be the launch of GIVpower (cc @laurenluz ) , followed by the launch of Griff's podcast. 

· Please, will love your support adding media, podcasts, Web3 personalities, etc, [in the **"name"** column](https://www.notion.so/giveth/PR-Database-829918551be04ae48d5da218f1bd03a7) . No need to add emails, Im doing the research . @tropicalmangos @c0ric0ri @laurenluz @WhyldWanderer @SnakeGH 
Thank you!

**Comment by c0ric0ri** [comment]
Tagging @SymSL here as well, as we've had discussions around influencer marketing which coincides with this. 

FYI perhaps we should consider Tiktok in these efforts because of the potential reach? Months ago we spoke with Mike Mezz who has achieved quite a following there posting about regenerative finance and economics.

**Comment by oyealmond** [comment]
We have a good amount of media to start with. https://www.notion.so/giveth/PR-Database-829918551be04ae48d5da218f1bd03a7
