### ISSUE TITLE
Blog on Greenpill podcast

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1047]
This just came out!!

Someone should watch it and summarize what they talked about in a tweet thread!

https://twitter.com/BanklessHQ/status/1595063351779934208

**Comment by laurenluz** [comment]
the thread can be short, the point I think is to be like "this podcast was great! you'll learn all about amazing things like etc etc..."

I'm thinking a 2-3 part thread... where one part of the thread is actually a soundbite from the talk.

@danelsuga would you be down to take this? I know you don't like writing tweets, but the idea is really just to listen to it, pick 2 or three great parts... choose one as a soundbite and make a list of the topics in another.

**Comment by danelsuga** [comment]
Yes, I can do the summarizing jazz. Not so much the tweeting. :D

**Comment by danelsuga** [comment]
Here are my extensive notes and summary.

https://docs.google.com/document/d/1MUV06qT08rrfz1EbFAjKDXjFgOZwr1x5m_NGJTHFwOY/edit

**Comment by danelsuga** [comment]
I'll work on a soundbite or two after the weekend.

**Comment by laurenluz** [comment]
@danelsuga this is so great! can you pick a couple of soundbites?
one griff was just talking about last night is where he talks about an AI to help you vote.. he linked it as a reply on owocki's tweet last night. maybe that can be one.

Also - the part that says "incomplete" - what's the story there?


Tbh looking at this, I almost want to just make it a blog. Basically as is, with a few images/graphics... colour it up a little.

I think people would love it.

**Comment by danelsuga** [comment]
Thanks!

Oh, oops. Sorry - it looks like I forgot to go back and complete the section on "proof of work". I've taken care of that now. 

I will get the soundbites, sure!

This could definitely be a blog, but maybe some of my notey-notes should be cleaned up, especially the beginning structure even though that was how it played out.

I think it would be great, because it offers so much at a glance for understanding these tools without having to watch the video if you didn't want to.

**Comment by laurenluz** [comment]
yes! 100% 

Also, browsing twitter, found some things:

Visual: https://twitter.com/owocki/status/1600158366185111552

Exhaustive info: https://twitter.com/carl_cervone/status/1603087764865646592

Suggestion to make a blog here: https://twitter.com/owocki/status/1603071747565273090

imo if we could get this polished up & out quick, we could even add some links to the work that Carl's doing and have something that people actually really appreciate... but timing is key

**Comment by danelsuga** [comment]
omg ok. someone needs to tell those guys i took copious notes. :P

here is the link to the maching-learning web2 algorithm, voting aggregated data etc. etc. reference: https://youtu.be/qyd7mvQmn5I?t=3869

i already retweeted it on the owocki thread for whatever it's worth.

**Comment by danelsuga** [comment]
OK, I've made a new doc to build the actual article (because I like to keep my notes).
https://docs.google.com/document/d/11ogQ5HZpSOh0wRArirOjvwkhyNajVmaLzHEttuT6JH0/edit?usp=sharing

**Comment by danelsuga** [comment]
I reworked the beginning so far. When you talk about quick, how quick? Do you want to publish it with its imperfections so we don't miss the boat, and then I can clean it up later? If we want to do it today or tomorrow?

**Comment by laurenluz** [comment]
No stress, but if you feel like tackling it this evening, I can review it while you're sleeping and we could even have it ready to go tomorrow or monday.

Monday is also fine if you want to take a couple of days to write.  I'm imagining that this will take pretty minimal QA because you've got it all there straight from the horses' mouths and written out as notes.

**Comment by danelsuga** [comment]
I didn't manage today so will work on it Friday.

**Comment by laurenluz** [comment]
great! if you do get a chance in your daytime to finish a draft, I can review tomorrow in my daytime :) lmk if you need other support @danelsuga

**Comment by ccerv1** [comment]
gm. excited to work on this with you. FYI, I created a markdown template for summarizing the data about each funding mechanism [here](https://github.com/ccerv1/funding-mechanisms-research) 

happy to help edit it contribute in other ways to the blog post!

**Comment by danelsuga** [comment]
hi @ccerv1 ! thanks! awesome. @laurenluz here is an edited doc, just synced. was offline today.

https://docs.google.com/document/d/11ogQ5HZpSOh0wRArirOjvwkhyNajVmaLzHEttuT6JH0/edit?usp=sharing

**Comment by laurenluz** [comment]
Hey @danelsuga ! Great start, I left you some voice messages w/ some feedback :) lmk if you have any questions.

**Comment by danelsuga** [comment]
OK, thanks.

**Comment by laurenluz** [comment]
@GriffGreen can you give this a review?

**Comment by danelsuga** [comment]
I submitted the article to the Giveth Medium. Feel free to tweak it of course @laurenluz ! 

Because of wacky Medium formatting, I took out the numbers and just used bullet points. All the extra paragraphs as part of each mechanism was totally screwing up the formatting, and Medium doesn't really have much margin for adaptability with all that. Equally un-aesthetic results for the added paragraphs for a number of mechanisms but whatever. If you see a better solution, go for it.

I also added this line right before "web-based mechanisms" section: Creating this market is part of Giveth's mission!

Here's the full paragraph:

What if there was a market for a clean river? This would allow different companies to compete in that new market. If the collective doesn't have any customers, it can make its own: use supply and demand to give value to and reward value creation for society. Creating this market is part of Giveth's mission!

Because it just seemed to fit in with that section, and because I was trying to find a quote from Griff, as I had several from Owocki already. So Griff begins a tiny bit to talk about creating a market for public goods, but only a tiny bit. I thought this would be a good moment for a plug, as it just fit in. Take out if desired.

Or maybe better would be: Creating this market is part of the greater mission of the Giveth Galaxy!

**Comment by danelsuga** [comment]
I incorporated Griff's edits. I think he only did half or so, but it's all in there now. I resubmitted it to Giveth's Medium just in case he's done.

**Comment by danelsuga** [comment]
Incorporated Griff's new edits. Also updated on Medium t stay consistent and in case he's done. 

Happy holidays!! 🎄💜🎉🎊🎈🎁

**Comment by danelsuga** [comment]
All edits incorporated again. Just waiting for final sign-off.

**Comment by ahmadabugosh** [comment]
hey @danelsuga do you think I should give it a final proof read and just post it, or would you rather wait for @GriffGreen or @laurenluz ?

**Comment by danelsuga** [comment]
It's actually fully ready to go on my end, just waiting in Medium to be published by Giveth. Unfortunately, that means I can't do anything more. It's @laurenluz who has to press the publish button!

**Comment by ahmadabugosh** [comment]
@danelsuga I actually can publish it myself (I got edit rights when I was fixing the Medium categories), so if you don't want to wait for @laurenluz let me know! 😄

**Comment by danelsuga** [comment]
Oooo

Well, that's interesting. 

I definitely would prefer if she had a final look, but it really needs to be included in this newsletter. I'll try to reach out on Telegram.

**Comment by danelsuga** [comment]
@laurenluz says she will get to it today so it can be included in the newsletter. Let's reconnect tomorrow (Friday) @ahmadabugosh ! Thanks.

**Comment by laurenluz** [comment]
https://medium.com/giveth/coordination-mechanisms-notes-from-a-conversation-with-griff-green-kevin-owocki-af95f3e831b1

Posted! @c0ric0ri @ahmadabugosh - please include this link in the newsletter & "year in review" :)

We can tweet about it next week

**Comment by danelsuga** [comment]
Thank you @laurenluz! 🥰

**Comment by laurenluz** [comment]
thank youuu @danelsuga !!

**Comment by danelsuga** [comment]
Was contacted on Twitter by someone who will translate this post into Japanese. :D

**Comment by laurenluz** [comment]
wow!!
