### ISSUE TITLE
Re post Giveth House Twitter Space :) 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1074]
Hey team! @c0ric0ri @laurenluz 

[Here's the draft to repost our last Twitter Space](https://docs.google.com/document/d/1z0jHDgxJFHjcAHFSp8xcOdAYkKXEj_vykHVBW_gtQLY/edit) for you to review. 

Thank you!

**Comment by laurenluz** [comment]
scheduled for saturday <3 thanks Almendra!

**Comment by oyealmond** [comment]
noted the feedback around capturing engaging content mentioned at the space to build the post tweet.
Ty @laurenluz !!

**Comment by laurenluz** [comment]
yeah!! I just listened to the 1st 15 min or so until I found an idea I liked and tried to work it in there. I also like drafting tweets in tweethunter directly because it give a "Rating" on how well it thinks the tweet will perform, based on the content.

if it says "ok"... I feel bad... hahah this one, when I was done with it, said "above average" (which was good enough for me). not sure if the free version has it but you should check! it's pretty cool!

**Comment by oyealmond** [comment]
Im checking & there's no free version :'(, it has a 7 days trial period. Im going to ask Stee, maybe he knows

**Comment by oyealmond** [comment]
https://twitter.com/Givethio/status/1599041527472443392
