### ISSUE TITLE
Move Newsletters to new platform - Revue shutting down Jan 18 2023

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1094]
@ahmadabugosh - are you able to take this on? 

- investigate the best alternative
- move over newsletter content
- change all "subscribe" links

[Reference](http://help.getrevue.co/en/articles/6819675-we-ve-made-the-difficult-decision-to-shut-down-revue)

**Comment by ahmadabugosh** [comment]
hey @laurenluz @c0ric0ri, After looking at a few different options (Substack, Mirror and Beehiv) I decided to move our newsletter over to [Paragraph](https://paragraph.xyz/@giveth ). 

I think it's the best option because: 
-  It's web3 native (they publish all content on Arweave) and allow users to link their wallet's (in the future we could use this for POAPs or other incentives)
- When you post on Paragraph they index them on Google and allow users to subsribe with just their email (which is not the case with Mirror)
-  We tested it out with General Magic, and didn't find any reasons not to (it has a nice UI for editing, allows for multiple authors and has all the features we want). 

I already migrated all of our posts and subscribers onto it: https://paragraph.xyz/@giveth

--------

@MoeNick , can you get the team to help us change the links? 

1) For the homepage, could we add this iframe? I'm not sure how it will look, but this is the one that they recommend to add:

`<iframe src="https://paragraph.xyz/@giveth/embed" width="480" height="480" style="border:1px solid #EEE; background:white;" frameborder="0" scrolling="no"></iframe>`

You can also check their docs https://docs.paragraph.xyz/docs/development

2) For the /join page, can you add the iframe or this link? https://paragraph.xyz/@giveth/subscribe

3) @geleeroyale  Can you redirect news.giveth.io to https://paragraph.xyz/@giveth ? (As a temporary solution, in the future we have the ability to put the newsletter on the subdomain directly).

**Comment by geleeroyale** [comment]
DNS record has been updated

**Comment by c0ric0ri** [comment]
Thanks @ahmadabugosh ! I also updated the Highlights of 2022 blog post with the new links.
