### ISSUE TITLE
Christmas/ Holiday Campaign 

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/giveth-planning#1115]
Context: 

Create 2 high impact campaigns with the objective of getting more donations on our Dapp 

Christmas Campaigns (to get more donations) 

**1. Re-engagement campaign-** campaign to get our past donors re-engaged with an email marketing campaign consisting of 5 emails centered around the holidays and "the spirit of giving", along with some storytelling along with top projects we want to spotlight who received a ton of donations (social proof built in). 

Rationale: December is the biggest donation month of the year! People are feeling the most generous over the holidays and we need to take advantage and have our biggest month yet!  Also, from a marketing perspective it's faaaaaar easier to get another donation from an existing  donor than get a brand new donation. That's proven with stats across industries (not just my opinion).

This campaign will include: 
- email campaign x 3 
- tweets x 3 
- discord x1
- telegram x1

We need to push this across as many channels as possible for better visibility and more chances to win them over! 

**2. Project Holiday Campaign**- create tweets and emails so projects can share with their audience why they should donate to them on Giveth over the holiday season! Let's leverage the partner projects we have and increase our visibility and reach. 

This campaign will include: 
- email campaign x 3
- tweets x 3

**Comment by laurenluz** [comment]
@c0ric0ri i tranferred it

**Comment by ahmadabugosh** [comment]
Hi @tropicalmangos, I'm scheduling this out now, but I noticed two very big mistakes! 

1) You mention in the second email that "GIVback tokens represent more than a simple reward". There is no such thing as a GIVback token, it's the GIVbacks program, which gives users GIV (some of which is sent directly to their wallet after every GIVbacks round and some is streamed to them over 4+ years through the GIVstream).
2) In the third email you mention "P.S. Remember, when you make a donation, you earn GIVbacks which you can use for Giveth swag and to boost your favourite projects! " That also is not correct. You can get swag by getting $nice tokens, but that is only by donating to the main Giveth project in stablecoins. Also the GIVbacks program doesn't let you boost projects that's GIVpower. 

These kinds of very basic mistakes show a fundamental lack of understanding of how the GIVeconomy works and would confuse our donors! How were these missed in the review process? :( @laurenluz @c0ric0ri @oyealmond 

------

I'm sending out the first 2 emails (scheduling one today and the other on the 28th), but I had to rephrase the second email. For the third email, I don't think it's worth sending out, because we're sending out the newsletter at the end of the month, and I don't want people to get spammed with too many Giveth emails, plus I think it would make more sense to have a stronger start to the year email (perhaps a different campaign).

**Comment by ahmadabugosh** [comment]
@tropicalmangos It's ok, of course I wouldn't want you to work when you're not feeling well and I hope you feel better soon! 

I was just surprised because in the last comms call, you mentioned that it was thoroughly reviewed by 2 people and ready to go, but those are basic mistakes that aren't grammatical or stylistic differences but have to do with the basics of how Giveth works, and honestly I think you should be more acquainted with what we do and test out all features of our platform so you can write better content. 

For the third newsletter, I know it's focused on the new year, but 1) The theme of the campaign was to make December the highest giving month and it feels like a shift to start talking about the new year in the third email 2) I think the content of it is weak in relation to getting people excited about 2023 and we could do a lot better to get people excited about the new year. For example, we can mention GIVpower boosting and talk about how different projects are ranked and also mention the cool new animated POAP we have for Round 27 etc. so I think we should rewrite it or think about another angle for it.

**Comment by ahmadabugosh** [comment]
hey @tropicalmangos , what is the issue with Autopilot? Are you having trouble logging in? 

Yes, the first email went out to everyone tagged as a Donor and Project two days ago, the second one is set to go out on the 28th

<img width="1378" alt="Screenshot 2022-12-26 at 10 33 47 PM" src="https://user-images.githubusercontent.com/4855928/209575473-b51e9b80-eaaa-4aac-b87a-7f07acbd0bf7.png">

**Comment by ahmadabugosh** [comment]
@tropicalmangos I think we may still need to edit the 3rd email and agree if it's good to go. @danelsuga are you free this week to help with that?

**Comment by danelsuga** [comment]
Sure!

**Comment by c0ric0ri** [comment]
Hey @tropicalmangos FYI I moved this to Review/QA because it seems like it's way past the In Progress stage, but if it's done please update accordingly

**Comment by danelsuga** [comment]
I'm sorry. I hadn't realized it was already in there. Will look now.

**Comment by danelsuga** [comment]
OK, done!

**Comment by laurenluz** [comment]
@danelsuga @tropicalmangos - I hacked it a apart a little with suggestions, there were quite a few things that were innaccurate or misleading imo, but I think it should be good now.

**Comment by ahmadabugosh** [comment]
Done, tweaked the messaging a bit and sent the last one
