### ISSUE TITLE
Design and acquire swag - ETH Denver

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#1138]
# notes from jan 5 meeting

> - [ ]  LAUREN IS COORDINATING SWAG
    - Mitch’s update - we put up the poll in #ideas channel in Giveth
    - Lauren’s update - working w/ Rodri & Lulu on swag. Giveth galaxy hoodie design
    - has not put poll up on twitter for swag
    - rodri will work on designs next week
    - design for giveth, design especially for eth denver
    - maybe 5 different types of products for eth denver
    - all needs to be available on printful
    - ahmad is looking at other providers for swag - if printful is a blocker there might be another solution

while you're there, updating swag, let's not forget #1020

**Comment by divine-comedian** [comment]
just noticed this small clip reading up on the eth denver notion:
![image](https://user-images.githubusercontent.com/67759413/211368035-0e91c880-6720-4e84-854f-b6a0e9ee0371.png)

we probably will need closer to the conservative estimate since we'll be making people work for their swag. obvs depends on our final budget.

**Comment by WhyldWanderer** [comment]
Having access to their brand assets is nice!

## Notes from Jan 12 meeting

### Lauren’s update - brainstorming is happening and will have many more updates next week or tomorrow

**Comment by laurenluz** [comment]
@rodricastillo9013 and Lulu are working on some designs and will have some ready this week for review.

**Comment by ahmadabugosh** [comment]
@laurenluz @divine-comedian @WhyldWanderer Do we know what quantity and type of swag we'd want? If we buy it in advance (in the next 2 weeks) and in bulk we could save a lot (maybe up to 50%)

**Comment by divine-comedian** [comment]
here's a rough quote from ETH Denver swag guidelines:
![image](https://user-images.githubusercontent.com/67759413/213715628-2fc37269-b201-49c1-a290-0ecbf2e41fdf.png)

**Comment by tomislavmamic** [comment]
> We surely should order more than we had in Barcelona as we ran out halfway through the conference.

We can preorder a limited amount to be distributed during the event. If there is more demand than that, we can make it so that you can give people special codes that they can use to access that item on our swag shop and claim it. We can then either have them pay for the whole thing (production and delivery), just a delivery, or nothing (we pay for everything).

It will be more expensive per item, but only in shipping part. Production part should cost about the same. Unless the initial order is in thousands.

**Comment by laurenluz** [comment]
we have a total budget of like $5 for swag + stickers. 

I'm assuming like $4k on clothes, $1k on stickers, working with that to get quotes.

Can we somehow allow people to use a cc to buy swag from swag.giveth.io?

because if that's still our central swag hub, perhaps it makes the most sense just to everything from printful.

**Comment by ahmadabugosh** [comment]
Hey @laurenluz so just to understand, you want to use the $5K for free swag ($4K for clothes and $1K for stickers), and then allow people to purchase more swag at the event if you run out? 

We have CC setup already on the General Magic marketplace we're building, I'll discuss with the team if we could either have a Giveth storefront ready on the marketplace site, or if we could add our Stripe payment gateway to the existing Giveth swag shop

**Comment by laurenluz** [comment]
yeah, that's what I was thinking. right now you can only use $nice in our swag shop I think... I don't think even glove works anymore (not sure) @missgene ?

I could love to add a cc option to the swag shop, just to cut our the coordination from our side... we can't exactly just mint people $nice because they missed out on swag.

**Comment by laurenluz** [comment]
Ok I have ordered swag! Here are some useful links & things for our future reference.

- [Quantities](https://docs.google.com/spreadsheets/d/1BcyAhEKWAAPlNo7X-6KZgV01VnM_LRazhvemDxxbdNI/edit#gid=1392101541)
- [Lulu Designs Images](https://drive.google.com/drive/u/0/folders/135EdXEEEcjWs3hPNJK_njD6EZHKJRdNy)
- [Swag Design Images](https://drive.google.com/drive/folders/1UkaCrEMJzhmcTJ3gdaLzFXexvtkxsevx)
- [Eth Denver swag figma](https://www.figma.com/file/LKBHpnxI9sLjde7DzOQIYQ/Giveth-Marketing?node-id=2597%3A18061&t=9WGPxoNGhk2m4TFP-4)
- [Notes (not super useful)](https://docs.google.com/document/d/11VpDBpBbHzdQEShZyRhiQcFVZDxXgRkjM2SNn8g8z8c/edit)

Ordered swag from printful, total $4,255.21 - ship to Heather in Boulder - arriving Feb 6
Ordered stickers from sticker mule, total $738.27 - ship to Heather in Boulder - arriving Feb 6

Total budget was $5k

**Comment by ahmadabugosh** [comment]
Hey @laurenluz @WhyldWanderer @divine-comedian , We just added credit card payments to the Giveth Swag shop: https://swag.giveth.io/

**Comment by laurenluz** [comment]
oh heck yeah!!
