### ISSUE TITLE
Outreach to external orgs for impact quest prizes

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#1139]
# Notes from Jan 5 meeting

> - [ ]  Outreach to events , ways to partner & participate in a side event.
    - Mitch’s update -
    - yass is having a call with someoen from AAVE
    - cori and mitch need to contact bradley for rAAVE - david, christina, bradley
    - yass has a good friend of mine who is super up to date on these side events
    - shapeshift party with willy - ashley will talk to willy
    - pizza DAO - griff can reach out to pizza DAO
        - partner with pizza DAO to deliver pizza to the homeless
    - jake wiggles - music lead for eth denver - mitch will talk to jake

**Comment by divine-comedian** [comment]
heather got us this link to track upcoming side-events, looks pretty empty for now

https://docs.google.com/spreadsheets/d/1gDVzvwwy_NcVr7kXo2J7pD74ZwKbvnRjKmOXwoZ2cao/edit#gid=1476575035

also there is a TG group for sponsors to coordinate on parties - will look there for more opportunities 

shapeshift is looking for someone else to buddy up to sponsor their party this year - will probably use voorhees mansion again but nothing is confirmed 

rAAVE will not be happening for eth denver (damn bear market) - will try to be in touch if there are other ticketed AAVE/lens parties happening

**Comment by WhyldWanderer** [comment]
Talked to Willy
Shapeshift is still waiting to confirm that they will partner with Coinbase for a party at Erik's house. (Dj's, drinks, etc)
If CB doesnt confirm, they would be looking for someone to fill the space.
Too expensive for Giveth (5k-7k)

Willy says there could be ~250 people and we could potentially make it a fundraiser too? like $10 or $20 donation to Giveth or Giveth's matching fund per ticket... not sure if this makes it worth it. 

We cant be sure that it will sell out and those numbers are very rough estimates... it doesnt seem like it would be worth the risk and add more work to the load of Gviethers in Denver. But without a RAAVE this event, people will be looking for alternatives. What do you think? Is it worth it?

Willy says if CB doesnt follow through, we could potentially partner with a 3rd DAO like Gitcoin and do an event that way.... 

He also confirmed that however the event turns out, even if Giveth isn't involved he would be happy to provide us with a few tickets for prizes!

**Comment by divine-comedian** [comment]
People that have been contacted and interested that we need to follow up with in a few weeks:

- [ ]  Ronen - Game7 - giant crypto gaming org @divine-comedian 
- [ ]  Annee Park - DeFi Denver/ PickemPlay / HAV3N - build week events (still looking for partners) @divine-comedian 
- [ ]  VEER - sozu haus - (eth denver hacker house) @divine-comedian 
- [ ]  John Legg - DAIvinity (still looking for partners) @divine-comedian 
- [ ]  ShapeShift @WhyldWanderer

**Comment by divine-comedian** [comment]
not sure getting it signed adds value for some people 

but consider that he is lending his credibility - vitalik 

can check on the website to see if there are more celebrities

**Comment by divine-comedian** [comment]
someone in AMA wanting to give away NFTs NFTbeez

**Comment by divine-comedian** [comment]
Vitalik won't be at ETH Denver :cry: 

Still outreaching to more event sponsors as they appear in the unofficial lists of events/parties to get a soft commit on donating tickets 

Reached out to NFT Denver Club Takeover organizer - Cynthia - impact quests deemed "not valuable for her" :-1: 
Reached out to Hannah Oreskovich - who is leading some teams looking for co-sponsors for events (not sure which ones) - will come back to me with any interest

ETH Denver donated $1000 worth of swag which we can order from their swag store once it is updated with 2023 items - pick up at conference

**Comment by divine-comedian** [comment]
**Prizes can include:**

- 10-50 PFPs (need to determine)
- phyiscal Giveth Swag
- Hedgey NFTs that have GIV locked behind them
- ETH Denver Swag
- Tickets to Parties (mitch needs to follow up)
- Hedera Hashgraph dinner for volunteering
------

@WhyldWanderer - need to outreach to shapeshift for party confirm
@spectoregia - need to confirm tickets for Gnosis party

**Comment by c0ric0ri** [comment]
Messaged Nader with the request for swag/tickets and to find out who correct POC is. Will provide updates when I have them!
