### ISSUE TITLE
Draft Outreach Message for Gitcoin Alpha Round

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1149]
We need a simple message that can be used to promote our grant during the round, via Discord, Telegram and social DMs. I don't think this needs to be complicated, but simply including the appropriate links with a friendly encouragement.

It would be great to have this drafted for our Comms meeting next week so that we can use it to kick off outreach within the group!

My understanding is we would use this list for outreach efforts: https://docs.google.com/spreadsheets/d/10d3-NFU6M7Dl9u4A4W0g4JZa96zNuUpGzXxtljJuF94/edit#gid=1511320055

**Comment by c0ric0ri** [comment]
Hey @SnakeGH is this something you could take on?

@danelsuga @WhyldWanderer @laurenluz do we have other drafts we've used in the past for reference? I was searching in Github but didn't see one.

**Comment by danelsuga** [comment]
The emails sent to previous donor is part of the same [Gitcoin shill doc](https://docs.google.com/document/d/1tC7AiyYwzxSX3hbpQSaT_zKqnzHmu3xYRuS7wKRtgFg/edit?usp=sharing
) as listed under [issue 1146](https://github.com/Giveth/giveth-planning/issues/1146#issuecomment-1379644992).

As for emails for sending other folks, I don't know about that one. I only sent it to previous donors myself.

**Comment by danelsuga** [comment]
The emails sent to previous donors is part of the same [Gitcoin shill doc](https://docs.google.com/document/d/1tC7AiyYwzxSX3hbpQSaT_zKqnzHmu3xYRuS7wKRtgFg/edit?usp=sharing
) as listed under [issue 1146](https://github.com/Giveth/giveth-planning/issues/1146#issuecomment-1379644992).

As for emails for sending other folks, I don't know about that one. I only sent it to previous donors myself.

**Comment by SnakeGH** [comment]
@c0ric0ri do you want me to take what @danelsuga has provided https://docs.google.com/document/d/1tC7AiyYwzxSX3hbpQSaT_zKqnzHmu3xYRuS7wKRtgFg/edit# and create a short 1-2 line message about the Gitcoin Alpha Round? 

Honestly, if @danelsuga has the time, since she made a killer doc, I think she could easily pull out the critical information that Comms could use to make tweets, TG, Discord, LI, FB messages. If she does not have the time though, then I can def do it tomorrow, no worries. 

Just let me know Suga :)

**Comment by c0ric0ri** [comment]
Hey @SnakeGH yeah I forgot you are covering for Yass this week.

The point of this issue is just to have an easy template for contributors to use when doing outreach to shill the grant. A small intro that can be used in our messages - like the kind of stuff we have created for Algene. I think a couple of lines is plenty with a link to our grant encouraging donations.

**Comment by danelsuga** [comment]
Sorry - that grant link is obviously going to change.

**Comment by SnakeGH** [comment]
Thanks @danelsuga, I also took some time to create a fun write up, which if we plug in our "key selling points," it could be a light way of marketing / communicating. Maybe combine Suga's and mine to create the perfect pitch...IDK @c0ric0ri @laurenluz 



Is all this “new year, new me” talk already on your nerves?! And does this winter weather have you feeling a little down and out?? I’m sure it has, which is why you’ve been trying to change all that, with a way to really spark some energy into this year…

Well, no need to look any further friend, because Giveth is here to shine some much-needed sunny charitable warmth on you, by providing a real way to impact the Future of Giving! 

Gitcoin’s “Alpha Round” is LIVE, and with the $330K in matching funds, even the smallest donation will make a huge difference in someone’s life and hopefully provide you with that much needed burst of January rocket fuel!

You can find Giveth’s grant listings with the following links:

**Comment by danelsuga** [comment]
@SnakeGH ! I love the change up. A breath of fresh air! I would recommend still adding the main selling points (no fees, 100% goes to project, rewards for donors). Maybe something like:

_Does all this “new year, new me” talk get you wondering what it actually means? Does the winter weather have you feeling a little down and unsure how to move forward? 

Well, look no further, friend, than Giveth, here to shine some much-needed sunny, charitable warmth by offering a true, revolutionary way to support causes that are working to better the world. Introducing Giveth.io: the only crypto fundraising platform boasting zero fees and where 100% of the donation goes to the project, and donors are rewarded!

Gitcoin’s “Alpha Round” is LIVE, and with the $330K in matching funds, even the smallest donation will make a huge difference in someone’s life and provide you with that much needed burst of January rocket fuel!

Join us in Building the Future of Giving!

You can find Giveth’s grant listings with the following links:_

**Comment by danelsuga** [comment]
(Oops, rereading your message, I see you had the same idea as me!)

**Comment by SnakeGH** [comment]
@danelsuga dreamwork makes the teamwork! I love it and thanks for helping to add those missing selling points plus sentence boosters and of course grammatical fixes :) ! Well done and hopefully it's in a great spot now, cause I think it's perfect now.

**Comment by c0ric0ri** [comment]
Hey both thanks so much! I added the draft into a doc so it's easier to review and leave comments. That's usually how we draft content for ease of editing just FYI @SnakeGH 

https://docs.google.com/document/d/1ozq_CsGCh_y2w9_cJhkbpk6ljGmjU6l5YbGZob8N84w/edit

I added a second draft below that is a bit shorter and takes a slightly different approach. I think it's good to have a few versions so people can choose depending on who they are speaking with or what channel they are using (telegram would require a shorter message).

I left some suggestions on the first draft as well!
