### ISSUE TITLE
Fiat Integration Email Campaign

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1160]
Fiat integration is live in a beta version, and we want to get many more testers as possible (at least 100) from as many different locations as possible.

it would make sense to appeal to our existing user base to test this out and provide us with feedback, so an email campaign is a great way to let them know this is live and invite them to try it out.

We could even use a raffle to incentivize users to fill out feedback form.

Let's start with drafting 2 emails for this campaign (1 to announce, 1 to remind):

- announcing that it's now possible to donate with fiat (and still get GIVbacks? need to double check)
- this is brand new and we'd love to invite you to test this important step in giveth's development
- feedback is important for us to improve, and we'll be running a raffle for all participants who fill out the feedback form

**Comment by c0ric0ri** [comment]
Hey @ahmadabugosh would you be willing to take on drafting this?

**Comment by ahmadabugosh** [comment]
Hey @c0ric0ri , maybe we can discuss this in the Comms meeting? 

Isn't it still in staging on [this link](https://fiat-38.vercel.app/)? I don't think it would affect GIVbacks or anything else would it? 

Some things we'd need to address in the email are:

1. How this is a staging environment, not our main site and how we're not storing any credit card details (since they may be concerned that their CC details are safe)
2. How they need to use real funds to test
3. Why would they do it (is there an incentive)? For example, could we ask them to donate Fiat to the Giveth project and give them nice tokens? (in addition to a POAP etc.)
4. What are things we'd want them to test? Is there certain behavior we should ask them to do? (donate in a certain way, using certain types of cards etc.)
5. Is there a form or way they can submit feedback? Since the people we'll be sending this to are not pro testers, we need to make it as easy as possible for them to give us feedback.
