### ISSUE TITLE
Gitcoin grants notion donation shortlist - highly curated partner grants

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1161]
Let's support other communities and xpollinate!

Key points:
- Share ReFI DAO (in climate round) - big opportunity for CS
- Include awesome projects in Climate & Eth Infra (so we are not sharing so many projects competing for OSS matching funds)
- Make it highly curated... perhaps 10-20 recommended grants (close close partners or orgs we can count on for RTs & shares)

@Cotabe has started this notion here:
https://www.notion.so/giveth/Gitcoin-Alpha-round-Giveth-s-fav-projects-f0395490ee9643a7bc6ac07dd6c4da0b

Here is his working spreadsheet:
https://docs.google.com/spreadsheets/d/1m8nPF8_AU3-jtrxBkUzGLTiXoEnojK9y3BZ8U5HKBq0/edit#gid=0

**Comment by Cotabe** [comment]
Here is the last version of it with our partnership with SolarPunk Guild https://www.notion.so/atlantian/adc482829bc84c06a1e19ed60b1df803?v=8d812dea2ccc4985b307a90b7c4844f0

**Comment by Cotabe** [comment]
I prepared a thread for the Xpollination, please share your feedback @laurenluz @c0ric0ri 

Humberto made his own thread with some of this explanation, we could post a link to his thread, but I think it feels cleaner just one thread, instead of a thread linking to another thread.

Here is how it would look like: https://typefully.com/write?ref=shared-draft&utm_content=header-logo

And here is a doc for comments: https://docs.google.com/document/d/1wOLZIPzeZcpxwHnQahomxU9psQ_D76bRpvYQlTVpi80/edit?usp=sharing

**Comment by laurenluz** [comment]
@Cotabe thanks! I set it up to tweet tomorrow. please have a look in the doc and lmk if the changes are all good w you.

**Comment by c0ric0ri** [comment]
https://twitter.com/Givethio/status/1618289145901682697?s=20&t=agjs9YxCZarDA1w4vt-ASg
