### ISSUE TITLE
Discussion on how to structure our GitCoin Grant Proposals

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#118]
Discuss in Fundraising channel. 
Giveth 2 initiatives only in the past.
Should the grant be for Giveth in general which covers everything? or do we need multiple grants?
Do we need a GIV Token grant?
Giveth 1 grant?

**Comment by Danibelle** [comment]
I think we will want multiple grant proposals.
Question is whether the current proposal "Giveth 2" stays solely for the new DApp and accompanying website launch or if we change the name to be more encompassing?

**Comment by Danibelle** [comment]
Discuss in Fundraising Discord!
https://discordapp.com/channels/679428761438912522/754748857849741323/816366004674363402

**Comment by magentaceiba** [comment]
My individual opinion on this one: As an outside person, I'm already overwhelmed keeping my mind straight around Commons Stack and Giveth and all the clusters of projects. As a marketing person, more grant proposals means I have to keep track of linking every person I outreach to to potentially multiple proposals - that seems difficult to communicate and adding friction of decision fatigue ("this is too complicated therefore I won't act on it because I don't have the brainspace.") Seems dilutive.

**Comment by Danibelle** [comment]
Consensus is to keep the one GitCoin Grant for Giveth.
My only concern is that people give such small amounts to multiple grant proposals, we are limiting our fundraising opportunity with the GitCoin Grant Round specifically...  but now we have the Panvala Coalition as a second Grant that will focus on the GIV economy so I think it's settled..

One Grant for Giveth
One Grant for the Regenerative Commons Coalition.
