### ISSUE TITLE
Explainer Video for GIVferral Landing Page

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1207]

**Comment by c0ric0ri** [comment]
hey @ahmadabugosh  , would you be up for working on a script for this?

**Comment by c0ric0ri** [comment]
When do you think you can have the script ready by @ahmadabugosh ? It would be really cool if we could have the video recorded by sometime next week since the page is ready for launch.

**Comment by ahmadabugosh** [comment]
Hey @c0ric0ri I'll work on the script, but the Chainvine landing page (the one users actually do the referrals on the Chainvine platform, not our landing page), is still not finalized. We did some testing and sent them a bunch of feedback that they should change this week. Once that's finalized and the workflow is clear, then I can start on the script.

**Comment by ahmadabugosh** [comment]
Hey @c0ric0ri, 

Here is the video I made for the landing page: https://youtu.be/02C9KcRNgP0

Please let me know if you have any comments @danelsuga @laurenluz

**Comment by danelsuga** [comment]
Great @ahmadabugosh !

Couple questions:

1. So are these 'secondary' GIVbacks (my term) given to the referrer precisely what their "rewards" are for the referral program? In other words, if someone makes a donation through the referrer's link, the GIVbacks that the referrer earns are their reward? Is there something else?

2. It's mentioned that these secondary GIVbacks are "a portion" of the donor's GIVbacks (quoting from the video). Does that mean the referrer takes a part of what the donor would otherwise have gotten?

One point for editing:

The first screen change is to "How it works." The second one is "How Rewards Work". Note the disparity in capitalization. I would suggest making them the same.

**Comment by ahmadabugosh** [comment]
Hey @danelsuga , 

1) Yes, so let's say I donate $100, I'll get my normal ~$70 GIVbacks, then if I refer someone else and they also donated $100, I would get an additional $10, so my total GIVbacks would be my GIVbacks plus a portion of the referred GIVbacks (in this case $70+$10=$80).

2) Yes, so if I am being referred by someone I would get less GIVbacks if I donate through someone else's link. So if I'm a new Giveth user and I donate $100, if I did NOT go through the referral program, I might get $70 of GIVbacks, but if I DID go through the referral program I might only get $60 of GIVbacks (since $10 would go to the person that referred me). We did it this way because it prevents people from gaming the system. If we had extra rewards on top of GIVbacks people would have incentives to always refer themselves through alternative wallets.

Does that make sense in the context of the video? I I didn't go into too much detail in the video because I didn't want to confuse people, and also the numbers might change (what percentage they receive etc.)

**Comment by danelsuga** [comment]
Thanks @ahmadabugosh 

1. OK. 

2. Maybe I'm missing something here, but what would compel someone to use the referral link at all, where their GIVbacks will be reduced, instead of just redirecting themselves to the project page itself and getting the full GIVbacks by contributing directly without a referral?

**Comment by ahmadabugosh** [comment]
2. Yes exactly, for someone that already knows about Giveth they would be incentivized to go to the project page directly since there is no benefit for them to go through the referral program. 

The target audience for the program is new users that we want to onboard onto Giveth (that would not have used Giveth otherwise), and the main ones that would be sharing it would be projects or ambassadors that are onboarding new users.

 So 1) New users would not be aware that they are receiving fewer GIVbacks in their first round 
 2) Even if there are made aware or if they ask, they're supporting the person or project that is onboarding them (which would be another reason why they would do it). For example, a project could say something like "Use our link to donate on Giveth and not only will you receive a portion of your donation back, but you'll also support our project further by increasing your impact" , so it's like another donation game and a way to amplify your donation. Now that I think about it, if projects use it it's kind of like quadratic funding in a way since they'll receive a portion of the GIVbacks "pool" of rewards.

**Comment by c0ric0ri** [comment]
Hey @ahmadabugosh, thanks for this great video!

I got a bit lost on the part, "How Rewards Work".

The giveth referral program is integrated with our givbacks program - that makes sense.

The next bullet point takes me off on a tangent that is distracting (especially if I am new to the GIVbacks program). I would instead skip straight to the third point, starting with - "when anyone donates through your link, you will earn a portion of their givbacks"

the line you mention right before that part, "now with the referral program, you can earn even more rewards on top of the givbacks program" - I think this is confusing and can be left out completely. yes you can earn rewards via givbacks when you donate normally and with the referrals you earn even more, but i wouldn't tie this together....it just adds a later of complexity. as a new user, i'm getting lost. let's just talk about the referral program on it's own.

then I would go from here to point 2 (but make it point 3) where you add some context about the GIVbacks program and encourage people to learn more. "As a reminder, the giveth givbacks program is..."

This is by the way a bit difficult to provide feedback on without the written script. Do you have a copy to share?

**Comment by ahmadabugosh** [comment]
@c0ric0ri @danelsuga I edited the video with your suggestions here: https://www.youtube.com/watch?v=WmCio7JxR8A

I kept the specific details out of it, and said we'll mention them in the docs (since the reward fees may change)

**Comment by c0ric0ri** [comment]
Thanks @ahmadabugosh for me it's so much clearer now! I personally think this is much better for the video, supported by the docs. Love the video! Maybe at some point we can expand the end with helpful suggestions of where the link can be used - "whereever you're sharing about giveth, like in social media posts, your blog, or website or telegram groups"
