### ISSUE TITLE
Referral Program Landing Page (on Giveth)

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1234]

**Comment by ahmadabugosh** [comment]
@mosaeedi Worked on a landing page for the referral program here: https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19398%3A246854&t=JvwdnaUnz96iSJl0-0

Any feedback on copy @danelsuga @c0ric0ri ?

**Comment by danelsuga** [comment]
Great, @ahmadabugosh ! I have some comments, such as using the word "terms" instead of "rules" on the banner and adding loads of periods for all the sentences without them. :D

And for the line "learn how you can become a chain in the giving network", I'm not sure that the metaphor of a "chain" is correct here. (In fact, it's a mixed metaphor, where calling someone is a "chain" in relation to a "network" is not really the case, since a network is not made up of chains.) It is possible to call someone is a "link" in a "chain" but that is not the right idea here. I would suggest something like, "learn how you can become a pathway in the giving network" or "a connection" or "point of connection". Perhaps something like that?

This is great! Thanks!

**Comment by ahmadabugosh** [comment]
hey @c0ric0ri @danelsuga , we have the page live here (we're not announcing it to the public yet, we're still testing it): https://giveth.io/referral

Let me know if you have any content suggestions

**Comment by danelsuga** [comment]
Looking great, @ahmadabugosh !

I've got just a few tiny suggestions:

Giveth Referral Program
Refer a friend, earn GIV tokens for every donation **made**.

1 Go to **Chainvine, and** connect your wallet.

3 Earn GIV tokens for each donation made through your link **[PERIOD].**

When others give, you earn**[PERIOD].**

**Comment by danelsuga** [comment]
Hi @ahmadabugosh and just some tiny edits in the text here: https://app.chainvine.xyz/giveth


1) Connect your crypto wallet **[PERIOD]**
2) If you’re a first time donor on Giveth, click the link under the **"Get Rewarded"** section to head to Giveth.
3) Donate to any verified project on Giveth**[PERIOD]**
4) That’s it! You’ll now be eligible for rewards in our next GIVbacks round (which happen every 2 weeks)**[PERIOD]**

**Comment by c0ric0ri** [comment]
Hey @ahmadabugosh I provided feedback on this copy several weeks ago through an issue on the dev board. It was already implemented. I'm also good with the way it looks now!

**Comment by ahmadabugosh** [comment]
Thanks @c0ric0ri , I just have a few minor changes below:

@mosaeedi @MoeNick can you help with these, 

1) For the third point, can you change it from "Earn GIV tokens for each donation made through your link" to "Earn GIV tokens for each donation made to a verified project through your link."
2) Please change "Up to 10% of the total donation amount!" to "An equivalent of up to 40% of the donation amount in GIV tokens!"
3) Can you change the video to this one: https://drive.google.com/file/d/1mgxdmkLtz34D-MOUCenUXK1AS-eFU0Ev/view?usp=sharing

Thanks!

**Comment by mosaeedi** [comment]
Here is the link to the updated design on Figma -> [Figma link](https://www.figma.com/file/hNqwpebu4JCy1XIed2c862/Giveth-Public?node-id=22-36561&t=pz3ZryuftcRIwqs3-4)

**Comment by ahmadabugosh** [comment]
@mosaeedi Looks good! I added some small comments, can we push it live by Monday?

**Comment by ahmadabugosh** [comment]
This has been update with the latest changes: https://giveth.io/referral
