### ISSUE TITLE
ETHDenver Tweet Thread to boost blog post - March 18

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1272]
Thread to shill ETHDenver:

ETHDenver is serious about making a positive impact, that's why they choose to partner with us and empower us to make a difference. This was the results of that partnership:

- supported us on impact quests
- pizza for the homeless
- ensured there was money available for impact track bounties
- giant booth positioning
- griff was a celebrity judge with prime talk space
- we were all in review crew for speaker applications

If you want to see more about what we were up to at ETHDevnver, check out this blog post (link)

**Comment by c0ric0ri** [comment]
@WhyldWanderer this would be a great place to add in stats on impact generated from the quests

**Comment by WhyldWanderer** [comment]
Total donations to local Denver projects during Impact Quests: 
5,037.35

**Comment by c0ric0ri** [comment]
@laurenluz @WhyldWanderer @oyealmond would love your input on this, trying to add in details how SporkDAO or ETHDenver supported us on each point

**Comment by laurenluz** [comment]
@c0ric0ri I took a look and left some comments. In the thread, it feels we're trying to make it seem like there was more impact than there really was.

I think this would better if it was shorter and more list-form. So we mention:
- funds raised
- hackathon projects w/ impact bounties
- brining people into crypto4good

in like 1 or 2 tweets and then ending w/ the blog post.

Do you have time for that? Otherwise, it's not the end of the world to put it out like this with minor tweaks.

**Comment by laurenluz** [comment]
ok nevermind, I did it and scheduled for today.
