### ISSUE TITLE
Create project survey results report - Google Looker & Sheets - 30 Mar

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#1301]
Using Typeform Survey results to create presentation to easily understand the results and make recommendations

**Comment by clara-zi** [comment]
Link to report:

https://lookerstudio.google.com/s/hRFzTNzqZQ8

**Comment by willmayrink** [comment]
Hi Clara,
So, I took a peek in your report, and I have a few suggestions to make. You're managing demographic data but using pizza graphics for it, while you can use a real Google Maps in order to increase the value of your report. Also, you're always keeping the same type of graphics for multiple data, that's not optimal in many cases.
I'll leave you with an example of a report I made for a sale's company. You can also feel free to contact, so we can generally improve the level of your report design skill!

https://lookerstudio.google.com/reporting/6c7d5f4a-9001-4ddd-a66b-3f75a7a497d0/page/tymjC

**Comment by clara-zi** [comment]
@willmayrink Hey. Thanks for taking an interest in the report I've started working on and for taking the time for feedback :) 

In this particular instance I think a pie chart for the location of respondents makes more sense than a map as a quick visual representation of percentage share is needed. But I'm open to persuasion. 

Also, the location data on the source .csv needs some manipulating before a map can be generated (is there a quick way to get it to the correct format to generate a map: I tried it?) I've use maps with Google Analystics as source data with Looker before and it produces a great result). The underlying data here has been generated through a Typeform. The underlying data is mainly score and survey responses.

I have just started to use Looker, so I'm definitely working on improving my design skills and welcome your tips.

**Comment by willmayrink** [comment]
About the pie chart; I totally get why you choose this one specifically; even though you could use the "size tip" of the ballon map to cover the percentage and always display the value, it comes just to personal choice.
The location data in looker is kinda weird sometimes; before the new update you basically didn't need any manipulation on data; even a text field would be reconized as a country's name the moment you would pick the ballon maps (for example). 
My report kinda 'got broke' after the update, it has something to do with cities and states; right now, you can't use the `CONCAT` function to join a citie name, state or territory abbreviation, and write the country name as a fixed label.

I'd love to help you through the development of any report, as I'm coming back to the IT industry and had always been my major skill collect and build data visualizations!
