### ISSUE TITLE
Lens promo - Tweet Thread

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1302]
Create a tweet to promote our Lens account

- tell the story of being shadowbanned
- we're excited to now be on Lens, a platform that prioritizes ownership of content, decentralization, etc.

**Comment by laurenluz** [comment]
@c0ric0ri what happened to this one?

**Comment by c0ric0ri** [comment]
Other things took priority at that time @laurenluz but I'm still happy to create this or have someone take it to promote our Lens account

**Comment by laurenluz** [comment]
I don't think our original approach is relevant anymore because so much time has passed since the shadowban, but maybe we could use a bit of that concept and make it more relevant.

I honestly haven't been posting consistently on lens lately though, it seems kind of pointless to post and no one see it. Maybe a thread strategically shilling lens (generally) and asking people to follow us might be a good 1st start.

when we talked, you suggested taking this becase you have some experience in the debates of lens vs. twitter, so open to your thoughts

**Comment by SteffanThorn** [comment]
@laurenluz could we get me logged into the lens account? 

I think it's a good idea to have this running. 

Included a draft for when we do:
https://docs.google.com/document/d/1-N8bWK_6Z-97TfBbddIxPRhnxtGE72SMh1CfYdN_sXg/edit?usp=sharing

**Comment by laurenluz** [comment]
great tweets @SteffanThorn - I can get you logged in, I'll set up a call w/ you to do it

**Comment by c0ric0ri** [comment]
I like this simple draft, thanks @SteffanThorn. Just added some adjustments to it

**Comment by oyealmond** [comment]
hey @SteffanThorn :) 

Does this got tweeted?

**Comment by laurenluz** [comment]
this did not go out, and Stee doesn't have access to our lens yet...

if we want to go ahead with activating our lens we can:
- get stee logged in
- start posting regularly... for at least a week?
- then share these tweets from twitter...

@oyealmond @SteffanThorn should we go ahead with that?

**Comment by oyealmond** [comment]
Ik @SteffanThorn is eager to take on Lens. 

My personal feeling is spending energy on Lens, really will not make a big impact on Giveth rn. 
I'll not invest time on it. 

wdyt @SteffanThorn ?

**Comment by SteffanThorn** [comment]
For now I'll get the hang of twitter and linkedin.
