### ISSUE TITLE
Update Gitcoin Grant for Beta Round - Grant - April 17

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1309]
We have from April 4 - April 17th to finalize the grant before it needs to be submitted.

**Comment by laurenluz** [comment]
Eligibility criteria is [here](https://gov.gitcoin.co/t/discussion-feedback-request-gitcoin-program-beta-round-eligibility/13306)

**Comment by laurenluz** [comment]
Starting here: https://docs.google.com/document/d/1idvNH_s5EQ5DhEHPwCCGUnE-tutVrWE389HMYZYWkkc/edit

**Comment by laurenluz** [comment]
Ready for review. Things to consider:
- we are allowed to include markdown formatting, so suggestions on imporant images/videos are welcome
- not sure if we should mention the Givers because "advertising" is against the gitcoin rules

@divine-comedian - can I get your eyes on here?
@MoeNick - did I miss anything important launches or milestones from Q1? or anything important upcoming that I should mention? can you have a quick look?

**Comment by danelsuga** [comment]
Good job @laurenluz. I gave a review and left comments.

**Comment by danelsuga** [comment]
p.s. hope my comments are helpful and nothing else! as always, what you put together is great. i try to read it as someone on the outside, and so some of my thoughts might seem rudimentary or coarse. definitely no reflection on your abilities. on the contrary! i know you know how to develop and integrate. always a superstar @laurenluz !

**Comment by laurenluz** [comment]
Thank @danelsuga - your comments were helpful.

I went though this again after edits from Griff & Suga, and I think it's good to go. Will put it up and submit to OSS round this weekend or early next week.

**Comment by laurenluz** [comment]
I have updated our grant in builder and will apply for the OSS round when applications are open, eta April 12

**Comment by laurenluz** [comment]
ok I applied for OSS in the core round

And also TEC & metacrisis

**Comment by laurenluz** [comment]
I applied also to Mantle
