### ISSUE TITLE
Celo Donations documentation - May 12

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1360]
We added Celo donations to the dApp. Our documentation should include this information, and also some docs will need to be updated to include Celo chain.

Soon we'll have to do the same as well for Optimism (and this already should have been done for Polygon)

@franculio - can you take this? and reach out if you are unclear?

**Comment by c0ric0ri** [comment]
Hey @franculio do you have a draft here already to share? How is our timeline for documentation updates on this?

**Comment by franculio** [comment]
Hey @c0ric0ri ! I have a draft ready, it's a modification of this doc here https://docs.giveth.io/dapps/projectdonating/ adding information about the new chains and how to switch networks. 

https://docs.google.com/document/d/1m0iI1h_PIf5q2V--khkhBc710l46yuLgh2VaO70DpAw/edit?usp=sharing

**Comment by franculio** [comment]
Maybe @danelsuga could review?

**Comment by danelsuga** [comment]
Lookin good!

**Comment by c0ric0ri** [comment]
@franculio the doc says we accept fiat donations, that needs to be removed. Left some tweaks and comments otherwise.

**Comment by danelsuga** [comment]
I didn't think that was really a problem since the credit card option shows up on the donate page and hopefully down the road it will be in action. I was personally thinking (like with the "recently") better to leave it and have it future ready since it's not actually disturbing anything. Just my thought though.

**Comment by danelsuga** [comment]
(As you know @c0ric0ri I am EXTREMELY IN FAVOR of getting Giveth back on track with the fiat project.)

**Comment by franculio** [comment]
Yeah, the fiat part is confusing. 

I guess it was there because of a previous on-ramping process we had. We still have an option to on-ramp fiat donations through Torus wallet but is not something you can access at this stage. Maybe we can clarify that is something that is "coming soon" and add a comment with a link to the Torus option:

https://docs.giveth.io/dapps/torusonramp

**Comment by c0ric0ri** [comment]
@danelsuga I just see it right now as confusing and incorrect, since we don't have the option and there is currently no forecast on when we will have it available. I am also strongly in favor of getting fiat added, but I would definitely remove it until we have that available, or at least clarify that it's a future thing as @franculio suggests.

**Comment by franculio** [comment]
I've added what was commented on the draft and this is how it would look like: 
<img width="953" alt="Captura de Pantalla 2023-05-19 a las 13 04 27" src="https://github.com/Giveth/giveth-planning/assets/79286405/ab3752e4-3b89-4cfc-8ac2-755097c25d88">

@c0ric0ri @danelsuga Let me know if this is ok with you and I can update today.

**Comment by franculio** [comment]
The doc has been updated, I've taken out the fiat donations part according to Lauren's suggestions, check the update here https://docs.giveth.io/dapps/projectdonating

Issue can be closed!
