### ISSUE TITLE
Optimism Campaign Strategic Outreach

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1376]
We have money from optimism so that the 1st 640 projects who add an optimism address get 25 OP donated to them.

We should make a campaign of tweets explaining this to projects... and also we can use as a piece for outreach to other projects.. get them on Giveth, get them verified & adding optimism.

Optimism is going a lot with grants and RGPF and if we can make a focused efforted to onboard projects to optimism, it would be really good for our ability to fundraise.

@oyealmond @c0ric0ri @ahmadabugosh @WhyldWanderer - can you support on this? Needs tweet writing but also creating a other outreach tasks.

**Comment by oyealmond** [comment]
Sure. [Drafted the actions for the Op campaign](https://docs.google.com/document/d/1gx13tFyhnhPZ5lEFcxeIydU9aeqVcG5-WUWmCZn3uMk/edit?usp=sharing), starting this Monday. 
Could you check it out @laurenluz?

**Comment by laurenluz** [comment]
Epic @oyealmond !! This is fantastic jumping off point. I left a couple of comments & ideas.

**Comment by oyealmond** [comment]
loved the ideas! thanks! 
Already added them to the doc. @laurenluz

**Comment by c0ric0ri** [comment]
Running list of nonprofits & projects to reach out to: 

https://docs.google.com/spreadsheets/d/1lBITH5PXNDsfLsKNERmDCp2xFFWZ3_WUHbdLLJ5kHpY/edit#gid=0

**Comment by oyealmond** [comment]
hey @ahmadabugosh! Could you please draft an email tu our existing project database explaining what they should in order to be eligible to get 25 OP? You can find all the info [here](https://docs.google.com/document/d/1gx13tFyhnhPZ5lEFcxeIydU9aeqVcG5-WUWmCZn3uMk/edit) or in this issue. 

Let us know if you have capacity, or if I or maybe @danelsuga could jump in and support.

**Comment by ahmadabugosh** [comment]
@oyealmond I made a draft of this email here: https://docs.google.com/document/d/19s31miH8Ysi-nH89X7lWiMWsZdgJF40LGa7k-eRfJbc/edit

CC @danelsuga for review

**Comment by oyealmond** [comment]
Thanks @ahmadabugosh! 

@laurenluz plz also help us reviewing Ahmad's draft and [these tweets](https://docs.google.com/document/d/1s-JCBJX1XMWALZgtU-4o7XMohP-jTRUN47dkXMrwCIs/edit) whenever you can.

**Comment by danelsuga** [comment]
Looking good, @ahmadabugosh. I left some comments for edits. I did not critique the content or format. I think it's good.

**Comment by c0ric0ri** [comment]
Note: Projects must be verified to get this reward

**Comment by c0ric0ri** [comment]
Hey @ahmadabugosh where can I find the list of projects that have received funding from Optimism with RPGF?

**Comment by oyealmond** [comment]
here @c0ric0ri . Is a great list to reach out actually https://app.optimism.io/retropgf-discovery?tab=All%20projects
Great idea @ahmadabugosh . Thanks again.

**Comment by c0ric0ri** [comment]
Here is the running list of projects to do outreach to, who have received funding from Optimism for RPGF.

https://docs.google.com/spreadsheets/d/1-OdcQZJGMB2hU1Q4m71RbjISAp_AEQ7_0nh0vlN7Axg/edit#gid=0

**Comment by c0ric0ri** [comment]
Included an outreach message in the second tab of the table. @ahmadabugosh @laurenluz @oyealmond let me know your thoughts.

I'm thinking Algene can help with the outreach here? I'm not sure how good it is to do this from Giveth's account, given the previous shadowbanning....

**Comment by oyealmond** [comment]
i think is great. @c0ric0ri will be great if you can coordinate w/ Algene about it.

**Comment by oyealmond** [comment]
Found more Op projects for outreach https://app.optimism.io/retropgf-discovery?tab=All%20projects 
Some of them might be duplicated in your list @c0ric0ri

**Comment by c0ric0ri** [comment]
It looks like they are almost all duplicates @oyealmond....I think it's just the same list? Thank you though. It already took a lot of time yesterday to build the sheet from this page, so I think I'll just proceed with moving outreach forward now

**Comment by laurenluz** [comment]
Looking at the outreach message (I edited a tiny bit already):

> Congrats on receiving RetroPGF from Optimism!
> Due to our new partnership with Optimism, it's now possible to fundraise for your project on Giveth on Optimism Network.
> And to get the word out, we're rewarding the first 640 verified projects who add Optimism to their receipient addresses with 25 OP (courtesy of Optimism).
> We thought this might be interesting to you as a new option to fundraise on Giveth's platform!
> Just head to Giveth.io to add your Optimism address, or hit us up in Discord for any questions.
> 

This is really missing a key part... if we are doing outreach to projects that are not already on Giveth, they would need to create a project, then get verified.. and have an optimism address added at some point too...
We should (if the project isn't on Giveth)... invite them to fundraise on Giveth, explain the benefits of getting verified/fundraising on Giveth... and then sweeten the deal w/ the OP incentive.

As it is, I feel like it's missing a lot of the meat of this - like what it even means to raise funds on giveth/get verified. @c0ric0ri

**Comment by c0ric0ri** [comment]
@laurenluz yes.....but, we do say we're rewarding the first 640 *verified* projects. In my opinion the point of this campaign is letting new projects know about this special opportunity, and use that to incentive new projects to get on Giveth. And yes, they need to get verified to get the 25 OP....but that's just part of the sign up process in this case.

So I would say we could add a small line like:

**Comment by c0ric0ri** [comment]
Here is another version, is this what you were more thinking? @laurenluz 

Congrats on receiving RetroPGF from Optimism!
Due to our new partnership with Optimism, it's now possible to fundraise on Giveth on Optimism Network.
With Giveth's platform, you can raise funds in crypto for your project. We work with multiple chains and we take no fees, so 100% of donations go straight to you.
And if you are approved for verification, donors to your verified project will receive rewards in the form of GIV tokens.
To promote our new partnership, Optimism is offering 25 OP to the first 640 verified projects on Giveth who add Optimism to their recipient addresses. So if you're interested to get on Giveth, now's a great time!
Just head to Giveth.io, and make sure to have your project verified for eligibility. Connect with us in Discord for any questions!
https://twitter.com/Giveth/status/1655905986824093698

Congrats on receiving RetroPGF from Optimism!
Due to our new partnership with Optimism, it's now possible to fundraise for your project on Giveth on Optimism Network.
With Giveth's platform, you can raise funds in crypto for your project. We work with multiple chains and we take no fees, so 100% of donations go straight to you.
And if you apply for verification, donors to your verified project will receive rewards in the form of GIV tokens.
Optimism is offering 25 OP to the first 640 verified projects on Giveth who add Optimism to their recipient addresses. So if you're interested to get on Giveth, now's a great time!
Just head to [Giveth.io](http://giveth.io/), and make sure to have your project verified for eligibility. Connect with us in Discord for any questions!
https://twitter.com/Giveth/status/1655905986824093698

**Comment by laurenluz** [comment]
@oyealmond - tweet thread scheduled for today!

**Comment by laurenluz** [comment]
@c0ric0ri I think they're both good! I have a slight preference for the 2nd version, but feel free to go with whatever feels better to you.

**Comment by laurenluz** [comment]
@oyealmond - it might be nice to break this issue into an epic to keep better track of all the parts! Or at least, let's do that for the next one.

@ahmadabugosh I made some edits to the email, check in w/ @oyealmond re: timing for this to go out since she's overseeing this campaign's moving parts!

**Comment by oyealmond** [comment]
Yeah, agree @laurenluz! 
@ahmadabugosh is sending the email Monday. 

What's only missing from this issue is the outreach campaign. Let's use this issue to track the progress on the outreach. cc @c0ric0ri

**Comment by ahmadabugosh** [comment]
@oyealmond, the email has been sent

**Comment by c0ric0ri** [comment]
Hey @oyealmond , yes we just needed to get Algene on Giveth's Twitter account today. it's in progress. She's going to help with getting the draft message out to all the Optimism projects who received RPGF

**Comment by oyealmond** [comment]
hey @c0ric0ri ! 
I saw the DMs , I think the outreach is done! or maybe I'm wrong, could you provide some light around it? Thanks!
