### ISSUE TITLE
Aprendamos ReFi podcast launch - Twitter thread - May 17

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#1378]

**Comment by Cotabe** [comment]
Here is the doc:

https://docs.google.com/document/d/1i-LSKhXNMXO4tqEhZX7ytFzzECuzxw-tZFBqm7XgNbA/edit

**Comment by Cotabe** [comment]
@oyealmond @c0ric0ri @laurenluz 

I would like to get your feedback on this Twitter thread to promote the Aprendamos ReFi podcast launch.

I wrote it in Spanish since the whole podcast audience is Spanish speakers.

**Comment by c0ric0ri** [comment]
Hey @Cotabe I gave it a round of reviewing. But the final details of the copy I'm limited with so definitely needs another check.

By the way I renamed this issue with more detail (topic - content type - date it needs to go out), and also moved this issue to the right status (Review/QA). Please make sure to keep this in mind for issues, it helps a lot to find things :)

**Comment by c0ric0ri** [comment]
Oh and same thing as the other issue, do you have a cover image you wanted to use to advertise it?

**Comment by Cotabe** [comment]
Thanks for reviewing it so fast @c0ric0ri 

Thanks for the feedback. I will be more diligent with dates and status. I applied the changes recommended. 

@oyealmond can you do a second review & direct us to the designs?

**Comment by oyealmond** [comment]
hey @Cotabe ! I review this, but I think will be better if the tweets are written in English as the Giveth social media brand voice is in English. The way we've manage copies like this in the past is the we have the English tweet with some Spanish words. 

But I will love to count with @laurenluz's opinion on this too. 


Thanks!

**Comment by oyealmond** [comment]
@Cotabe here's the[ Figma with the design](https://www.figma.com/file/mzl8UhfYNgLofMoL4BwM1A/Podcast-Cover?type=design&node-id=0%3A1&t=ap5uGE1HxghMy0Dq-1). We only count with one format cuz the designer that made this is not longer in Giveth anymore 😬

If you want to create the launching image, I made already a design for. it, you will need to create a copy of the Figma file in your board in order to edit it. If you want me to make the design please provide all the details you'll like in the cover.

**Comment by laurenluz** [comment]
I do agree with @oyealmond here, and I was thinking this also in yesterday's call (I just didn't want to be too nay-saying).

Giveth's Twitter audience is english speaker. I think it's nice to throw a bit of spanish in there, but provide the context in English. otherwise, it doesn't quite make sense for our audience.

Many orgs create separate, spansih-speaking of other language accounts where the post exclusively in other languages.

**Comment by laurenluz** [comment]
also did we say we want to launch this on Monday?

**Comment by oyealmond** [comment]
yes @laurenluz this monday exactly

**Comment by Cotabe** [comment]
Ok, that's fair enough. I will translate the tweets. I guess the same goes for linked in & email.

**Comment by c0ric0ri** [comment]
Thanks @Cotabe ! And yeah please don't hesitate to raise this next time @laurenluz @oyealmond, no problem. I know we put out content in Spanish sometimes and as this content is geared towards that audience, it seemed cool to put out a thread in Spanish in for the launch. But totally makes sense to make it more of a combination.

**Comment by Cotabe** [comment]
The thread is translated now. 

Let me know your thoughts. I will translate all other comms by the end of the day.

@c0ric0ri @oyealmond

**Comment by c0ric0ri** [comment]
Added my comments @Cotabe!

**Comment by laurenluz** [comment]
great edits @c0ric0ri and great thread @Cotabe 

would like to finish this off. left a comment at the top.

@Cotabe can you make a list of twitter handles of latam web3 communities that we should tag?

**Comment by laurenluz** [comment]
Also I need an actual image for this

**Comment by oyealmond** [comment]
here's the image
@laurenluz @Cotabe 
Let me know your thoughts
https://drive.google.com/file/d/1ROIcX0v0mukVfhkZ2LyfITaJINUW2ai_/view?usp=sharing

**Comment by Cotabe** [comment]
I made the last edits to the thread. Let me know if we are missing anything else for scheduling the tweets

@laurenluz @c0ric0ri

**Comment by laurenluz** [comment]
Thanks @oyealmond @Cotabe - it is scheduled for monday at 6am costa rica time

**Comment by Cotabe** [comment]
We were missing the youtube link on the thread. Can you help us updated it @laurenluz

**Comment by laurenluz** [comment]
https://twitter.com/Giveth/status/1660617020990210050
