### ISSUE TITLE
Check & possibly improve the content of the "sorry you didn't get verified email"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1422]
with all the rejections we are putting through, we should make sure this "sorry" email is up to date

@NikolaCreatrix @WhyldWanderer - can one of you take this?

cc @oyealmond

**Comment by WhyldWanderer** [comment]
Here is the current copy:
![image](https://github.com/Giveth/giveth-planning/assets/74267818/fc3712c6-6dd8-4d08-ae4e-94aa5f46c45c)


I feel like I already did the best job that I could and it was previously reviewed by comms. 
Im always open to feedback and making any adjustments though.

Also, something to think about that could be better..
Anytime, the verification team rejects an application we make a comment in the AdminBro that describes why the project was rejected and what we would need to see in order to verify the project. 

I have made an issue in the dev repo to explore the idea of somehow bringing that comment to this email through a Segment Autopilot connection or somehow conveying the reason through the notification center - you can find the issue here https://github.com/Giveth/giveth-dapps-v2/issues/2716

**Comment by oyealmond** [comment]
Related to https://github.com/Giveth/giveth-planning/issues/1422

**Comment by laurenluz** [comment]
yeah @WhyldWanderer  I don't think necessarily the copy is bad, but maybe let's like @NikolaCreatrix have her opinion based on her experience... and if we don't want to change anything about the copy, we can just close this. (this was by her suggestion in the comms call)

**Comment by NikolaCreatrix** [comment]
Looking at this email, it already is so great! It's kind, friendly, and motivating. It does cover ALL the common reasons for rejection, we ask them to come and talk to us. (I mean ideally, they want to come to talk to us!) We tell them to re-apply after showcasing more... 

I think the problem isn't here, and even though it would be cool to provide owners with customized/case-to-case response emails, when we do comms and promote project verification, we can be more transparent about how amazing and qualitative our screening process is with 
a) we need to see some history of action and impact made, (we don't verify an idea), 
b) need to be able to assess enough rep at stake (enough following, non-profit status, support from someone who can vouch for them), 
c) the project isn't oriented toward personal gain but rather toward creating a social/public good.  

I think promoting more about how our verification system works and how much we care for supporting projects that already ARE doing the work, is one more incentive for impact (random) donors to come because they can see our projects are trustworthy. And their crypto makes an instant impact.

Seeing this inspires me to go back to improving our documentation so I will work on that now here... #1368

**Comment by oyealmond** [comment]
Agree this is more of a case by case response. Def we can follow in the devs issue @WhyldWanderer opened & complementing the documentation as @NikolaCreatrix suggests. 

Thanks!
