### ISSUE TITLE
Autopilot organization. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1429]
Hey @ahmadabugosh! 

Let's review the Autopilot situation and how could we organize Giveth's emails. 
Let's dedicate some time in our next comms call to review the next steps. 

To prepare before Tuesday, maybe we could bring the actual journeys we have? 
I hear @WhyldWanderer & @laurenluz autopilot is a mess, but I'm not sure in what sense. 

@WhyldWanderer @ahmadabugosh could you provide some info in the context please? 

Thanks!

**Comment by oyealmond** [comment]
Thanks for the hard work @ahmadabugosh! 

Here's our next steps to organize Autopilot: 

    - Meeting with Carlos to talk about the segments & triggers.
    - Audit of existing emails and triggers and roadmap [here](https://docs.google.com/spreadsheets/d/1d34y9rsX8LU--kI7b-EcAfEhkt3XlWhew2Eiu8KlE7E/edit#gid=0) for what to implement next 
    - Create new journeys Ex. GIVpower. Mandatory updates (cc @WhyldWanderer) 
    
    **Next Steps:** 
    
    - Talk w/ Mo regarding the next segments.
    - Implement the onboarding sequence.
    
    **Comments:**
    
    - Weird sequences, check with Carlos. cc @WhyldWanderer , could you provide more info on this weird issue?

**Comment by geleeroyale** [comment]
Hi everyone! I stumbled upon this issue by accident. I was actively researching alternatives to autopilot, but relized I have to collect more requirements because all these CRM tools have tons of functionality, but we most likely want to use similar tools to what autopilot brings. So - in short - devops can help here, but would need to know more about how its actually used.

I hope we can find a different solution than using segment. First, because in the long run we want to get away from Segment as well. Its not cheap and at this point I would like to collect requirements here as well.

Happy to jam, with you on this @oyealmond @CarlosQ96

**Comment by oyealmond** [comment]
thanks @geleeroyale ! actually @CarlosQ96 & @ahmadabugosh are currently working on this, I'll love for them to reach out to you to figure out the support from devops!

**Comment by oyealmond** [comment]
we could close this too @divine-comedian
