### ISSUE TITLE
DevOp Tweets

### ISSUE THREAD

**Issue by SteffanThorn** [Giveth/giveth-planning#1433]
Made this because of @hanners-717's request and hearing we need more people. 

https://docs.google.com/document/d/1-4YTaAg8FW2V451uRCUDtcZefGfocXlpYfw4ve0muas/edit?usp=sharing

@laurenluz looping you in

**Comment by laurenluz** [comment]
Thanks for creating the issue @SteffanThorn - the 1st one is ok (I edited a little) - you can schedule it.

We should write a couple more that mention America time zone...

Copy/pasting my comment here:

"DevOps is like the name of the WG... you wouldn't say "a DevOp"

Basically DevOps does all kinds of magic I don't understand like running servers and making sure that our site doesn't go down... 

They also do some security work... work on efficiency.

The main point here.. is that we want someone in the Americas... because we have great devops people... one in the middle east, one in europe... we want one in the americas so if "things go down" we basically have 24 hr DevOps support/coverage.

If you want more info, you can ask Kay (@geleeroyale) who runs the DevOps WG... 

but anyway... the last tweets could be improved... and I think the point about "in the americas" is critical here. America timezone... mexico, colombia... canada, etc...

doesn't have to be states, but in the western neck of the woods."

**Comment by SteffanThorn** [comment]
Added a new tweet. Left a comment. Let me know if it's good to schedule.

**Comment by laurenluz** [comment]
yeah, go ahead and schedule the 1st two

**Comment by SteffanThorn** [comment]
scheduled one for today and one for tuesday.
