### ISSUE TITLE
QF info Notion 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1445]
Create a Notion gathering all the QF info, to kick off QF comms. cc @laurenluz :)

**Comment by laurenluz** [comment]
Ok, set it up in [notion here](https://www.notion.so/giveth/QF-Marketing-Guide-1f0dd6cbca7e413b9aa6c948fd8d7596).

@oyealmond @WhyldWanderer - can we start this off by having you two review the doc, and make an comments/questions/concerns? I can add to it with more info if there's something missing.

Then maybe we can involve the rest of the comms team, get a bit of a brainstorm & breakdown of tasks, and then assign people and get support. wdyt?

@SteffanThorn I want to loop you in here too because I think you could help with some marketing ideas.

**Comment by oyealmond** [comment]
Great! Agree the best start is documentation. That will give the social media & comms team the complete info to create the rest of the materials. I think a good start is kicking off documentation w/ @franculio, maybe @laurenluz & @franculio could you get together to review this? Would you prefer having more team members to synch about documentation?

**Comment by franculio** [comment]
@oyealmond I started this doc to create the structure for the doc based on the notion and the spec. Most of the things I don't know how to start since they're still to be defined. Any input will be welcomed! @laurenluz 

https://docs.google.com/document/d/1rsEO4jsLIGRtLgiIOqrCu4CcOERgtRehcoml1foJHk4/edit?usp=sharing

**Comment by laurenluz** [comment]
@danelsuga @GriffGreen @divine-comedian @NikolaCreatrix - tagging you in here so you can have a look at this notion and support with comms & marking around QF.

There are going to be a lot of things to manage:
- emails
- Twitter spaces
- fundraising
- project onboarding
- social media campaigns

etc. etc. 

So we will really need the full team's support to make these QF rounds a success!
