### ISSUE TITLE
Create an email for announcing the round is Live

### ISSUE THREAD

**Issue by franculio** [Giveth/giveth-planning#1459]

**Comment by franculio** [comment]
Started a quick Chatgpt first draft here:

https://docs.google.com/document/d/1PHt3K7vNoI1EZI1gTE089hX0d-c9GgxS71ZLMuC75GA/edit?usp=sharing

**Comment by franculio** [comment]
@danelsuga do you think you help with this? 

Cc @laurenluz

**Comment by danelsuga** [comment]
Thanks for the groovy draft @franculio ! I made some edits. Seems pretty ready to go apart from one turn of phrase I'd like some support with @laurenluz ? :D

**Comment by danelsuga** [comment]
This one is looking done too, I think. @laurenluz

**Comment by laurenluz** [comment]
Hey @danelsuga ! Just had a quick look, this is much better too... just, I think we can adjust the tone a little.

The alpha round is meant to be like a relatively small test thing... we're not 100% sure it's all going to work perfectly so the idea is to have a small round with familar projects... get people to use it/donate/test... and also let us know if they find any issues so we can improve them for future rounds.

I wouldn't call it, for example, the "inaugral round" because it sounds too exciting/enthusiatic 😅 - it's an alpha test. real money, real project, real site... but we haven't worked out all the kinks.

maybe you can make a quick pass with that in mind? and if you could also mention like... if they find any bugs or have feedback, let us know here: https://giveth.io/support

**Comment by laurenluz** [comment]
like it's good to be enthusastic and get people into it... but also try to get them to like... have a little bit of an open mind as we work on the kinds w/ our community's support.

**Comment by danelsuga** [comment]
OOoooooo gotcha!

**Comment by danelsuga** [comment]
OK, modified!

**Comment by laurenluz** [comment]
Thanks @danelsuga ! I made some direct edits just to shorten it, and I think it's good to go now!

@WhyldWanderer or @ahmadabugosh - can you help us set this up to go out to our full email list once I give the go-ahead tomorrow? estimating 4pm CET Tuesday July 18
