### ISSUE TITLE
QF Partnership Tweet Thread

### ISSUE THREAD

**Issue by franculio** [Giveth/giveth-planning#1461]
Create a tweet thread mentioning all of the partners who have collaborated to the Alpha round (Quadratic Force). 

Here's a document with more information about Quadratic Force (benefits and requiriments):
https://docs.google.com/document/d/1I3t8WXQA8J9OaumL8NLo2VWkkQqvWHAWYVrCbZAQPoo/edit

**Comment by laurenluz** [comment]
we should basically say like "QF alpha is made possible thanks to our partners"... and then one tweet per partner...

if we have bigger partners & smaller partners... we can do like one thread w/ all... and then extra tweets for the bigger partners.

@oyealmond - can you take this on when you're back from vacay? we'll have our list of partners hopefully by friday and this can go out next mon/tues/wed etc.

**Comment by oyealmond** [comment]
Hey @laurenluz @SteffanThorn, [here's the draft of the QForce](https://docs.google.com/document/d/1LJpH2LaOco1T3nh9AmbrEjQfOCzc6cbA3tjTjo0L-rY/edit?usp=sharing) thread. Please revie, & let me know your comments.

**Comment by laurenluz** [comment]
edited and scheduled!

**Comment by oyealmond** [comment]
thanks @laurenluz 🥹

**Comment by oyealmond** [comment]
Twitter: https://twitter.com/Giveth/status/1682351593285361666
Instagram: https://www.instagram.com/p/Cu9jhlWADia/

@laurenluz do we still need separated tweets for the three major donors?

**Comment by laurenluz** [comment]
Yes!

**Comment by oyealmond** [comment]
Repeating the same info of the tweet thread? Meaning, a separate tweet about them again @laurenluz

**Comment by laurenluz** [comment]
I think the posts later in the thread are less likely to get engagement that the first posts. we did something like this for the turkey fundraise and the later posts were never liked by anyone...

Is there something I'm missing?

In order to make good on our promise to them, we need to give each an equal spotlight. I edited the thread and broke it into 3, will schedule them starting tomorrow unless we decide something else.

@oyealmond - can you edit the images to take out the text "thank you for your support"? I think it's cleaner just to have the logo, the name & "Giveth Quadratic Force"

**Comment by oyealmond** [comment]
got ya @laurenluz . 
Thanks so much for the feedback and for the help editing!

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1684942327289180160 
https://twitter.com/Giveth/status/1684217554384846855
