### ISSUE TITLE
tweet thread non profit funding

### ISSUE THREAD

**Issue by SteffanThorn** [Giveth/giveth-planning#1480]
Made a first draft on ways nonprofits can get funding. 

https://docs.google.com/document/d/1YHt_AoJziUcoc_Y3rpTm4sapxwOH2azCe6I38SAHy_w/edit?usp=sharing

@oyealmond @laurenluz

**Comment by oyealmond** [comment]
mm, I don't really like the content of this thread. I think will be cool if is dedicated to the different types of funding available in Web3, and promote Giveth more. Instead of mentioning VCs, that really don't have a lot to do w/ the GIveth brand. I would change the approach to something more like: 

Different types of Web3 funding: 

Quadratic Funding - this QF, Giveth launched recently Alpha Round... 
Retro PGF - Optimism leads this types of funding... And it work retroactively which means... 
Crowdfunding - Giveth is a good option for crowdfunding campaigns.. 

What others Web3 funding do you know? 

****

@SteffanThorn

**Comment by SteffanThorn** [comment]
We can definitely do the angle you're mentioning. 

What I'm thinking is to hit a wider audience, but I'll start with this angle you've mentioned and see if I can widen the scope in the hook.

**Comment by SteffanThorn** [comment]
Here's a draft on this angle https://docs.google.com/document/d/1_WpOhdEsbA-nUQvspFTUlsubBMBX89DeXidm3YzdpkQ/edit?usp=sharing

**Comment by laurenluz** [comment]
reviewed!

**Comment by SteffanThorn** [comment]
scheduled for Aug 11th 
@oyealmond this is flexible for moving to another day if need.

**Comment by oyealmond** [comment]
thanks @SteffanThorn @laurenluz  ! I saw it scheduled, the final edits are great!

**Comment by SteffanThorn** [comment]
https://twitter.com/Giveth/status/1688973861977526295

**Comment by SteffanThorn** [comment]
closing this
