### ISSUE TITLE
tweet tread twitter presence 

### ISSUE THREAD

**Issue by SteffanThorn** [Giveth/giveth-planning#1481]
thought it would be a good idea to make a thread on ways people can improve their twitter presence. 

(we could also do something similar for instagram) 

First draft:
https://docs.google.com/document/d/1vpml0Ht5gkBnyhffaR6e3o_UKOwktyofKtpYtm9T9GI/edit?usp=sharing

@oyealmond @laurenluz

**Comment by oyealmond** [comment]
I like the approach but, I will love to see more of "Giveth applied" tips, instead of only Twitter. A more general approach of how to build an online presence if you're a public goods project. @SteffanThorn 

This thread could cover: 

· Interact w/ your community
· Provide regular updates of your work
· Create content
· Build partnerships.

**Comment by SteffanThorn** [comment]
Thanks for the suggestions @oyealmond 
I've added to the list of ideas. 
Let me know what you think.

**Comment by oyealmond** [comment]
I made a proposal @SteffanThorn

**Comment by laurenluz** [comment]
reviewed

**Comment by SteffanThorn** [comment]
Edited based on suggestions. 

Please review again @oyealmond @laurenluz 

Would be good to see your opinion on this too @missgene

**Comment by laurenluz** [comment]
looks great! I made some direct edits because I found some small typos, but other than that, it's great.

**Comment by oyealmond** [comment]
Want to schedule @SteffanThorn?

**Comment by SteffanThorn** [comment]
scheduled for Aug 21st @oyealmond 

If there is an event specific thread coming out that day, I suggest move this thread to another day.
