### ISSUE TITLE
Stretch MVP Reqs ~ At time of donation, Donors are told they will receive up to 75% of their donation in GIV tokens

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#152]
## Stretch MVP Requirements

- At the time of donation, Donors receive a *moment of surprise* notice that they will receive up to 75% of their donation in GIV tokens. 
- We inform them of the day and time that the round will end so they can stay engaged with the platform. 
- Then they will be able to come back and check how much they will get once the round finishes.

**Comment by markoprljic** [comment]
We want to have a moment of surprise for users and **not tell them in advance** how much they will get.
The donor is excited about supporting a project, they don't care about what they get in return, they have no expectations BUT they do get ownership of this cool donor-owned platform Giveth.

**Comment by ForestSoleil** [comment]
^ What do you think about this @willyogo @GriffGreen @bowensanders @divine-comedian @WhyldWanderer @laurenluz ?

**Comment by laurenluz** [comment]
hmm well, won't we only know how much they'll get once the round is over and we determine how much was donated? so it would also be hard to give an accurate estimate.

I think we should tell the Giver the USD of their donation at the time the donate... and then emphasize that they are eligible to receive a maximum of 75% of that.

**Comment by WhyldWanderer** [comment]
From my understanding, we have no way of knowing how mich GIV they will receive until the end of the round since it is dependant on how mamy donations are made within that round.

I like the moment of surprise that marko refers to... at the time of donation, we tell them they will receive up to 75% of their donation in GIV tokens and we inform them of the day and time that the round will end so they can stay engaged with the platform. Then they will be able to come back and check how much they will get once the round finishes.

**Comment by ForestSoleil** [comment]
I love both of your responses, Lauren & Ashley! Thank you for chiming in. 

@markoprljic I am updating the title of this issue to be more reflective of what we've decided based upon your suggestion.

**Comment by divine-comedian** [comment]
+1 Ashley's comment!
