### ISSUE TITLE
Reuse exisiting blogs and content and publish it on Giveth's website to improve SEO

### ISSUE THREAD

**Issue by surbhiaroraa** [Giveth/giveth-planning#1535]
Hi @ahmadabugosh,

Currently a lot of great project and donor resources are outside of Giveth's website (Medium, Youtube). Its very important to have that content on our website. Hosting our blogs directly on your company website can provide several benefits from an SEO perspective:

_1. Increased Website Traffic: When we publish blogs on our own website, it can drive organic traffic directly to our site. This helps to boost our website's overall visibility and authority in search engine rankings.
2. Improved Website Authority: Consistently publishing high-quality and relevant content on our website can establish our site as an authoritative source in our industry or niche. Search engines often reward authoritative sites with higher rankings.
3.  Enhanced User Experience: Keeping our blogs within our website ensures a seamless user experience. Visitors can easily navigate between different sections of our website, including our blogs, without leaving our domain.
4.  Internal Linking Opportunities: By hosting blogs on our website, we can take advantage of internal linking strategies. Internal links can help guide visitors to relevant pages on your website, improving navigation and SEO.
5. Reduced Bounce Rate: When visitors read our blogs on your website, they are more likely to explore other pages and sections. This can help reduce our website's bounce rate, which is a positive signal for search engines._

Reference content:
https://blog.giveth.io/the-abcs-of-creating-a-project-on-giveth-55ff82c060f8
https://blog.giveth.io/the-abcs-of-donating-on-giveth-6e3bd147397e

**Can we use all our existing content on different channels like Medium, Youtube etc and republish on our website. With little to no investment in creating new content we can improve our SEO massively.** 

cc: @oyealmond @divine-comedian

**Comment by ahmadabugosh** [comment]
hey @surbhiaroraa , I love the idea, but I don't think if moving the blog content to the website would have that much of an effect. 
Mainly because we recently moved the blog to a subdomain (blog.giveth.io), so that helps our main domain get more authority, and the blog already ranks high for a lot of searches. Also, I think the tone of the blog is very different and more casual compared to the main website content. I think it makes sense to keep both.

Having said that, I think it's a good idea to repurpose other content. For example, we could use AI tools (like Descript that we're already using for social media videos), to transcribe some of our Youtube videos or talks from conferences into blog posts or landing pages. That would be very easy to do (it probably wouldn't take more than an hour per talk to proof read), and I think would have a lot of benefits since they would be long-form pieces of content with a lot of relevant keywords.

**Comment by SteffanThorn** [comment]
@ahmadabugosh 
What you're describing is probably google thinking the subdomain is the authority site. 
Subdomains are technically different entities so don't transfer authority to the root domain. 
We could "migrate" the blogs to the main domain, with redirects and additional checks. 
I don't think the tone of voice is an issue -- maybe some more flamboyant language could be altered.

**Comment by ahmadabugosh** [comment]
@SteffanThorn I think it's a debatable topic. SEO has thousands of signals it looks at, and I do agree we won't get as much effect as having everything on the root domain, but it does have some positive impact even as a subdomain from what I've seen.

A couple more points, one benefit of having 2 places (the blog and main site), is it lets us rank for things twice. For example, for the blog post @surbhiaroraa mentioned, we're designing an onboarding page around the same topic but it feels more organic because it's tied directly to our branding and integrated with actions on our site.  Because of that we're basically ranking twice for similar keywords. 

Also, our blog is on Medium and it doesn't allow for subfolders (like giveth.io/blog), so we had to put it on a subdomain.  Maybe we can revisit some of the articles once the dev team finishes with their new landing page creator tool ([see this issue](https://github.com/Giveth/impact-graph/issues/1102)), which would make it easier for us to post our the blog  articles on the main site.

**Comment by oyealmond** [comment]
Agree we can follow up later on the possibility of integrating the Giveth blog to main website when the issue @ahmadabugosh is referring is done. 

We can keep here the work around repurposing Giveth content for social media. @surbhiaroraa is working on a resources link for the social team to use, anything else we should keep in mind @surbhiaroraa?

**Comment by surbhiaroraa** [comment]
Opened 2 separate issues to address repurposing of content. Hence closing this issue here
https://github.com/Giveth/giveth-planning/issues/1544
https://github.com/Giveth/giveth-planning/issues/1543
