### ISSUE TITLE
SEO Landing Page: How can Nonprofits measure the success of their fundraising efforts

### ISSUE THREAD

**Issue by surbhiaroraa** [Giveth/giveth-planning#1539]
Hi @SteffanThorn 
You wanted to try writing for SEO Landing Page. Want to take a shot at this? 
[Link to the document ](https://docs.google.com/document/d/1RQ3qp-c8rH9XjWcTFAtI7j74DO34b_GA-06JM9wO56c/edit)

cc: @oyealmond @divine-comedian  Just to keep you in the loop

**Comment by SteffanThorn** [comment]
Before I switch off for the day, I'm sharing where I'm at with this as I'm new to SEO and want to make sure I'm doing this right. 

I took the article Surbhi shared, and related the relevant topics to Giveth. Right now it's mainly bullet points with a few I've turned into paragraphs. 

I'm not sure if I'm also meant to be drawing keywords from somewhere else or just these 2 docs above. 

Thanks for the support in advance 
(tagging all the SEO-related people I know in Giveth)@surbhiaroraa @oyealmond @danelsuga @divine-comedian

**Comment by oyealmond** [comment]
Oh I think is a good approach! 
I will encourage @danelsuga, could you help us with some edition work to turn the bullets into a landing page?. 

Let me know your thoughts!

**Comment by SteffanThorn** [comment]
How do I get access to the landing page editor? 

Would help me make more complete drafts.

**Comment by surbhiaroraa** [comment]
> Before I switch off for the day, I'm sharing where I'm at with this as I'm new to SEO and want to make sure I'm doing this right.
> 
> I took the article Surbhi shared, and related the relevant topics to Giveth. Right now it's mainly bullet points with a few I've turned into paragraphs.
> 
> I'm not sure if I'm also meant to be drawing keywords from somewhere else or just these 2 docs above.
> 
> https://docs.google.com/document/d/1Rmxzqoych92o9j99F9yNaFbctm84LVJy7FXESHBuJ68/edit?usp=sharing
> 
> Thanks for the support in advance (tagging all the SEO-related people I know in Giveth)@surbhiaroraa @oyealmond @danelsuga @divine-comedian

@SteffanThorn 
@ahmadabugosh  is the right person to address this question. Ahmad for the landing page beside the main title keyword, what all keywords should be focused on? Will you provide that list or how do you think we should approach that? Should we be searching for keywords based on the topic?

**Comment by surbhiaroraa** [comment]
> How do I get access to the landing page editor?
> 
> Would help me make more complete drafts.

What do you mean by this? Are you asking who can help with editing your writeup? If that's the question, Almond tagged Suga above and Suga is kickass at this.

**Comment by danelsuga** [comment]
I did some editing. Nice go, @SteffanThorn !

**Comment by ahmadabugosh** [comment]
@SteffanThorn FYI, for SEO [this sheet](https://docs.google.com/spreadsheets/d/10e9ltdCl16rXgZ82gxAEZ-ROlhQiSnnIItUKfSaGUgc/edit#gid=325379001) has a list of the keywords we're targeting. The "Top 50 Keywords" tab has the ones we want to target and then the "Q4 2023 Keywords" has the ones we want to target this quarter.

**Comment by surbhiaroraa** [comment]
Hi @SteffanThorn 
I hope your questions are addressed on this one. Let me know if you have any further questions.

**Comment by SteffanThorn** [comment]
Love me or hate me. I've redone the whole thing and have aligned it more with how @surbhiaroraa's original draft looked. 
Including the intro and outro she wrote, and the first lines of each KPI. 

I've also highlighted Giveth specific benefits (which we could add links to other articles for). 
And comments to point where I'm either asking for specific or reflecting on our current status for the KPI. 

I took your main reoccuring comment into account @danelsuga and tried to use Giveth and Donors, instead of "you".

**Comment by surbhiaroraa** [comment]
Thank you for your efforts @SteffanThorn 
This looks great. I have left 2 comments. Please check that. 

@danelsuga @ahmadabugosh Can you please review [this](https://docs.google.com/document/d/1Rmxzqoych92o9j99F9yNaFbctm84LVJy7FXESHBuJ68/edit?usp=sharing) and tell if any changes are needed.

**Comment by ahmadabugosh** [comment]
Hey @surbhiaroraa , 

To be honest, I think we should change the direction of the article. It seems the focus now is that Giveth helps you with KPI's and it makes it seem like Giveth is an analytics tool, when in reality, we don't provide most of the metrics that are listed there (like donor retention rate, website visits, conversion rate, NPS), so I feel it's a bit misleading and doesn't really highlight the value we provice. 

Instead, why not have it be more about how Giveth can help Nonprofits raise funding (like the title originally was), which I think we can add more value on?

For example, for that we could mention:

- How Giveth lets you raise crypto, which for non-profits is a new discovery tool for fundraising and opens you up to global audiences and donations from people that would not have donated otherwise. You could also mention the amount of money in the crypto space (maybe mention stats on public goods funding on Gitcoin etc. so show that people are generous in the space). You could also mention how sometimes organizations support projects as well like Bankless and 1inch during the earthquakes.
 
- How Giveth has a strong community that promotes projects to our core group of loyal fans (you could talk about meet the makers for example, and our weekly calls, newsletters and social media where we highlight projects). 

- You could mention how the Giveth opens the door to more funding through the mechanisms on our platform, like QF rounds, and incentives like our GIVbacks program and referral program.

**Comment by surbhiaroraa** [comment]
Got it. Thanks @ahmadabugosh 

Actually the intention of the article isnt to position Giveth at all through this. The intention is to write some resources (which also target SEO) to educate Nonprofits which will help us establish Giveth as a thought leader.

However in the current article some elements are wrong for sure. Let me work on that. And the suggestions you provided above are very solid - I think its better we write another full fledged article on that.

**Comment by surbhiaroraa** [comment]
@SteffanThorn 
Please correct the article. Check Ahmad's note above and the comments in the document for reference.

**Comment by SteffanThorn** [comment]
From all these comments it seems there's 2 things being asked here. 

1) The original article given by @surbhiaroraa was general KPIs -- and that was somehow unacceptable as it wasn't about Giveth, but now we should include an article of the KPIs for general purposes without Giveth. So in other words, edit the first article Surbhi provided and don't worry about including Giveth. 

2) A new article just focused on using Giveth's benefits for nonprofits, ignoring that KPI terms.

**Comment by SteffanThorn** [comment]
Creating a new issue for 2. #1555

**Comment by oyealmond** [comment]
Hey @surbhiaroraa! We discussed on the last comms call all the SEOefforts should be aligned with Giveth voice, as they will be posted either on our website or blog. Non of this SEO efforts should be generic, they should include the SEO keywords and be framed with Giveth's narrative. 

I like the new approach @SteffanThorn gave to this text in https://github.com/Giveth/giveth-planning/issues/1555 . 

We should dismiss this landing page?

**Comment by danelsuga** [comment]
I think it's not a good idea to not heed Surbhi's expertise. I think it is totally worthwhile to have SEO landing pages that demonstrate Giveth as a leader in the field as she suggested. And as an honest, open organization that is providing level, meaningful research and isn't simply shilling something no one understands.

**Comment by oyealmond** [comment]
Didn't understood your comment @danelsuga . As I understood, the landing page of this issue, transformed into this other issue https://github.com/Giveth/giveth-planning/issues/1555? So we're not publishing [the landing page of this original issue](https://docs.google.com/document/d/1Rmxzqoych92o9j99F9yNaFbctm84LVJy7FXESHBuJ68/edit?usp=sharing)? That's my question

**Comment by danelsuga** [comment]
I was just saying I support Surbhi's feedback! I don't disagree with her approach to change the narrative and create the "generic" pages in order to develop a different angle for Giveth. I look forward to what she says. That's all! :D

**Comment by oyealmond** [comment]
oh I see @danelsuga! Now I understand. thanks for clarifying. 
On the last comms call we discuss the next steps of the landing pages w @ahmadabugosh - including align landing pages w Giveth's voice . You can check all the next steps [here](maintaine ) @danelsuga

**Comment by surbhiaroraa** [comment]
@oyealmond Let me know once you have finalised this, I will look at the design aspect and go ahead with publishing.

**Comment by oyealmond** [comment]
Hey @surbhiaroraa, as I understood going through the comments above, this issue content got discarded and was replaced with the new content of this issue https://github.com/Giveth/giveth-planning/issues/1555 . Please confirm so we can move this issue to the Icebox.

**Comment by surbhiaroraa** [comment]
Yes @oyealmond 
Right no this is discarded but we might use these as one of the many educational resources for projects to up their game of fundraising. But for now sure, you can discard this.
