### ISSUE TITLE
Write article: Get double matching with Panvala on xDAI and save on gas fees

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#155]
You can get double matching with Panvala on xDAI and save on gas fees. 
ZK Sync works also but xDAI has more reasons to go here. 

Mitch interested in writing this. Get Naran from Panvala to help us write this piece.  
Addressing a current issue so this is good to publish sooner than later.

**Comment by divine-comedian** [comment]
@ForestSoleil just to clarify we are talking about making donations to Giveth with PAN on xDai? Or making donations to a project on Giveth.io?

**Comment by laurenluz** [comment]
@divine-comedian @ForestSoleil can we close this? or is this still going to happen?

**Comment by WhyldWanderer** [comment]
Panvala no longer does double matching for donations in PAN on xDAI 
However, we can write an article or some sort of documentation explaining to projects, that if they receive donations in PAN they will get matched by Panvala.

**Comment by laurenluz** [comment]
@WhyldWanderer is there actually a lot of content that would go into explaining it? or should we just draft a tweet thread?

Would love if you made a nice, exciting, education $PAN-themed tweet thread ;)

https://docs.google.com/spreadsheets/d/1Es1ZhOzsRnZW3IBNPEwQqQhQFYty6FJY0AtU08I06tk/edit#gid=450032996

**Comment by divine-comedian** [comment]
I think this is a great topic that can be compressed into some occasional tweets!

**Comment by ForestSoleil** [comment]
Agreed - @WhyldWanderer when you have the availability, can you please see Lauren's comment above and draft a tweet thread? Then Lauren can schedule and we will close this issue.

**Comment by laurenluz** [comment]
So far regarding panvala, we tweeted:

```
Amplify your Giving Power with @PanvalaHQ!

When you stake $PAN on a project (like Giveth!) they receive $PAN distributed through @PanvalaHQ's matching funds initiative. 

Start Staking: https://cutt.ly/AbHGIr5
Learn more: https://panvala.com/

#blockchain4good
```

Ashley if you draft something you can drop it in here: https://docs.google.com/spreadsheets/d/1Es1ZhOzsRnZW3IBNPEwQqQhQFYty6FJY0AtU08I06tk/edit#gid=450032996

**Comment by WhyldWanderer** [comment]
In my opinion, the best way to inform project owners about PAN matching is through email when they receive their first donation in PAN. Im working to create something in autopilot that will allow this journey once we get the current bugs worked out after migration to next.

I think that Laurens tweet was perfect for a twitter post about PAN.

In order for a project to get PAN matching, they will need to join panvala as a community and stake pan for their community. Knowing this, it is a bit of a process and seems like a subject that needs to be explained more thoroughly than through a twitter thread.

Im going to close this issue since we have already tweeted about it. If I come up with any other ideas around Panvala and matching for tweets/threads, I will add them to the spreadsheet you posted above.
