### ISSUE TITLE
Presentation update to send to projects

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1580]
Upgrade the presentation:

- Update the presentation
- Prep slide templates for projects
- Each project has 3 slides

Working with this version: https://docs.google.com/presentation/d/1-8fvfRHRDAsEsdMlXgkH3YSp1PLxvvBEUPEpd85VZh4/edit?usp=sharing

@surbhiaroraa please drop the new link here when done

**Comment by surbhiaroraa** [comment]
I dont have edit right to the presentation. Its okay - you can just add the pointers from below:

**Introduction (3 minutes)**

- Briefly introduce your project and the team.
- Clearly state the project’s mission and vision.
- Clearly define the problem that the project is addressing.
- Provide data and context about the problem's severity and impact.

Example:
Hello everyone, we are (Project Name), a dedicated group aiming to (Briefly Explain Mission). Our vision is to (Explain Vision).....In our community, (Explain Problem with Data and Context).

**Proposed Solution (2-3 minutes)**

- Explain how your project aims to solve/address this problem 
- Highlight the uniqueness and effectiveness of the solution (if any)

Example:
Our project addresses this issue by (Explain Solution and its Unique Aspects).

**Impact (1-2 minutes)**

- Showcase the project’s impact.
- Provide examples, stories, or data on how the project is making or will make a difference.

Example:
Since our inception, we have  (Provide Data or Stories about Project Impact).

**Funding Goal (1-2 minutes)**

- Clearly outline the funding goal.
- Explain how the funds will be used.
- Highlight any past financial successes or how previous funds have been used.

Example:
We are seeking (State Funding Goal) which will be used for (Explain Fund Allocation).

**Call to Action (1 minute)**

- Invite the community to get involved.
- Provide clear instructions on how they can support, donate, or participate in the project.

**Comment by NikolaCreatrix** [comment]
Thank you Surbi, I prepared the slides. The updated version is here:

https://docs.google.com/presentation/d/1-8fvfRHRDAsEsdMlXgkH3YSp1PLxvvBEUPEpd85VZh4/edit#slide=id.g27be0e5bdf0_0_1
