### ISSUE TITLE
Create Impact Report with the objective of building brand awareness, trust and credibility

### ISSUE THREAD

**Issue by surbhiaroraa** [Giveth/giveth-planning#1599]
Providing some context here: After a lot of discussions while creating dApp WG proposal we decided to start putting out our impact metrics. 

There are multiple options of approaching this
- Put out impact metrics every 2 weeks (at the end of every GIVbacks round) - This gives us an opportunity to do frequent marketing around this, will help us stay on the top of minds of donor and project community due to the higher frequency. 
- Put this out every quarter - we sure will have better numbers as the numbers will be cumulative of 3 months 
- Put it annually - this can be a very thorough edition (for eg. https://thegivingblock.com/annual-report/)

Had a discussion with @ahmadabugosh also about this and we are of the opinion that its better to put it out every 2 weeks and then also do an annual edition as in a year we will have a lot of content to do a thorough edition. 

Basis that I quickly made a rough draft on canva to help you all understand what I mean - 
<img width="200" alt="Screenshot 2023-10-09 at 5 33 49 PM" src="https://github.com/Giveth/giveth-planning/assets/140404865/a13e0122-418a-47a9-9d2e-c88fd1609081">

What do you guys think? @oyealmond @divine-comedian @ahmadabugosh

**Comment by divine-comedian** [comment]
I think these stats are good starts but don't necessarily showcase the "impact" we created. If you want to weave in storytelling along with numbers it might be more effective to find out what impact we actually made. 

I would suggest along with our numbers such as dollar value of donations and # of GIV distributed through GIVbacks we should include 2-3 anecdotes of how did projects spend their funds to create impact. We don't need to know for all projects but only perhaps the most successful or the most active projects. Since it requires a bit more work we can focus on doing this as a quarterly initiative. 

One of the most common questions I am asked around Giveth is "How do I know how my donations are being spent?" - While we can't create full accountability for every donation or every project we can provide some proof that Giveth as a donation platform facilitates impact creation.

This ties in with a lot of work we already do in other areas, such as MTM, Mandatory Project Updates etc.. . Building a relationship between donors and projects. 

For me as a long-time donor I find these traditional NGO publications as a good example. (Yes you've caught me talking about trad NGOs now :P )

https://dispatches.doctorswithoutborders.ca/
https://www.care.org/news-and-stories/resources/care-usa-2022-annual-report/

**Comment by oyealmond** [comment]
Hey @surbhiaroraa @divine-comedian thank you so much for the inputs. 
So as discuss today for the different applications of the Giveth Impact Report, we will do: 
- infographic for each GIVbacks Round highlighting the amount raised & the amount of $ distributed in GIVbacks. 
- Gather project updates and make a complete monthly report (including the 2 infographics) that will be added to the newsletter. 

For the next steps, 

1. @surbhiaroraa check the [forum post](https://forum.giveth.io/t/round-46-givbacks-and-nice-distribution/1204) where @WhyldWanderer gathers all the info, and please Surbhi plan how the infographic will look like
2. @surbhiaroraa please coordinate with @WhyldWanderer on the cool updates we have going on and select 1 or 2 for the complete report. 
3. @surbhiaroraa Plan how the monthly report will loo like. (structure) 

Let me know if there's something missing, or that we should contemplate. 
Thanks!

**Comment by surbhiaroraa** [comment]
Thanks @oyealmond 
Working on this.

**Comment by WhyldWanderer** [comment]
Adding a link to GIVbacks Analytics data spreadsheet:
https://docs.google.com/spreadsheets/d/1f6VHgI28aqg8HNZ8qfTX2C5l1bhmJSw_tsQP_m8JCBI/edit?usp=sharing

Let me know if there is any other data that I could be recording from each round that would be useful for this initiative!

**Comment by surbhiaroraa** [comment]
@WhyldWanderer @ahmadabugosh 
Do we have following data points - 
1. countries from which donors below? This will help us show a visualisation of different countries represented.

2. Do we have data around countries of projects (could be registered address or whatever) - if we can show this in a visual format how many countries we are impacting through our donations?

**Comment by surbhiaroraa** [comment]
The graphic is there when I am checking here in my github - I dont know the glitch. 

Let me know if you can see here 
![GIVbacks](https://github.com/Giveth/giveth-planning/assets/140404865/2a8617ec-c3d8-4184-8464-3411fe707d73)

**Comment by oyealmond** [comment]
@surbhiaroraa Feedback from today's call: 

- Separate big numbers with commas 
- Change the footer text to: BUILDING THE FUTURE OF GIVING 
- Can we try to make a horizontal version of this material, or, maybe it will be better to separate this graphic in 2, one with the round stats, and a different one with the highlighted projects so we can create more content out of this effort. Instead of creating one post with all the info, separate and create 2 post one w the stats , and the second post w/ the round highlighted projects.

**Comment by surbhiaroraa** [comment]
@ahmadabugosh Can you share the stats of the latest GIVbacks distribution round (reference: Infographic above)? 
I will update the infographic and lets start pushing it out.

**Comment by ahmadabugosh** [comment]
hey @surbhiaroraa, @WhyldWanderer would be the best person to coordinate on this
