### ISSUE TITLE
Project verification and project creation requirements for Polygon form. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1612]
Prepare for Polygon a doc explaining what do we need for project verification and create a project on Giveth.
 
Give them the information of what fields we need them to add [in this Polygon form](https://spotlight.polygon.technology/village-form)

 @laurenluz & @missgene

**Comment by laurenluz** [comment]
Hey @missgene !!

Basically Polygon is going to be onboarding projects from their side via a form, and we want to make sure that we get them to collect all the fields/information we need in order to then take their data... make it into a .csv and input it into our backend to create projects for them all.

[This is the form Polygon has setup already](https://spotlight.polygon.technology/village-form).

For this issue, please create a google doc that lists out all the fields we are asking for in our our [create a project form](https://giveth.io/create) & project verification form (for this one, you need to "create a project" & then "apply for verification" to go through it). - Maybe you can make them in order and use titles so we know which is which.

Then have a look at the Polygon form and compare what data they are collecting so far... and what other data we will need.

Please highlight the fields on our forms that we'll need to add to their forms.

Also - for context - @CarlosQ96 will be adding this data from a .csv file to our backend, so if you have any questions about what exactly we need or if things are kind of weird fields for a form, you can mention them/ask them in our group DM on discord :) I just added you

**Comment by laurenluz** [comment]
This was created, but in the end they decided they will not send us the .csv.

still, might be useful in the future:

https://docs.google.com/document/d/1u_pKRDkdtbbEf0hU8icxCKLPn1OCdTLhydnsWRjm4n8/edit
