### ISSUE TITLE
Announcement tweet thread GG19

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1634]
Prepare announcement tweet thread, from project update.

@oyealmond @laurenluz

**Comment by laurenluz** [comment]
@SteffanThorn - can you make our [project description](https://docs.google.com/document/d/1TF5NsHh9agaPfn0UGc_ePULHOBYOhvAAjMhotNcBF5M/edit) into a shill thread for gitcoin grants?

I think you did this last time and did a really good job of summarizing milestones.

Keep in mind... this time we applied for web3 community & education (instead of open sources software)... so our content should basically have the focus of like "why is the creating an impact/bringing nonprofits into web3 & teaching them how to use it"

**Comment by SteffanThorn** [comment]
Hey yea I’ll take this on.

will have it done tomorrow

**Comment by SteffanThorn** [comment]
3 threads. 

Each one feeding into the other. 

https://docs.google.com/document/d/1DYk90eP4JI58NMQOD0hUScRhw-7PhYZNM8i_Dfj2ABI/edit?usp=sharing

**Comment by laurenluz** [comment]
great stuff Stee! I left some comment & suggestions (and made a few small edits directly)

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1724759659662262322
