### ISSUE TITLE
Discuss Magenta's Role & Responsibilities

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#165]
Magenta has suggested that perhaps there are other things she could support us with? She is curious about everyone's new roles and where she is most helpful. 
Could be supportive to have her help Ashley in onboarding to her new community manager role, with Magenta's connections and strategy. 
Forest & magenta to have a 1:1 about communications strategy.
Dani, any other ideas?

**Comment by Danibelle** [comment]
Here is the current contract to review what's being done as a partner org, it's paid already: https://docs.google.com/document/d/1o6azVDflF8nyCA3uAjOAE4oGLGIgPGBzrCtmiiLYANY/edit?usp=sharing

Happy to explore what Magenta is into as an individual contributor to Giveth aside from that.

**Comment by laurenluz** [comment]
@Danibelle @magentaceiba what happened here? would love to be updated about if/how magenta will be continuing to support our team!

**Comment by magentaceiba** [comment]
Hi I've just been slow to reorient due to a project that took more of my bandwidth than anticipated, and then taking a couple weeks to take care of myself. Will get back to you on this by next week and schedule a time with Ashley. I believe where we landed with the discussion with Dani and Forest was for the remaining funds that were allocated to the outreach support with Giveth's organizational membership with Bloom, to go to boosting or writing a quarterly blog post about projects on Giveth, similar to the Change Maker roundups, helping them reach more people. Remaining to do right now on that is for me to calculate how much of that budget remains.

**Comment by laurenluz** [comment]
Thanks for the update @magentaceiba - sounds really good, makes perfect sense. I'm really grateful that we got to connect here - you are a powerhouse of great ideas and experience and we'll miss you in the comms calls ;)

**Comment by ForestSoleil** [comment]
Yes, Magenta that is where we left off and what we decided. Thank you, love!!
