### ISSUE TITLE
WGs social media content request

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1702]
Hello @WhyldWanderer @laurenluz @divine-comedian @SnakeGH 

Reaching out to ask you if you have any content requests for social media. Our socials are all about the Polygon Round until the 24th, but we can start preparing the materials you need. 

Also asking if you have any recurrent topics we should always post about frequenly. 

Thanks!

**Comment by SnakeGH** [comment]
For fundraising, I would probably do another "still riding high" from all the OP awarded to Giveth. 

Also Octant EPOCH is quickly approaching, as well as another Optimism round. 

We are getting close on a partnership with Endaoment, so that will be some material coming up as well as I think @divine-comedian & @laurenluz had a good follow up call with Donorship about a future partnership, which would be more material in the near future 

Don't want to steal Lauren's thunder but there is a couple other QF rounds coming up, that a "teaser" post would be exciting 

And not entirely sure where SuperFluid & Solana integrations stand but some big topics for future material...

**Comment by divine-comedian** [comment]
Thanks! Yeah we're looking at a launch of Solana VERY SOON, devs say next week but you never know with these things. 

I did touch on #1696 - that is ready to go. 

Donorship and Endaoment need some work still but good points jake da snake

**Comment by laurenluz** [comment]
I think we should also prep a series of tweets around the metapool round - inviting APAC projects to get on giveth, get verified & apply to the round

Other things mentioned:
- Octant Epoch 2 we have an issue for already :)
- Donorship - too early!
- Solana - important :D

and it's definitely not a bad idea to give another gratitude post to Optimism, but I hope we can do it in a way like... we have something to say. maybe along the lines of completed milestores, or goals we want to achieve on Optimism coming up.

**Comment by oyealmond** [comment]
Great! thanks for your feedback you all. Octant is already going on, I'll start with the Meta Pool content inviting APAC projects, and I'll keep an eye on Solana. I created a separated issue for the second OP tweet https://github.com/Giveth/giveth-planning/issues/1707
