### ISSUE TITLE
Weekly/Bi-weekly medium post for round-up of submissions

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#172]

**Comment by divine-comedian** [comment]
first submission roundup draft is ready for review ! 

https://docs.google.com/document/d/19GQh-sS-AmyU633uuKy__qtYtLSQkHfOXc2Hh4Pi-T8/edit?usp=sharing

@laurenluz  @WhyldWanderer  @ForestSoleil

**Comment by laurenluz** [comment]
Reviewed and added suggestions to the doc @divine-comedian - great work!

**Comment by divine-comedian** [comment]
round up #2 ready for QA ! 
https://docs.google.com/document/d/1wivlZWl-5GfDoFhRoB1i4Tbd100D99nDY28exwpcB4g/edit?usp=sharing
@laurenluz  @ForestSoleil  @WhyldWanderer

**Comment by laurenluz** [comment]
@divine-comedian ... I'm doing QA on this and it's really apparent that you copy/pasted a lot of it from their blurbs on Giveth.io... I think our weekly post should include a summary from the voice of Giveth. it's really difficult to edit this piece because I'm finding that I'm just having to rewrite it entirely to make it consistent. I also don't think it is ethical to use a project's exact words and publish it on our blog, unless we are putting it in as a quote.

would be appreciated if you could update and then ping me, then I'd be happy to review.

If you're too busy I don't mind to take over the rewrite. I don't mean to be harsh... I think you know what I'm talking about though....

**Comment by divine-comedian** [comment]
Yes I took most of their text and adjusted it into the round-up blurb.. My feelings towards this is that this is the way the project owner's chose to describe their projects. I don't want to change too much of the author's actual words but rather highlight them. If there's a particular way you think this should be written I can respect that but I don't totally agree with your point of view.  

I'm open to re-writing but I'd like to hear other thoughts on this conflict. @Danibelle  @GriffGreen

**Comment by Danibelle** [comment]
I think to @laurenluz 's point, if we are quoting then let's just put it in quotes and/or say "from their project description: " ..
Agree with you @divine-comedian that we don't have to totally rewrite in our voice, it's okay to round up their info then present it..

And, I'll take a look at the doc now for any further comment/suggestions.

**Comment by laurenluz** [comment]
I just went through again... Looks a lot better. I love the photos Dani added. I also agree that we should put quotes around whatever parts are directly quoted from the project's descriptions, but I'll leave that to you @divine-comedian since you know which parts that would be specifically

Otherwise, just made a few more small edits - looking good.

**Comment by ForestSoleil** [comment]
Round-up #2 published May 14th on Medium 
https://divine-comedian.medium.com/change-maker-submissions-round-up-2-4e9b3fe4e3f0?source=collection_home---4------2-----------------------
