### ISSUE TITLE
Change Maker Campaign: reach out to individuals, projects, groups - get more people involved!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#178]
Share the campaign to more people and get people adding projects!
Add "the personal touch"...This issue is to keep track of who we are reaching out to (whether projects or individuals).
Please add a checkbox item to the list and add your name (by "editing this issue text") *before* reaching out to someone, and then check the box when it is done.

- [x] Costa Rica Telegram groups (Forest)
- [x] Costa Rica WhatsApp groups (Ashley)
- [x] Mateo/Adriene Casa Asension @ForestSoleil 
- [x] David, The Havening Project (Forest)
- [x] Ara/Devin w Free the Food @WhyldWanderer 
- [x] Email to projects that are already on giveth.io (using autopilot) @divine-comedian 
- [x] Outreach to press/media sites for crypto and non-profit world @magentaceiba

**Comment by WhyldWanderer** [comment]
Dangit i meant to talk to Ara today at the meeting and I missed him. They will receive the email about it when we blast it because theyve already created a project and then I will follow up with them a day or two after. 

I have gone through some of the whatsapp costa rica groups searching for keywords that might lead me to projects that would be good on giveth. I made a list of about 5 and plan to reach out to them personally. I have not blasted anything to the actual groups and will get in touch with forest on the best way for us to approach that.

**Comment by divine-comedian** [comment]
email blast has been sent via autopilo!

**Comment by ForestSoleil** [comment]
Hey @Divine-comedia @Mitch can you please copy paste the email blast that went out via autopilot here? So that we can take that copy and adjust it perhaps for other outreach?

**Comment by divine-comedian** [comment]
The email can be found here - https://app.ap3prod.com/giveth/assets/607de1905e166c461774e245

**Comment by divine-comedian** [comment]
Any updates on the outstanding tasks? RE: 

CR Tribe chat telegram (Ashley or Forest) @ForestSoleil  @WhyldWanderer 

Outreach to press/media sites for crypto and non-profit world @magentaceiba

**Comment by WhyldWanderer** [comment]
@ForestSoleil Ill hit the WhatsApp groups! 
And check to see if i have any telegram groups that you dont..

I plan to hit outreach hard this week and I can update here

**Comment by divine-comedian** [comment]
Moving into the longer term phase I believe we'll slow down on the active shilling aspect of the change-maker campaign. closing this issue as we move forward!
