### ISSUE TITLE
change-makers, final round-up! 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#302]
Here's the draft for the final change-makers post, ready for QA, let me know how QA works using the medium draft link... 

https://medium.com/@divine-comedian/change-makers-final-round-up-cac16070c15f

@ForestSoleil  @laurenluz  @WhyldWanderer

**Comment by laurenluz** [comment]
@divine-comedian can you copy/paste into a google doc? it is not easy to make edits to your doc in the medium... unless you submitted it to giveth and then editors could touch it...  but also there is no good way to track edits.

the copy/paste to google doc and the copy/paste back preserves most of the formatting, I've done that before.

**Comment by ForestSoleil** [comment]
Can't easily make edits. Need to post them here.

**PVC**
"tree-planting service" should probably be plural --> services
"At this moment one of their main goals are to extend" --> IS to extend

**Bridging Digital Communities**
"Is run by a Digital Wizard by the name of Kay, he creates online bridges that allow communities to stay connected." --> Is run by a Digital Wizard by the name of Kay. He creates online bridges that allow communities to stay connected.

**Spread the Love Commission**
"asking a man experience homelessness" --> asking a man experiencing homelessness
"between 600,000 to 1.5 million experience" --> between # PEOPLE experience

**Initial paragraph**
"Wow! It’s been a while since we did another round-up of change-making projects using Giveth.io. A lot of action has been happening on Giveth, we’ve got some exciting news coming soon! This will be the final showcase of projects under the change-makers campaign as we gear up for the next phase of Giveth."
Hmm I get the sense from the wording of this that we were busy with other things and didn't post for a long time. Maybe we can close it out more softly? --> As Giveth winds down our Calling All Change-Makers Campaign (link to original post), we are ecstatic to highlight these final four projects doing good in the world. Didn't submit in time? Not to worry. We will continue to promote the incredible work that our Makers are pioneering. Drop us a line blah blah blah. 
A lot of action has been happening on Giveth, and we've got some exciting news coming soon! Stay connected with us here on Meidum and on our Discord channel (link).

**Comment by divine-comedian** [comment]
My bad guys, worth a shot - I''m honestly surprised that Medium wouldn't have a better system for copy editing. 

@ForestSoleil  your edits have been incorporated! 

let's try this again. 
https://docs.google.com/document/d/1wR0kJPjub-RDYSTyneCGfup1fd1ur4Ih564CCTj0vwA/edit

**Comment by laurenluz** [comment]
QA'd!

**Comment by laurenluz** [comment]
posted! will share and shill tomorrow with the tweet link for RTs
