### ISSUE TITLE
GIVbacks

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#308]

**Comment by WhyldWanderer** [comment]
HackMD Doc (WIP): https://hackmd.io/35eK-VtFT4emILjDqS0UmA

**Comment by laurenluz** [comment]
need to explain that GIVbacks are in the token distro and so whenever the user claims anywhere they also get the GIVbacks portion. (and the GIVstream portion)

**Comment by laurenluz** [comment]
https://hackmd.io/9WSKSyz7Sa-tKQXYV7_Y7A?both

**Comment by laurenluz** [comment]
@WhyldWanderer @divine-comedian @ForestSoleil 

This is ready for review. Pictures will need to be updated later, ofc, but I think it's ok:

https://docs.google.com/document/d/1ghXU9TZg6kR4Zx9lX_GO1U4qGY0vHa3nUo5tnkKTjR8/edit?usp=sharing

**Comment by divine-comedian** [comment]
left some comments, looks pretty good! :+1:

**Comment by WhyldWanderer** [comment]
Reviewed! I left some suggestions in the doc. Great job Lauren!
The only thing I saw missing in this doc is links

**Comment by laurenluz** [comment]
Thanks for the reviews team! This one is now officially done... only missing:
- links
- updated photos

https://docs.google.com/document/d/1ghXU9TZg6kR4Zx9lX_GO1U4qGY0vHa3nUo5tnkKTjR8/edit
https://hackmd.io/9WSKSyz7Sa-tKQXYV7_Y7A?both

**Comment by laurenluz** [comment]
@divine-comedian This is ok to go up as well. I will need to update the links and photos later.

**Comment by divine-comedian** [comment]
LIVE 
https://docs.giveth.io/giveconomy/givbacks

**Comment by WhyldWanderer** [comment]
I am realizing that we need to be more clear about Verified projects donating to other verified projects. 
Since all verified project addresses are added to the purple list, these projects will not be able to receive GIVbacks if they donate using their project address. 

We should correct this paragraph:
![image](https://user-images.githubusercontent.com/74267818/146230015-d60f289d-daf8-41c8-b419-14a3bdeeab35.png)

The last sentence should say:
"Note that Projects themselves do not receive GIV for donations to their own project or any other verified project"

**Comment by laurenluz** [comment]
should allude to purple list (without being explicity) - if you're using the wallet address attached to your verified project or campaign

only campaigns get GIVbacks... nuances from TRACE

@WhyldWanderer to go in and update with the extra details directly in the live doc. and add it into the GIVbacks blog post issue

**Comment by WhyldWanderer** [comment]
made updates to the docs... still missing live giveconomy links though
