### ISSUE TITLE
Update TRACE Documentation in docs.giveth.io

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#313]
A few places that I see need updating:

**Intro to TRACE page:** 

Announce that we are no longer in beta:
![image](https://user-images.githubusercontent.com/74267818/125721432-d95162f0-7266-4f07-a43e-e1db7044f42d.png)

Maybe link to Medium whats dappened posts? or the DEV section of Notion?
![image](https://user-images.githubusercontent.com/74267818/125721525-decdc4e2-991f-4f7f-881d-25054c0d9d7d.png)

**Giveth Entities and Roles Page:**

Mention verified projects? Add something about how the TRACE onboarding will work? How the two platforms are integrated until now...
![image](https://user-images.githubusercontent.com/74267818/125721700-fb367822-b55e-4db7-aac5-5857a3ae90d0.png)

Feature Payments Expenses and bounties.. remove Milestone
![image](https://user-images.githubusercontent.com/74267818/125722027-215ecb22-dd13-4a82-8974-d1114484cb65.png)

Remove Milestone...
![image](https://user-images.githubusercontent.com/74267818/125723363-a75837b3-fe11-49d2-9e48-5ea57a5fbeaf.png)

Image Fix:
![image](https://user-images.githubusercontent.com/74267818/125724538-65ca96c2-d9a0-45aa-80dc-1c86135d9954.png)

Broken Link?
![image](https://user-images.githubusercontent.com/74267818/125723471-fa003c65-6b00-4125-bdad-c330ffd9d6df.png)

I also see that on the "Leaving Traces" page we still reference Milestones but I think that is okay to leave it since eventually we will add them back in.

**Comment by divine-comedian** [comment]
weird that just that one image didn't update, I uploaded a new one yesterday evening...

broken image link is fixed!

Milestones - I'd love to just leave it in since it does exist on TRACE and hopefully we'll be unhiding that feature soon on the UI

I removed the internal link text and just linked to our medium, the whats dappened posts and the dev section of notion are both out of date...

RE: Verified project text and campaign managers 

A Campaign Manager is a registered user who has created a Campaign, and therefore acquires sole ownership of the new Campaign. Campaign Managers can also be Giveth.io users who have chosen to make their project traceable and have passed the project verification process. The role of the Campaign manager is to create Traces through which they can fund the work of people and the cost of resources behind the project.
#### How to become a Campaign Manager
* A user can create a Campaign to become the Campaign Manager
* Verify their giveth.io project and request to become traceable, upgrading to a Campaign on TRACE and becoming the Campaign Manager of said Campaign 
#### Power of a Campaign Manager
* Edit their Campaign
* Send Campaign funds (via Delegation) to Traces within their Campaign
* Reject or accept proposed Traces to their Campaign
* Create or edit Traces in their own Campaign


---
Once we have some documentation on project verification we can add a link in somewhere for the process.
What do you think? @WhyldWanderer

**Comment by WhyldWanderer** [comment]
It all looks great! 

The part that is slightly misleading about the Campaign Manager is that the only way to become a Campaign Manager is to create a project on Giveth.io and get it verified. Correct me if Im wrong, but we arent allowing users to create campaigns.

**Comment by divine-comedian** [comment]
Okay, I see what you mean, so we're not allowing whitelisted users to make new campaigns as before. so we'll just remove the 1st bullet and say 

**How to become a Campaign Manager**
- Verify their giveth.io project and request to become traceable, upgrading to a Campaign on TRACE and becoming the Campaign Manager of said Campaign

**Comment by WhyldWanderer** [comment]
Yes!! That sounds much better! Thanks so much Mitch.. you da best!

**Comment by divine-comedian** [comment]
okay changes are LIVE! 

![image](https://user-images.githubusercontent.com/67759413/125840630-14b2bfa1-a77b-4cc7-932e-338839b1958e.png)
