### ISSUE TITLE
Make a system for tags on medium articles

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#460]

**Comment by laurenluz** [comment]
@SymSL willing to take this on in 2 weeks

**Comment by SymSL** [comment]
Hey Lauren, I think these are great, agree on most and suggestions on some:
- For-good Projects
- GIVeconomy
- DAO
- Tech (_Would this not also be under Platform - what would be different here?)_
- Donating on Giveth
- Courses / 101s - would this be articles where people would learn? May be better to have a category for Learn or Educate (eg there is a Coinbase Learn)
- dApp (or maybe "Platform" is good/better) - _I agree, I think **Platform** is better because dApp can still be cryptic to some at this stage_
- Talks / Conferences / **Philosophy** - I really like Giveth Philosophy and feel alot can fit under this category.

If we agree on these then I'll need access to the Medium to change these for each article please

**Comment by ahmadabugosh** [comment]
Hey @laurenluz I wanted to push this up the queue. I think about this issue every time I visit our Medium 😅, if you add me to the Medium I can implement this

**Comment by laurenluz** [comment]
Hey @ahmadabugosh! Sure - send me your medium handle and I'll see if I can give you the power (maybe in a DM, because my github notifications are a mess RN)

**Comment by ahmadabugosh** [comment]
Hey @laurenluz @SymSL @danelsuga,

I updated the [Giveth medium](https://medium.com/giveth) navigation and articles to the following:

- GIVeconomy -> This filters all articles with the "GIVeconomy" tag 
- Giveth Platform -> This filters all articles with the "dapps" tag
- Learn with Giveth -> This filters all articles with the "Crypto Education" tag
- Giveth Philosophy -> This filters all articles with the "Blockchain for Good" tag
- Giveth Galaxy -> This filters all articles with the "Impact DAO" tag. 
- View All -> This just shows all the articles we have. 

I didn't include "For good projects" since I didn't see any articles that would be relevant. 

Let me know if you want to edit any of those or if it makes sense!

**Comment by laurenluz** [comment]
wooowwwwwwwww!!!!!!!!!!!!!!!!!! I love it.

**Comment by laurenluz** [comment]
did you change the tags on existing articles?

**Comment by ahmadabugosh** [comment]
@laurenluz Yes! We're allowed 5 tags per Medium article, so I changed one tag per article based on what category I thought fits best. 

The only ones I wasn't sure where to put were the Community Project Spotlight ones, like [this one.](https://medium.com/giveth/community-project-spotlight-4-382e3244afac). What do you recommend for those? We could make a menu item for "For-good Projects", but the menu display would cut off on desktop if I add another category (unless I remove "Giveth" from Giveth Philosophy, Learn with Giveth and Giveth Platform) 🤔

**Comment by laurenluz** [comment]
Yeah! I like the "For-Good Projects" header. I would remove Giveth from all those places for sure!! Philosophy, Learn & Platform is better, I think.

Also just looking at the GIVeconomy one, I think you missed an article or two. The angel vault one should be there for sure.

**Comment by ahmadabugosh** [comment]
Done! Just added it "For-Good Projects" ->  This filters all articles with the "Public Good" tag.

I just added the Angel vault one, and I think I got them all now but maybe you or @danelsuga could do a quick run through and see if you like how they're tagged in each category

**Comment by SymSL** [comment]
Thanks so much for picking this up @ahmadabugosh, and I'm sorry that I had let it drop in the first place, team :( Won't happen again. Great job on finishing it!

**Comment by ahmadabugosh** [comment]
@c0ric0ri I added this to Notion for future reference https://www.notion.so/giveth/Medium-Article-Tagging-b0e08e15a5cd4563ada331ad27dcf02d
