### ISSUE TITLE
Verified Project Spotlight tweet thread for Round 3

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#475]
@Brodyann7 can you make a tweet thread with your favourite projects newly verified for round 3?

**Comment by Brodyann7** [comment]
🌏  We have another roster of newly verified projects! 🤩

Remember, when you give to verified projects, you get GIV. It's a win-win! 🏆

🌟 Check out some of our newest shinning stars👇: 

🌿  PositivBlockchain curates an open database, a knowledge platform and actively growing a community exploring the potential of blockchain technologies for social and environmental impact.
 
https://giveth.io/project/positiveblockchain.io 
@PositiveBlock

🏠 Spread the Love takes the “helpless” out of America’s homeless crisis by bridging the divide between those experiencing homelessness and those who wish to help.
 
https://giveth.io/project/Spread-the-Love-Commission 
@spread_love_org

🆘  The FundLife relief and recovery fund is providing access to essential goods and clean drinking water to communities affected by the Super Typhoon Rai in the Philippines

 https://giveth.io/project/typhoon-rai-relief-and-recovery-fund 
@FundLifeInt

☀️ Elephant in the Room is a nonprofit decentralized think tank that creates, implements and analyzes strategic multimedia campaigns to move the needle on climate change. 
 
https://giveth.io/project/Climate-Solutions-Communications-and-Public-Outreach-0 
@BenWest 

❤️‍🩹 The Henzi Foundation aids in providing financial relief to families or caregivers of children to assist with the final expenses due to an unexpected loss. 
 
https://giveth.io/project/the-frankie-fund 
@JHenzi


@laurenluz feel free to add/ modify/suggest anything!

**Comment by laurenluz** [comment]
Hey @Brodyann7 - this is GREAT! I love these tweet threads, for real!! Even if you're working more on the case studies, I would love if you could make one every 2 weeks. Only if it works with your bandwidth, but I think they add a lot of value.

I only changed the first tweet and made some minor tweaks in the others. I wanted to more explicitly mention GIVbacks and provide info about the round.

I also added a last tweet linking to the givbacks post for more info! :)

https://twitter.com/Givethio/status/1486364927816343556
