### ISSUE TITLE
Video Minicourse - Givstream

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#496]

**Comment by ahmadabugosh** [comment]
To Do

- [ ] Create Script
 - [ ] QA/ Review Script
 - [ ] Record Video 
 - [ ]  Edit Video / add closed captions in English
 - [ ]  Upload to video hosting platform
 - [ ]  Promote video

**Comment by ahmadabugosh** [comment]
I recorded this video already (just editing it now) so assigning it to myself

**Comment by ahmadabugosh** [comment]
hey @laurenluz @WhyldWanderer the main points I wanted to cover in the GIVstream video are:

1. There are 3 ways to increase your GIVstream (donating to verified projects via GIVbacks, participating in GIVfarm and participating in GIVgarden)
2.  Some rewards will be given to you through liquid GIV but the majority would be streamed to you 
3. The GIVstream rewards continue until the end of 2026

**Comment by laurenluz** [comment]
This one is pretty nuanced, we worked a lot on the messaging so that it's not with the perspective of "things being witheld" but rather from the perspective of "things you get and keep getting".

Before you edit, can you share it with me to watch? Maybe it's good as-is, but maybe it's worthwhile rereording to hit points like:
- GIVdrop recipients already have a GIVstream
- GIVstream history table showing instances of GIVstream increasing
- Your GIVstream can only go up
- The GIVstream means that, as the economy grows, so does the governance power of the people who supported it
- GIVbacks, when distributed is added automatically to your stream
- GIVfarm rewards need to be "claimed" for them to show in your GIVstream
- it doesn't matter when you claim in the GIVfarm... the rewards liquid & flowrate will be the same if you claim earlier or later

I'm happy to record this one if it makes more sense to re-record.

**Comment by laurenluz** [comment]
Ok I recorded a version, sending to you on discord @ahmadabugosh lmk what you think!

**Comment by ahmadabugosh** [comment]
Hey @laurenluz , I edited and uploaded your video here. Let me know if you have any comments, or if you're ok with it feel free to close this issue: https://www.youtube.com/watch?v=2ZpYkTg3huc&ab_channel=Giveth

**Comment by ahmadabugosh** [comment]
Oh and also I forgot, I split the end part of it to a separate video on GIVstream claiming: https://www.youtube.com/watch?v=I0VkJ4iQsww&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=6&ab_channel=Giveth

**Comment by laurenluz** [comment]
Great! You're amazing Ahmad - thanks so much <3
