### ISSUE TITLE
Video Minicourse - Givgarden

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#497]

**Comment by ahmadabugosh** [comment]
To Do

- [ ] Create Script
 - [ ] QA/ Review Script
 - [ ] Record Video 
 - [ ]  Edit Video / add closed captions in English
 - [ ]  Upload to video hosting platform
 - [ ]  Promote video

**Comment by ahmadabugosh** [comment]
I recorded this video already (just editing it now) so assigning it to myself

**Comment by laurenluz** [comment]
@ahmadabugosh there are several inaccuracies, and some parts that actually just wrong in this video. I appreciate you taking it over from me because I've been taking so long on it, but we need to re-record it... and there should be a script for review in this case if it's someone who isn't actually aware of all the nuances.

For example, voting on abstain actually means that all other proposals will pass slower... 

also the percentages needed to pass... the reference point is not all give in circulation.. it's actually all wrapped GIV.

also, you don't need to use the GIVfarm to wrap tokens... you can wrap them directly in the garden. You also can use the GIVfarm to wrap them.

I only got through half the video, but this really shouldn't be published for the course as-is.

**Comment by laurenluz** [comment]
also missing everything to do with creating & challenging a proposal, deposits, what exactly is the covenant...

also it kind of misrepresents conviction voting... and this is very important to explain correctly.

**Comment by ahmadabugosh** [comment]
@laurenluz fair points, I removed the video! Let me know if you want me to rerecord to add those points, or if you'd prefer recording it yourself (it probably would be better if you record it, since I'm scared I'll miss something important)

**Comment by laurenluz** [comment]
@ahmadabugosh I made a new recording w camtasia and sent you the file on discord - lmk what you think! I can rerecord if it needs to be fixed.

**Comment by ahmadabugosh** [comment]
hey @laurenluz I edited your video here (I added a bar on the bottom to cover the timer you had onscreen and also cleaned up the audio), let me know if you have any comments (if not feel free to close the issue): https://www.youtube.com/watch?v=ARIhMR4rEis&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=7&ab_channel=Giveth

**Comment by laurenluz** [comment]
Nice! It looks good!

**Comment by laurenluz** [comment]
Thanks so much Ahmad!
