### ISSUE TITLE
Verified project tweet thread for Round 4

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#502]
Round 4 starts Feb 4, so it would be great to share this during the week of Feb 7-11

**Comment by Brodyann7** [comment]
ok cool, will do!

**Comment by Brodyann7** [comment]
🌏  We’ve got a roster of amazing verified projects raising funds to empower communities 💪 
 
Check out some of our newest shining stars! 💫 👇
 
👩‍💻 BrightID lets all sorts of applications make sure their users don't have multiple accounts so that everyone has a fair share and a better online experience.
 
https://giveth.io/project/brightid-proof-of-uniqueness 
@BrightIDProject 
 
🌱 Permaculture Action Network is continent-wide collective that mobilizes thousands of people to take direct action on regenerative projects with a diversity of groups and organizations.  
 
https://giveth.io/project/permaculture-action-network
@PermaAction 
 
📚 EspacoVoa is building an inclusive learning space that promotes human connections and motivation for learning in Carrancas, Brazil. 

https://giveth.io/project/espacovoa 



@laurenluz @WhyldWanderer seems like these were the only projects that were verified in round 4?

**Comment by ForestSoleil** [comment]
Yes I just did a check in the project verification channel and it seems these were the only 3 APPROVED from round 4.

**Comment by ForestSoleil** [comment]
Are you double checking that our tweets are always within the 280 character limit @Brodyann7 ?

**Comment by Brodyann7** [comment]
This is within that limit (it's a thread), Lauren usually tweaks it so I try to leave them more or less open.

**Comment by laurenluz** [comment]
Thanks so much @Brodyann7 !! It's great.

I tweeted it out this morning along with the announcement of the GIVbacks round 3 distribution. Tried it like that this time... I think next time I will keep them separate.

https://twitter.com/Givethio/status/1491411523796824066
