### ISSUE TITLE
Copy editing Giveth docs

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-planning#510]
I’m going through the literature to learn and will copyedit along the way! I will create PR’s with my findings.

One item I’m concerned with in general is the overuse of capitalization. It is not consistent throughout the literature and seems to be used rather randomly. I would like to correct this by applying standard grammar rules. I recognize the significance of not giving a damn about grammar rules, but at the same time they are useful particularly in terms of authorial intention and in readerly flow of the content.
Thoughts welcome!

**Comment by danelsuga** [comment]
I don’t seem to have any Github superpowers for assigning folks, etc.
Can some one help please? Thank you!
@WhyldWanderer @laurenluz @divine-comedian @ForestSoleil 
@Giveth/communication

**Comment by danelsuga** [comment]
Thanks!

**Comment by laurenluz** [comment]
Hey @danelsuga please check in before changing capitalization, or assign me to review your PRs. Many things like "Future of Giving" or "Building the Future of Giving" are capitalized because they are parts of our tagline.

There are other things that we capitalize because we turned them into proper nouns... like Givers or Makers.

I still think there is probably some excessive capitalization in there & other grammer/spelling things, so please go forward w this, just keep the above in mind please.

**Comment by danelsuga** [comment]
Yes, thanks. That’s what I meant - I see who authored. Then I include you too. :P

**Comment by laurenluz** [comment]
ok cool 😅 Thanks! I also meant though that the "last updated" person might be the author, or might be the person who last fixed  a typo... hard to tell w the docs.

**Comment by danelsuga** [comment]
I still have a few more pages to go!
