### ISSUE TITLE
Video sound bites from EthDen

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-planning#552]
Collect video sound bites from Griff's EthDen talks and share with @ahmadabugosh.

**Comment by Elizardwizzard** [comment]
Hey! Im Elizabeth I got assigned this project on the comms call :), where can I access the material?

**Comment by danelsuga** [comment]
Hi Elizabeth!

Here are the videos to check out!

Griff: Creating Schelling Points for Public Goods via Micro-economies
https://youtu.be/cTMUh__9cWs

Griff: The Biggest Web3 Opportunity That No One Is Talking about
https://youtu.be/ADSOVkujrI4

Griff: Post-talk interview
https://m.youtube.com/watch?t=2558&v=pts4XqDRI_4&feature=youtu.be

Willy: Building a Future without Fees: Positive Sum Economies
https://www.youtube.com/watch?v=y-TOlyguMjQ

Lauren: Public Goods Are Good panel
https://youtu.be/LccyEBQ_BV0?t=1999

Lauren: Weavers of Web3 interview
https://www.youtube.com/watch?v=N__ljJR4yaY

**Comment by p-i-e-r-c-e** [comment]
Hey everyone :) - How should we split these videos up?

**Comment by danelsuga** [comment]
Hi pierce!

 I don't necessarily think they should be split up. It would be hugely valuable to learning about Giveth to check them all out if you can!

**Comment by danelsuga** [comment]
Elizabeth, I can't find you to assign you the issue. @Elizardwizzard is not coming up. Maybe you're not signed up yet?

**Comment by danelsuga** [comment]
Maybe for the sound bite task, how about if @Elizardwizzard takes #1 and #5, @pierce takes #4 and #6, and I'll do #2 and #3?

I've spent a lot of time on them already, so I think this might be a good breakdown, if that works for y'all.

**Comment by p-i-e-r-c-e** [comment]
@danelsuga @Elizardwizzard Works for me!

**Comment by laurenluz** [comment]
@Elizardwizzard if you can also do this one, it would be awesome: https://youtu.be/vAFqV1j_xX4?t=20063

Picking you because it's in spanish 😄 I think we won't share the video until The DAOist releases them as separate videos... but in the meantime we can still make the soundbite. Lmk if you have any questions

**Comment by Elizardwizzard** [comment]
Hey team! I have a few questions about the sound bites.
Should they be:
- Video clips (mp4) 
- Audios (mp3)
- Written transcripts. 
Or all of the above? 

- How long should they be?
- Where are they used for?
 
Thanks! :)

**Comment by danelsuga** [comment]
Thanks for the great questions, @Elizardwizzard! I think they can just be transcripts that are passed on to @ahmadabugosh.

They should be 10-30 secs. 

They will be used for promos. Ahmad would have specifics on that but I think in general you’ll be able to find soundbites they stand out that feature Giveth, something exciting, high energy and clear. For the Griff one, probably something succinct about his presentation of new economic models. But don’t necessarily focus on that. I think you’ll find certain things stand out!

**Comment by p-i-e-r-c-e** [comment]
@ahmadabugosh @danelsuga @Elizardwizzard 

https://www.youtube.com/watch?v=y-TOlyguMjQ
[5:42-6:06](https://youtu.be/y-TOlyguMjQ?t=342) Willy intros giveth causes 

https://www.youtube.com/watch?v=LccyEBQ_BV0&t=1999s
[33:59-34:28](https://youtu.be/LccyEBQ_BV0?t=2039) Lauren summarizes how we can incentivize giving and taking advantage of feedback mechanisms

**Comment by laurenluz** [comment]
Nice @p-i-e-r-c-e I'm with you on the video I'm in... I think that's a good clip... although I say "like" 100x 👀 maybe @ahmadabugosh can skip a few of them in the transcription 😅 

For the video w/ Willy, tbh, since the central point of the talk is using web3 techniques to create platforms that don't depend on fees, I would pick something more related to that point. Perhaps right at the beginning at [0:50](https://youtu.be/y-TOlyguMjQ?t=50) or shortly thereafter.

I think this clip about causes is a little bit abstract and misses the central point... although it will be cool.

**Comment by laurenluz** [comment]
Around [9 min](https://youtu.be/y-TOlyguMjQ?t=553) is also pretty cool :) imagine it from the perspective of someone scrolling through twitter... what are the words that will catch their eye and make them stop scrolling?

**Comment by Elizardwizzard** [comment]
Creating Schelling Points for Public Goods via Microeconomics 
https://www.youtube.com/watch?v=cTMUh__9cWs



Introduction of abundance economies 
3:45 - 4:14 

The lose - lose situation of financial opportunities in the actual system of abundance economics  
4:54 - 5:28

Feedback cycles are important, and conventional economic systems lack of it 
5:33 -  5:54

Positive externalities (public goods) come from abundance economies
7:28 -  7:49

There is no competition in abundance economies, Griff explains how cooperation is always the. way.
7:55 - 8:!5


Regen Economies = Mission driven economic systems 
9:07 - 9:19


Why do we need regen economies ( in examples)
10:42 - 11:00


We need to evolve with the world: Economic games 
12:20 - 12:36


Microeconomics: Small impacts make the real change 
14:49 - 15:16


What Giveth does in the words of griff
15:27 - 15:59



Commonstack: the applied research side of Giveth 
16:03 - 16:30

Giveth at the DAOist - Lauren 
https://www.youtube.com/watch?t=20063&v=vAFqV1j_xX4&feature=youtu.be

Lauren explains what the DApp is
5:39.29 - 5:39.49


Why Giveth started and how it became something else 
5:42:00 - 5:42:16


Society depends on sacrifice and why it is not sustainable ultraism 
5:42:16 - 5:43:00


GIVbacks - Lauren explains how they work 
5:43:10 -  5:43:47


Web3 education runned  by incentives 
5:44:45 - 5:45:06


How gurves help regen economies and the benefits of that 
5:51:21 - 5:52:01


What happens when projects become DAOS (with examples: clean water, education, etc) 
5:52:01 - 5:53:15



Creating abundant public good with Lauren Luz & Giveth
https://www.youtube.com/watch?v=N__ljJR4yaY



Combining the tech world with values 
1:18 - 1:48


The best of web3? Let’s start with descentralization
2:18 - 2:59

An upside of donating 
4:15 -  5:52 


Curiosity, potential-detection and education as motivation “one little nugget at the time”
9:21 - 10:52

**Comment by danelsuga** [comment]
2. Griff — EthDen 2022 The Biggest Web3 Opportunity That No One Is Talking about

https://docs.google.com/document/d/101-2609HzeHZ6eqQTSk6BFjdKI5GK8s0NF6JZUwbPN0/edit

**Comment by danelsuga** [comment]
3. Griff - EthDen 2022 Post-talk interview (« The EthDenver 2022 Experience »)

SOUNDBITES (also below)
https://docs.google.com/document/d/1069HVSEBbLgRVtd6EsYqEFpH08vSs6gr4WAs4c--V3Q/edit

42:38 Public goods are totally overlooked in this space. There is a huge opportunity to disrupt government and non-profit industries, which are just not working. And everyone knows they’re not working. We could do so much better with Web3 tools, regen economies, specifically. And there is no competition in the space, and every year we’re spending trillions on public goods. 

43:30 I think it’s the biggest overlooked opportunity, and I don’t think it’ll be overlooked for long.

43:45 If we can actually solve this problem, if we can actually coordinate around public goods productions in efficient ways, we won’t need governments anymore. And I thought that was the point when I got into crypto. I thought it was to change the way we coordinate as a society to the point where we don’t need these inefficient things that we invented when we were riding horses around.

44:10 I fully expect that crypto will come back around and get out of this « Oh, number go up. We’re only trying to make money » idea and come back to the idea of, « How can we create the most value for society? » 

44:15 Business models work great. Fundraising through taxes and donations really suck. I think we can make major moves.

45:45 I love this idea of competing microéconomies to provide value for society. I feel like it’s really happening.

46:30 You don’t need to be a dev to actually provide value in this space. You can start connecting with people that your value is a positive sum game with them. Build something, learn something.

**Comment by ahmadabugosh** [comment]
Hey everyone, I made this sheet to keep track of these sound bite videos: https://docs.google.com/spreadsheets/d/1KoVy2Ttvo3Q3GxnFx-6pNS01VfvgjDok95aNY9JKTik/edit#gid=0 

I made the first one you can check out here, now I'll start working on the others: https://share.descript.com/view/jyXYbll92dh

**Comment by laurenluz** [comment]
Hey @ahmadabugosh for the first one you created, can we make it shorted? I would cut out the last sentence about "this is our long term mission at Giveth..." to keep it a bit shorted. Not sure if you were still making tweaks to this or not. It would also be nice to slow it down a little, maybe increase the pauses a bit. But if you're not doing any more work on it, it's totally fine as-is as well.

**Comment by ahmadabugosh** [comment]
Hey @laurenluz I cut out the last part and added some pauses. I tried slowing it down a little, but it sounded a bit robotic so I kept the speed as is 😄 https://share.descript.com/view/H3arB8PhX8R

**Comment by p-i-e-r-c-e** [comment]
@ahmadabugosh For the video with [Willy](https://www.youtube.com/watch?v=y-TOlyguMjQ&t=50s) - I think these sound bites may be more relevant.

1:50-2:17 - Willy talks about how there are better ways for Dapps to monetize than extraction and also speaks on benefits for users

0:50-1:04 Asks listeners to imagine a future where other than fees, people don't pay to use Dapps

**Comment by danelsuga** [comment]
> Hey @laurenluz I cut out the last part and added some pauses. I tried slowing it down a little, but it sounded a bit robotic so I kept the speed as is 😄 https://share.descript.com/view/H3arB8PhX8R

Hi @ahmadabugosh Thanks for doing this! It’s great. A few comments from my perspective:

I also agree it’s really fast! But it sounds like you can’t change that. I also think it’s a bit « rambly » (no offense, Lauren!). I don’t think « regular » people would be able to follow it or its message; you kind of already need to know what it’s talking about to understand it as it is. So if it’s going to be used, I highly recommend modifying the grammar in the text to help guide the eye. Here is what I suggest (sorry for the French quotation marks!):

If we tokenize non-profits, and the people —instead of donating and giving away— they donate, and they get a token. And if that non-profit does well, then that token price can go up. We align this idea of « I would like the token to go to the moon » with « Oh, I actually care about my kid’s schooling system. » So it’s parents —at the same time as having a comfortable living environment— can also contribute to the school system. And I think it’s: How do we bring all these things together? And then also take advantage of the feedback mechanisms that we’re creating in DAOs with token weighted voting and all the communication we’re building.

**Comment by ahmadabugosh** [comment]
hey @danelsuga thanks for the feedback! 

I guess it goes back to what is the goal of these videos? The way I see it, the point of these videos is to catch people's attention while they're scrolling on social media as a teaser to get them to want to listen to the entire talk (most people will scroll past it while it's muted and not even hear it). So in that sense, even if it's missing some context as a talking point, I think it does the job of saying something interesting enough to get people curious.

Thanks for the feedback on the grammar! I updated this one, let me know what you think: https://share.descript.com/view/mFMC5HNbN7D

**Comment by danelsuga** [comment]
You're totally right!

The new one is great!! You can change the French quotes to regular ones. :P 

Thanks, @ahmadabugosh!
