### ISSUE TITLE
List of marketing/design tasks for recruitment

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#580]
From @markoprljic:
"We're looking to recruit a new graphic designer and would give them some marketing design tasks to do as part of the recruitment process. Can you draft some current and/or future campaigns in a document, describing the requirements and output, i.e. a design brief? 
If yes, can you let me know when is the earliest to expect this?"

**Comment by laurenluz** [comment]
we could also use (asap)
- twitter images to announce the new dapp design

**Comment by markoprljic** [comment]
> we could also use (asap)
> 
> * twitter images to announce the new dapp design

We need descriptions and design guide for this. Designer should know what to do, what is the output, messaging, reference  examples etc.

**Comment by danelsuga** [comment]
Thanks @laurenluz! Is there a doc for this now that will be shared with @markoprljic or should I just give some thoughts here? In any case, here are my thoughts of what that forthcoming article could use:

For the upcoming article on the history of the Giveth galaxy (potentially: The Hitchhiker’s Guide to the Giveth Galaxy), I’d say some ideas that reflect that link to HG2G. Beyond that, I’d say having graphics/images for the different orgs, maybe a Venn diagram or something clever!

I realize this is vague. For the moment, I would say, for my part, @markoprljic you can have recruits come up with graphics, etc. that reflect the interconnected history and community of the following: 

White Hat Group
Giveth
Commons Stack
TEC
BrightID 
Dappnode
Trusted Seed
1Hive
General Magic

The style should be « lovey dovey » and « hippie » and not at all hard or computery, if you see what I mean. The philosophical focus of the article will include how the Ethereum community developed as a supportive and very kind, personable environment and how all of the above could flourish due to that and due to the desire to make the world a better place and to « scale horizontally » by allowing different ideas to emerge with their own agency. Giveth could develop the GIViverse as a series of partnerships (as opposed to internal departments or something). Thanks!

**Comment by danelsuga** [comment]
Here’s a bit more context for what I mean:


The Hitchhiker’s Guide to the Giveth Galaxy

Far out in the uncharted backwaters of the Giveth Galaxy lies a growing community of interconnected projects and DAOs, bound by history and propelled in communion by a sense of common good. 

[IMAGE of galaxy populated with all the various branding icons]

How do they connect and whence do they come? Read on to explore the history and camaraderie of these partnerships.

**Comment by danelsuga** [comment]
@markoprljic 

Here’s a bit more context for what I mean:

The Hitchhiker’s Guide to the Giveth Galaxy

Far out in the uncharted backwaters of the Giveth Galaxy lies a growing community of interconnected projects and DAOs, bound by history and propelled in communion by a sense of common good.

[IMAGE of galaxy populated with all the various branding icons]

How do they connect and whence do they come? Read on to explore the history and camaraderie of these partnerships.

**Comment by laurenluz** [comment]
@markoprljic who is working on this? can you assign them?

**Comment by markoprljic** [comment]
Poaps are in progress
Hitchhiker banner is done by Lulu

For twitter campaigns I need a design brief from someone.

Thanks!

**Comment by danelsuga** [comment]
Thanks @markoprljic !

**Comment by laurenluz** [comment]
Do you stilll need tasks @markoprljic ? or can we close this?

**Comment by markoprljic** [comment]
You can close
