### ISSUE TITLE
Create Typeform for Buddy Reviews

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#584]
## Work Agreement - Buddy Review

To be filled out by the buddy (reviewer) during or after the buddy review. Buddies must fill out this form to record they’ve conducted reviews consistently (at least every quarter), and to have one place to gather and document each buddy review discussion.

as per - 
https://forum.giveth.io/t/upgrading-giveth-hr-work-agreements-termination-and-intra-wg-governance/431/9?u=mitch

**Comment by freshelle** [comment]
Draft typeform: https://giveth.typeform.com/to/r21q3oSB

Set of questions is found here - https://docs.google.com/document/d/16_wPhtYZ7rWm8r2lNUp7mIM6x1oZ1pn1ZH2iUVVyRBY/edit?usp=sharing

**Comment by freshelle** [comment]
I think this typeform is not necessary. Since we will be sharing answers to the buddies, it would be better to record the answers to these work agreement questions in the doc that will be shared with them. 

So,
1. Gather answers of self-review form.
2. Share a google doc to the reviewer containing 
- their buddies' self-review form and Giveth feedback answers
- questions about work agreement

**Comment by divine-comedian** [comment]
So should we have a template of questions for buddy reviews? what kind of discussions should be had?

**Comment by freshelle** [comment]
The same set of questions we've prepared, but just include the questions in the doc that will be shared with them (answers to the self-review form).

Similar to what you've shared for Jahan's review, it was in a google doc. So I was thinking maybe it was easier to place those in a doc instead of entering in a form.
