### ISSUE TITLE
Pull out donations from Gitcoin

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-planning#59]
This is very easy... but only the owner of the Gitcoin grant can do it... not sure if its Willy

**Comment by willyogo** [comment]
Griff exported the list of gitcoin donors, but for some reason it doesn't include the donors ETH address, which we need in order to include the donor in the airdrop. Please figure out a way to get the donation address for each donation in this spreadsheet. It may require exporting the list from etherscan rather than gitcoin.

The spreadsheet is named '[Gitcoin Donors June-Dec](https://docs.google.com/spreadsheets/d/1vpoKMSYVIuV2Db84TVJC1AUPj9GReWg8qTkBoMfFyXA/edit?usp=sharing)'

AC:
1. A spreadsheet of all donors to the Giveth's gitcoin grant between June and December is compiled
2. Spreadsheet includes donors' ETH address, cost basis of donation, and ideally txid
