### ISSUE TITLE
Video sound bite from Giveth CDMX DAOist talk

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#599]
@Elizardwizzard can you find a couple of good clips from this talk? https://www.youtube.com/watch?v=YsseimigT4Q

Pick something that is meaty and in-line with the central message of giveth... maybe something about turning nonprofits into DAOs or being not-just a donation platform.

Find 2-3 soundbits of up to 30s and tag me when you pick 'em so I can review! :D

**Comment by laurenluz** [comment]
@Elizardwizzard can you type out the quotes that you selected so it's easier for me to review and pick one?

**Comment by Elizardwizzard** [comment]
Why Giveth started and how it became something else

5:41: 59 - 5:42:19

"La razón por la cual empezamos Giveth era para hacer un puente muy fácil para los non profit y los donantes para entrar a la web 3, pero la web 3 tiene un montón de cosas que podemos aprovechar y Giveth esta haciendo más con eso."

Society depends on sacrifice and why it is not sustainable ultraism

5:42:19 - 5:43: 07
"El problema ahora en el sector de bienes públicos es que la sociedad depende del sacrificio para hacer esos bienes públicos los non profits que están haciendo el trabajo tienen que pedir donaciones de los donantes, los non profits y las personas tienen que ser voluntarios que tienen que hacer el trabajo, también los donantes no tienen la expectativa de recibir algo de vuelta.  Ellos van a dar porque sí, porque quieren, porque tienen corazones grandes pero ese sistema no es sostenible. En Giveth estamos haciendo algo diferente para solucionar eso..."

Web3 education runned by incentives
5:44:45 - 5:45:06
"Lo que que queremos hacer es enseñar sobre web 3 con curiosidad, por interés , la gente que viene a Giveth a hacer una donación , hacer una donación es muy fácil y después recibe Giv y después tiene preguntaas, ¿qué es Giv?¿ qué es un DAO?¿Cómo puedo usar esos Tokens de hacer votar?"

How gurves help regen economies and the benefits of that
5:51:21 - 5:52:01

"Vamos a seguir haciendo economias regenerativas para los bienes públicos y hay un montón de ventajas, con eso las personas que creen en el bien publico pueden tener una voz y las personas que están apoyando pueden ser exitosas y beneficiarse también de eso, porque el precio del token va a subir y si mas personas quieren apoyar ese bien publico el token va a subir y el proyecto va a ser exitoso y todas las personas que están apoyando van a ganar. "

What happens when projects become DAOS (with examples: clean water, education, etc)
5:52:01 - 5:53:15

"Vamos a tener diferentes economías regenerativas en Giveth así es como estará organizado, muchas comunidades, muchos proyectos, bienes públicos con sus propios tokens, sus propios DAOs, sus propios métodos de comunicacion y gobernanza descentralizada, podemos financiar bienes públicos de una forma muy diferente...

¿Qué significa eso?
Podemos sacar el plástico del mar
Financiar proyectos open source
Podemos dar educación gratis,
Cuida a la tierra de una forma regenerativa,
Podemos cuidar a personas sin casa en ciudades, Podemos cuidar a cumunidades en Africa, podemos alimentar a los que no tienen comida, podemos apoyar los bienes publicaos de una forma que beneficie a todo el mundo."

**Comment by laurenluz** [comment]
@ahmadabugosh Can you make a soundbite video with this content:

> How gurves help regen economies and the benefits of that 5:51:21 - 5:52:01
> 
> "Vamos a seguir haciendo economias regenerativas para los bienes públicos y hay un montón de ventajas, con eso las personas que creen en el bien publico pueden tener una voz y las personas que están apoyando pueden ser exitosas y beneficiarse también de eso, porque el precio del token va a subir y si mas personas quieren apoyar ese bien publico el token va a subir y el proyecto va a ser exitoso y todas las personas que están apoyando van a ganar. "

**Comment by ahmadabugosh** [comment]
@laurenluz @Elizardwizzard Apologies for the delay! Does this look ok? https://share.descript.com/view/9znnfrK0EaG Sorry I don't speak Spanish at all, and don't know if I made any mistakes

**Comment by laurenluz** [comment]
Thanks @ahmadabugosh it's great. Just a small typo:
![image](https://user-images.githubusercontent.com/75490971/165109907-9c9a55f5-e911-4511-9b92-46e72a7ce29d.png)
 should be a space here: "exitosos y"

**Comment by ahmadabugosh** [comment]
Fixed @laurenluz https://share.descript.com/view/OulLuRTPpRX, also added raw file here: https://drive.google.com/file/d/1kw6e22MDLYYwyI1PLN5BMUdOZPJLr_s7/view?usp=sharing

**Comment by laurenluz** [comment]
Great! I will tweet this out soon

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1523678344503459842
