### ISSUE TITLE
Strategy: Get projects to advertise to their donors that they should use Giveth to donate

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#629]

**Comment by laurenluz** [comment]
Those are good ideas. I didn't have anything in mind, just it would be good if projects did advertise to their donors. @c0ric0ri can maybe support w/ some ideas as well.

I like the idea of creating content that makes is easy for projects to explain Giveth to their donors. I have some vague recollection that we prepared something like that before. Maybe @clara-zi or @WhyldWanderer have an idea.

**Comment by clara-zi** [comment]
We put together this fundraising campaign guide; you may be able to use some of the soundbites / messages in here:
@tropicalmangos 
https://docs.google.com/document/d/1nqrhxv_-WpRM2lQBaAOiTBIUFWEszPJmVdOLZ08PBb8/edit?usp=sharing

**Comment by laurenluz** [comment]
Sounds good @tropicalmangos ! If you make some drafts for the content for social media & email, & post here, I can review.

**Comment by laurenluz** [comment]
@ahmadabugosh @c0ric0ri @danelsuga - any of you available to review?

**Comment by ahmadabugosh** [comment]
@danelsuga I think now this makes sense to be put on hold until we have the Ambassador and/or referral program up and running. Let's revisit in a few weeks.

**Comment by c0ric0ri** [comment]
Just moving this to backlog for now until we revisit

**Comment by c0ric0ri** [comment]
What is a good checklist to provide projects with to encourage them to engage with their networks?

**Comment by c0ric0ri** [comment]
This issue doesn't have a tangible task and has been sitting here for months, so moving to Icebox

**Comment by ahmadabugosh** [comment]
Hey @c0ric0ri , 

I think we should leave this one open. I mentioned this on the comms call. The tangible task is to create an email that goes out to Projects (we already have the [draft here](https://docs.google.com/document/d/1tWozEg0_EiSLkj800Z_fw0ssf-zz1VH9LLlitDEZe2E/edit)). 

So the next steps for this are: 

1) Edit the email and add info on the referral program to it.  
2) Create templates within the email that projects can use on social media and send to their email lists. This would be in the form of recommended scripts and / or a graphic they can use. 
3) Once we have that, we'll add it to an automatic flow in Autopilot. 

Tagging @danelsuga and @Cotabe who offered to help with this and push it forward.

**Comment by NikolaCreatrix** [comment]
Hey! So I have just read through the whole discussion and a trying to envision how I can help with this. @danelsuga are you still interested? Shall we complete this task? Can I help you with anything? I am noticing that this issue really needs just a bit of tweaking and it's good to go. I think Suga you are the best person for this! 

This issue has its 1 year anniversary this months, LOL. :D

**Comment by danelsuga** [comment]
Can I catch you next week @NikolaCreatrix ? I'm on vacation with the kids. :)

**Comment by danelsuga** [comment]
clarification @ahmadabugosh :

what is the difference between these two (first) emails?

[Template - Project Emails to Donors](
https://docs.google.com/document/d/1kSU0fCSYbwGtKnzupznIPuk6dRmhDWDFJt3vO4zZYew/edit#)

[Automated - Project Emails to Donors](https://docs.google.com/document/d/1tWozEg0_EiSLkj800Z_fw0ssf-zz1VH9LLlitDEZe2E/edit#)

**Comment by danelsuga** [comment]
disregard (deleted) last comment. meanwhile, i'm re-editing the emails.

**Comment by danelsuga** [comment]
Let me know whatcha's think.
@ahmadabugosh @NikolaCreatrix @c0ric0ri

**Comment by NikolaCreatrix** [comment]
@danelsuga I am loving it! You are SO good at this! 

There is only tiny nuance I have noticed in terms of verified vs new projects on Giveth.

Are we targeting this email only for Verified Projects? Because if so, then maybe we want to start the email with something like " Congrats on getting your verified badge!" instead of the current  "Congrats on getting your project up on Giveth!"  

I think it's a good idea to keep it targeted on Verified...

If you think we should send it to ALL projects - we need to diversify the emails a bit.
Curious what @ahmadabugosh thinks.

**Comment by c0ric0ri** [comment]
Hey @danelsuga awesome job drafting these!! I did leave a lot of tweaks and comments across the three drafts. If you can help clean it up and let me know, I'm happy to take another look.

We should also add some design improvements / Giveth's logo to these pages to make them nicer for sharing externally, what do you think?

**Comment by oyealmond** [comment]
hey @ahmadabugosh! These email templates are still useful?

**Comment by surbhiaroraa** [comment]
I have been thinking about this and have some thoughts. Sharing them below:

Its very important that we leverage the strong community and follower base that the projects have. But why will the projects share posts with their community? I was thinking can we incentivise the projects to actually do everything that we want them to to market their project listing to their community?

Can we do a leadership board for projects? 

Projects which do marketing will get selected for future Quadratic Rounds or get featured on the home page which gives them better visibility and increased donations?
This incentivisation program can be structured as below: 

- Sending an email to their donor base gets them 500 points. 
- Posting on social media gets them 50 points per post per social media
- Writing a blog featuring us or talking about why they chose to list their project on Giveth etc gives them 100 points
- Adding Optimism address gets them 100 points (In future if there is anything similar which we need projects to do for any grant or anything we can add that as one of the point) 

How can we incentivise more projects to do the above things using this leadership board?
- Display the leadership tracker on our website, we can put it every 2 weeks in discord or on social media. 
- Talk about it in Meet the Makers event. 
- We can also send an email to projects every 2 weeks with the current tracker inviting them to send emails to their community and post etc.

QF is incredible mechanism. We should use it more aggressively to create that FOMO of not being in part of the round. 

To do all of the above, what will be the effort or work required from our end?

- Draft emails on behalf of projects (these will be templates so its not like for every project we are drafting new emails)
- Draft social media posts along with graphics (again we can have a template made in canva for graphic so that we dont even have to depend on design team) 
- Announcement from project’s side why they are choosing to list on Giveth - again we will have draft text and graphic which can be used for all projects. 

@oyealmond  @ahmadabugosh @laurenluz @danelsuga @NikolaCreatrix @WhyldWanderer What do you all think?

**Comment by oyealmond** [comment]
Hey @surbhiaroraa! Adding @divine-comedian so he can share some thoughts, as I understand this idea will require devs work. Maybe he has some feedback. 

I think your gamification suggestion is great! Im not sure if we have the bandwidth to develop all this tho. My suggestion will be start w the templates @ahmadabugosh & the team work around this and iterate afterwards, as I see it as a low hanging fruit. 

Open to listen to you all.

**Comment by oyealmond** [comment]
hey @ahmadabugosh @anamarija09 following up on this issue, I review and added our promotional tips and tricks guide to Suga's email, and included Instagram in the social media messages for projects. 

Wondering what's the next steps for this to create a new Autopilot journey. 

[Template - Project Email to Donors](https://docs.google.com/document/d/1kSU0fCSYbwGtKnzupznIPuk6dRmhDWDFJt3vO4zZYew/edit)

[Automated - Project Emails to Donors](https://docs.google.com/document/d/1tWozEg0_EiSLkj800Z_fw0ssf-zz1VH9LLlitDEZe2E/edit#heading=h.6y3ueclb9mux)

[Social Media Template](https://docs.google.com/document/d/1WBGaRLQwxTlAPW7ZYDoP-bxr8J-B7q8XZCYuCi7JEMU/edit?usp=sharing)

Thanks!

**Comment by oyealmond** [comment]
Meybe we should re think this issue @ahmadabugosh
