### ISSUE TITLE
An Unconference Session on Reimagine Social Impact

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-planning#651]

**Comment by melodysongq** [comment]
Audience: EthBarcelona participants who care about giving and social impact and can be potential donors of Giveth
Goal: To collect feedback and ideas on motivations for donors to give so that Giveth can design the product betterr

This is a facilitated OST session on Reimagining Social Impact, we ask participants to bring to an open space their questions, issues, painpoints in giving to social impact (10 min) and have 30 minutes group discussion of each of the topics (multiple group discussion at the same time).  At the end, we ask the group leader (usually the person who asked the question, bring in the issue to discuss) to share the ideas and also do a one minute video after the session on the summary of that topic.   Together, we are looking to co-create solutions and blue sky reimagine what giving can be like, what problems people are having etc. that would inform the engagement of donors.  This information will be shared on social media as well as with projects on the Giveth platform.

**Comment by melodysongq** [comment]
I've already applied to facilitate this session.  Alternatively, this can be a side-event.

**Comment by laurenluz** [comment]
@melodysongq did this get accepted?

**Comment by markoprljic** [comment]
Wondering the same. I submitted my application but haven't heard back from them yet.

**Comment by melodysongq** [comment]
@laurenluz @markoprljic  I have not heard back from them.  Do we know someone we can check what happened to the applications?

**Comment by laurenluz** [comment]
I sent a message to Almond... Michaela is also the one organizing talks, it might be useful to message her: https://twitter.com/micaela_31416

**Comment by melodysongq** [comment]
I've reached out to Michaela. We'll see.  @laurenluz

**Comment by laurenluz** [comment]
I heard back from Almond and she said that Michaela said that all speakers for giveth were already covered, which she interprets as "there will be no more speakers confirmations". 

she also apologized for their team not being more communicative on the applications.
