### ISSUE TITLE
Email announcement of Giveth Donor 101 course

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#661]
The draft could include a link to the video series + one to the blog announcement

Link to video series: https://www.youtube.com/watch?v=kfoyvsPYnrE&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=1

**Comment by laurenluz** [comment]
It's awesome, left small comments & suggestions.

**Comment by ahmadabugosh** [comment]
@laurenluz obvious question I forgot to ask, who should I send this out to (which autopilot list)? 
Should this go to all Donors, Projects, the Newsletter list, or all of the above?

**Comment by laurenluz** [comment]
Maybe we can restructure it to have a "for projects" & "for donors" part and send it to all?

I think we don't send out too many annoying emails and we worked hard on this. what do you think?

**Comment by danelsuga** [comment]
I like that idea.

**Comment by ahmadabugosh** [comment]
Hey @laurenluz @danelsuga , I changed the wording: https://docs.google.com/document/d/1x_yzU3TXqw1EwrzyGn-PwOUHShCj12WpbH8mnPcKey4/edit. Let me know if you have any comments.

 Ideally, I'd want to send this one out in the next day or two (before the weekend), then I'll push the main newlsetter out to early next week (since by then hopefully we'll fix the typeform issue).

**Comment by danelsuga** [comment]
Looking good! I might change this sentence around from negative to positive:

This course is predominantly aimed at donors, so if you’re a project, we recommend you share it with your audience as well (retweet us, to encourage your community to support your project)!

**Comment by laurenluz** [comment]
it's great, I made small suggestions. +1 to Suga's comment.

**Comment by ahmadabugosh** [comment]
Sent!
