### ISSUE TITLE
Interview and record project owner's platform sign-up problems.

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#665]
@ahmadabugosh to provide project contact's details.

**Comment by ahmadabugosh** [comment]
Hey @clara-zi this is the project that is having difficulty registering: https://giveth.io/project/nisria  My understanding is:
1) She was having difficulty logging in, since she had an Ethereum address she wanted to send funds to, but didn't have Metamask or a wallet setup on her browser 
2) When the project eventually got published, the Ethereum address for her project was different than the one she submitted initially (or she thinks that's the case)


I'll DM you her contact details now so you can follow up with her 🙏

**Comment by clara-zi** [comment]
Project owner to voice record and document key issues (async). Claire to review and then 1-1 to discuss and progress key issues.

**Comment by clara-zi** [comment]
1) **Not able to consistently log-in on Mac** sometimes not able to log-in using Mac laptop: system sends her round in a loop, asking her to verify email over and over. Verification link in email doesn't link to anything. Her solution has been to leave the log-in process for a day or day and then go back to it and it work. She has cleared her history. This is not an issue all of the time. When logging in with i-Phone, she does not experience these problems.

2) **Project not linked with account** Because she has tried to register a few times and has used different devices, she believes it has created a 'glitch' in the process. When she logs in with her account, using the exact details, she cannot see a project on her account. However, she has received a confirmation email to say project is listed. But, if she goes to the platform and searches for her project, she can find the listing but cannot see it in her account!

3) **Wallet** Also the wallet address on her account is different to the one the project is listed with.

(I have some more detail in a recording)

@ahmadabugosh I think these are issues for the platform / dev team - seem like IT issues.

**Comment by melodysongq** [comment]
@clara-zi  I think it would be the best to post this issue on the Verification Channel (I will do) so that people can discuss and go to the next step on fixing the bug.

**Comment by clara-zi** [comment]
Project seems to be registered in Kenya. Project owner has asked for guidance for process to show registration. 
She has been unable to find out how to show this through Giveth. 
@clara-zi to follow-up.
I have requested registration certificate.

**Comment by clara-zi** [comment]
_Summary & recommendations:_ (WIP)

- [ ] reapply for verification in next round (should be verifiable if proj. link posted on social)

**Comment by clara-zi** [comment]
> I think it's the best to apply again. I've post this on the Verification channel. Also today at Verification party. the team can take a note of this project and note down the reason for decline from last time. Also, this is an example of not enough information on the project page as well. they really need a better write up to describe to get donors' attention otherwise a waste of time.

I think the profile is brief because project owner has had difficulty logging in to platform to complete profile. Will verification team feed back - is there a standard process when projects are rejected for verification? @melodysongq

**Comment by WhyldWanderer** [comment]
Hey @clara-zi .. 

Just wanted to leave some information in here that might be helpful for this user.. Im not sure if they are still facing these problems..

In response to your point #1 above - this is a torus thing... this has happened to other users as well including myself. Unfortunately, there is nothing that Giveth can do about this. We can refer them to Torus customer support and I think this is really our only avenue for these cases (the verification email loop - torus sends a verification email with a link that youre supposed to click and then it logs you in successfully... but this isnt always the case and you often have to ask it to send the email again - very frustrating)

And to clarify the process for rejection..
The project owner receives an email upon rejection that says this:

![image](https://user-images.githubusercontent.com/74267818/168440446-4c7865e9-7350-4897-973d-65da2f0dcf23.png)

**Comment by clara-zi** [comment]
> Hey @clara-zi ..
> 
> Just wanted to leave some information in here that might be helpful for this user.. Im not sure if they are still facing these problems..
> 
> In response to your point #1 above - this is a torus thing... this has happened to other users as well including myself. Unfortunately, there is nothing that Giveth can do about this. We can refer them to Torus customer support and I think this is really our only avenue for these cases (the verification email loop - torus sends a verification email with a link that youre supposed to click and then it logs you in successfully... but this isnt always the case and you often have to ask it to send the email again - very frustrating)
> 
> And to clarify the process for rejection.. The project owner receives an email upon rejection that says this:
> 
> ![image](https://user-images.githubusercontent.com/74267818/168440446-4c7865e9-7350-4897-973d-65da2f0dcf23.png)

So, if project-owner was to use Metamask, this problem would be solved? She would have one wallet for project and she would be able to log-in consistently on all devices and edit the project profile?
Seems like it would be better to delete the existing profile (is this possible?) and start again?
@WhyldWanderer @ahmadabugosh

**Comment by WhyldWanderer** [comment]
Yes, the problem could not happen because Metamask is not directly connected to your identity (email) and will not ask for verification of these things. 

However, it is important to keep in mind that if the project owner chooses to use a metamask, they will be entirely responsible for their funds and their keys. If something gets lost or goes wrong, it is completely on them and there is no 'forgot password' option and the support team does not have access to any accounts etc.  

I would hate if a project owner lost access to all donations made to a project becasue they didnt write down their private key. 
Torus support team has been a lifesaver on a few accounts so it may be worth the hassle depending on the crypto literacy level of the user.

I see 2 options in this case
1. Talk to the torus support team... get the email verified.. regain access to the torus wallet. Once the user has access to the wallet, they can get their private keys and import this wallet into MetaMask. The user will have access to the address with Torus and MetaMask... this way the user can connect to Giveth using MetaMask and other applications. We will make sure that they know to keep their private keys private and to keep them somewhere safe. HOWEVER, if for some reason they lose access to the wallet, they can still go back through torus and have access to the wallet and access to a support team.

2. If they do not want to talk to torus support and go through the steps of importing the wallet as described above, they can always create a new wallet with MetaMask - **please make sure they understand the importance of private keys and recovery phrases always being private** - They would need to provide sufficient evidence that they are indeed the original owner of said project and the support team can help them to get the wallet address switched for them in the database.

Let me know if you would like support with any of this!

**Comment by clara-zi** [comment]
Thanks for all the info @WhyldWanderer. 
Torus problem sorted out and now verified.

Project owner created a MetaMask account but found it too complicated to connect to their Giveth account and so will continue with Torus.

I am recommending to reapply for verification @melodysongq

**Comment by clara-zi** [comment]
Project owner will reapply for verification. I've invited for community spotlight.

**Comment by WhyldWanderer** [comment]
Since the issue has been resolved, can we close this one?
@clara-zi

**Comment by clara-zi** [comment]
Ooh yeh
