### ISSUE TITLE
Bring Commons Stack prize contenders to Giveth

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-planning#687]
Invite the non-winning projects contending for the new Commons Stack Prize to Giveth where they will find happiness.

**Comment by danelsuga** [comment]
Finalists as plucked from Tokenlog:

Grassroots Economics wins.
Followed by Juanka's Gravity DAO.
Followed by:

Precious plastic commons
jaklatt#2299 
@jaklatt

The AI Commons / Algovera
ygg_anderson#4998 and richardblythman and Algovera.ai#3425
@ygg_anderson and @richardblythman

ReFi DAO
John Ellison#5093
@climateXcrypto

Unmonopolizable Therapies Commons
Savvy Kerdemelidis$9857 and Nick FIORENZA#8698
@CrowdFundedCure and @nfiorenza

TODAO
Graial#0787 
@in_economy and @banal_na_graial

Breadchain Commons
Theblockchainsocialist#5005
@tbsocialist

All for Climate DAO
xdamman#3734 and Leen$8610
@xdamman and @leen_schelfhout

Web3 Designers
Markop#2007
@markoprljic

ReCommon
Alex | RegenCLT#0174
@arcorren and @RegenCLT

Liberating Structures Commons
Jeremey&TheGospelofChange#8201
@gospelofchange

Underground DAO
flaneur#6084
@jasoncremerius

Food Forest Commons
DiogoJ$$2058
@DiogoJo61288106

Fable DAO
jeverett#3344
@jeverettnichol

Greens for Good
T!b!#2584
@TiberiusB

The Villagers Commons
Kojak#5611
@kojak

Open Cultivars Commons
Chris Byrnes#4168
@reimagineIP

40 acres (I remember them from Gitcoin)
Catalyst#8424
@40acresDAO

ReeFi Commons
kluless.eth$0013
@kluless_

Decentralized Arts Commons
Metarishi | Artsect | citizend |#2621
@artsectDAO

Alas! A Cyber Physical Commons for OpenGuitar.
kn00t (lizard, lizard)#8297
@TorstenGoerke

“Recovery and healing to earn” dAPP and NFT assisted.
Paul in Albuquerque#4390
@Chavezpt

Matriz
alexsotodigital#7208
@alexsotodigital

SEEDS COMMONS
Nadim#0384
@SEEDSeconomy

Impact(NFT) Commons
MetaMaximus#9821
@Pericarus

XRFoundation
Josh australia#2302
@HexaField

WellnessDAO commons
ericc572#8077
 @wellnessdao

OpenTEAM
 JoshAFairhead#3602
@joshafairhead

The Infinite Game
Center4CollabEcon#1426
 @C4CollabEcon

Save DAO
Goldenageguide#5455
@Adbongogroupllc

The RESET
HerbStephens#1204
@herbstephens

The Overweb
shiftshapr#6332
 @shiftshapr

GreenPandora DOA
BoncoQ75#7558
@JQBonco

Withdrew:
KERNEL
I'm assuming it's this: 
https://www.kernel.community/en/
The post I read about them withdrawing did not have any active contact info.

**Comment by laurenluz** [comment]
It would be amazing to send a message to each of these people - could use the draft template from gitcoin outreach & modifty for it

**Comment by danelsuga** [comment]
Ok!

**Comment by danelsuga** [comment]
The next step for this issue is to do the outreach. No message has been drafted yet.

@laurenluz 
@ahmadabugosh 
@Cotabe 
@rainerhoell 
@clara-zi 
@melodysongq

**Comment by Cotabe** [comment]
Ok, there are 35 out of which one has withdrawn. I can outreach to all of these.

@laurenluz @ahmadabugosh @danelsuga @rainerhoell @clara-zi @melodysongq and @SymSL  can help on the Gitcoin ones. But I would greatly appreciate feedback on the messaging:

Hey [Name], this is Cotabe from Giveth. I saw that you participated for the Commons Stack Prize with [Project name]. I love/like how [project name] [project feature] (something authentic, of course). 

I wanted to encourage you to create a project on Giveth. Setup is very fast, so you could be fundraising from donors in no time. It has no cost and no fees so all donations go straight to your project's wallet. While your donors are rewarded with GIV tokens proportionally to their donations.

LMK if this is something you would like to explore.

**Comment by laurenluz** [comment]
That's awesome @Cotabe !! Thanks so much for taking this on!! Here's the tweet thread I sent out about it FYI: https://twitter.com/Givethio/status/1528772099791372288

One thing I would change... "straight to your project's wallet. After adding your project you can apply to get verified by filling out a typeform and proving you are providing public good. Once verified, your donors will be rewarded with GIV proportionally to their donations."

I would also just add the create project link right in your message, so they can even just jump on if they want to: https://giveth.io/create

**Comment by danelsuga** [comment]
Yeah, thanks, Cotabe! I’d like to add some tiny edits if you don’t mind. (I’ve also incorporated Lauren’s.)

Hi [Name], this is Cotabe from Giveth. I saw that you participated for the Commons Stack Prize with [Project name]. I love/like how [project name] [project feature] (something authentic, of course).

I wanted to encourage you to create a project on Giveth. Setup is very fast, so you could be fundraising from donors in no time. It has no cost and no fees COMMA so all donations go straight to your project's wallet. 

After adding your project COMMA you can also apply to get verified by filling out a Typeform and proving you are providing public good. Once verified, your donors will be rewarded with GIV proportionally to their donations.

Check out creating a project [link:
https://giveth.io/create], and/or reach out if this is something you would like to explore.


Maybe even direct then at the end to the Donor 101 Course? It's such a great intro to Giveth. Or even just the "Why Giveth?" video.

**Comment by Cotabe** [comment]
Love the suggestions. It turned out a bit long for a first outreach. I would suggest to do an A/B testing with something shorter that might link to why giveth video. Something like:

Hi [Name], this is Cotabe from Giveth. I saw that you participated for the Commons Stack Prize with [Project name]. I love/like how [project name] [project feature] (something authentic, of course).

I wanted to encourage you to create a project on Giveth. Setup is very fast, so you could be fundraising from donors in no time. It has no cost and no fees, so all donations go straight to your project's wallet and your donors may be rewarded for their donations.

Wanna know why Giveth is a great fundraising tool check out this video: https://www.youtube.com/watch?v=-JXwwIGJGQQ

Wanna DAO it... create your project here https://giveth.io/create

**Comment by laurenluz** [comment]
The draft message for gitcoin projects is here: https://docs.google.com/document/d/1OG1kyB9reY_B1A5BuKw3Gdt0Bz7z5HA0Cz_ljK6U8ZY/edit 

migth be helpful for this issue

**Comment by laurenluz** [comment]
Hey @Cotabe ! did you manage to do any outreach?

**Comment by Cotabe** [comment]
Outreach update:

Grassroots Economics - Already @ Giveth!!

Gravity DAO
 - @BellCho
: Can't DM on twitter

Precious plastic commons
 - jaklatt#2299 @jaklatt: Can't DM on twitter. Not many twits to engage.

The AI Commons / Algovera - ygg_anderson#4998 and richardblythman and Algovera.ai#3425 @ygg_anderson and @richardblythman: Sent FR on Discord. Engaged in a public twit. Also engaged in a common group we have on Discord.

ReFi DAO - John Ellison#5093 @climateXcrypto:  Sent FR on Discord. Engaged in a public twit

Unmonopolizable Therapies Commons - Savvy Kerdemelidis#9857 and Nick FIORENZA#8698 @CrowdFundedCure and @nfiorenza: Can't DM on twitter.  Engaged in a public twit

TODAO - Graial#0787
 @in_economy and @banal_na_graial: Not much info about the project

Breadchain Commons - Theblockchainsocialist#5005 @tbsocialist: Engaged in a public twit

All for Climate DAO - xdamman#3734 and Leen#8610: @xdamman and @leen_schelfhout
: Engaged in a public twit

Web3 Designers - Markop#2007
 @markoprljic: reached out just to know more about it.

ReCommon
 - Alex | RegenCLT#0174 @arcorren and @RegenCLT: Engaged in a public twit

**Comment by laurenluz** [comment]
you can get juanka on discord: Juankbell#7458

**Comment by Cotabe** [comment]
I'm continuing the outreach. Unfortunately, DMs on Twitter are usually closed by default (or fortunately), the same on Discord.

So the best way that I've found to reach out is through public tweets. 

I usually like or retweet a few tweets that I like. Then, I am being very selective in which tweets I engage, I don't chill directly, definitely not in behalf of Giveth. Here is an example: 

"YES!! Community in flesh! Love seeing web3 projects unfold in the physical space and would love to see and be a part of a regen community of land trusts for bioregional commons stewardship.

I'm a DAO member @ [@Givethio](https://twitter.com/Givethio). If you're looking into fundraising, I'd love to help 🤩"

So far Unmonopolizable Therapies Commons & ReCommon have responded and are interested. All for Climate DAO and ReFi DAO got likes.

I would love to know if this feels like a good approach? @laurenluz @danelsuga 

Another approach is going to the discord of some of those projects :)

**Comment by Cotabe** [comment]
Liberating Structures Commons - Jeremey&TheGospelofChange#8201 @gospelofchange: Already on Giveth since May. Have not raised though, could be good to invite him to a fundraising skills dev training.

Underground DAO - flaneur#6084 @jasoncremerius: Twitter inactive. FR on Discord

Food Forest Commons - DiogoJ#2058 @DiogoJo61288106
: Twitter doesn't exist. FR on Discord. Conversation started.

Fable DAO - jeverett#3344 @jeverettnichol: Twitter too personal. FR on Discord
. Already invited him to our Discord.

Greens for Good - T!b!#2584 @TiberiusB: Twitter too personal. FR on Discord


The Villagers Commons
 - Kojak#5611 https://github.com/kojak
: Sent FR on Discord

Open Cultivars Commons - Chris Byrnes#4168 @reimagineIP
: Twitter too undersused. FR on Discord

40 acres (I remember them from Gitcoin) - Catalyst#8424 https://github.com/40AcresDAO: FR on Discord

ReeFi Commons
 - kluless.eth#0013
 @kluless_: replied a tweet. Interested in setting up project on Giveth.

Decentralized Arts Commons
 - Metarishi | Artsect | citizend |#2621
 @artsectDAO: Not sure how good fit it is for Giveth. FR on Discord


Alas! A Cyber Physical Commons for OpenGuitar.
 kn00t (lizard, lizard)#8297
 @TorstenGoerke
: Already on Giveth
 (invite to fundraising dev skills)

“Recovery and healing to earn” dAPP and NFT assisted - Paul in Albuquerque#4390
 @Chavezpt: Already at Giveth https://giveth.io/project/social-impact-dao-llc


Matriz - alexsotodigital#7208
 @alexsotodigital
: Good friend I reached out by whatsapp

SEEDS COMMONS - Nadim#0384
 @SEEDSeconomy: engaged in a twit

Impact(NFT) Commons - MetaMaximus#9821 @pericarus: engaged in a twit

XRFoundation - Josh australia#2302
 @HexaField: engaged in a twit

WellnessDAO commons - ericc572#8077 @wellnessdao: engaged in a twit 

OpenTEAM - JoshAFairhead#3602 @joshafairhead: engaged in a twit 


Long day... Only 5 to go


The Infinite Game
Center4CollabEcon#1426
@C4CollabEcon

Save DAO
Goldenageguide#5455
@Adbongogroupllc

The RESET
HerbStephens#1204
@herbstephens

The Overweb
shiftshapr#6332
@shiftshapr

GreenPandora DOA
BoncoQ75#7558
@JQBonco

**Comment by laurenluz** [comment]
AMAZING work Cotabe!

**Comment by Cotabe** [comment]
Update:

Gravity DAO: Scott onboarded them.

Precious plastic commons- jaklatt#2299 @jaklatt: Sent FR on Discord

The AI Commons / Algovera - ygg_anderson#4998 and richardblythman and Algovera.ai#3425 @ygg_anderson and @richardblythman: Follow up with this tweet https://twitter.com/Cotabe_M/status/1535348397292498944?t=VmJGWi3zxYM1kcQ9jl7O2A&s=19

ReFi DAO - John Ellison#5093 @climateXcrypto: I'm stocked about this, have a call next Friday. They are very interested in collaborate.

Unmonopolizable Therapies Commons - Savvy Kerdemelidis#9857 and Nick FIORENZA#8698 @CrowdFundedCure and @nfiorenza:  Savvy is already on our Discord and participated in an AMA call. Will follow up.

TODAO - Graial#0787 @in_economy and @banal_na_graial: Not much info about the project

Breadchain Commons - Theblockchainsocialist#5005 @tbsocialist: Engaged in a public twit - No response. Can't add on discord, will try again

All for Climate DAO - xdamman#3734 and Leen#8610: @xdamman and @leen_schelfhout : No response to this tweet. Just added both as friends on Discord

ReCommon: Alex | RegenCLT#0174 @arcorren and @RegenCLT: We are exchanging DMs,waiting for them to book a meeting/join a meeting

Liberating Structures Commons - Jeremey&TheGospelofChange#8201 @gospelofchange: Already on Giveth since May. Have not raised though, could be good to invite him to a fundraising skills dev training.

Underground DAO - flaneur#6084 @jasoncremerius: Twitter inactive. FR on Discord. Not responsive

Food Forest Commons - DiogoJ#2058 @DiogoJo61288106: Conversation started, focusing on GR14 now. But interested

Fable DAO - jeverett#3344 @jeverettnichol: He is in our Discord, conversations started. Followed up on 06/21

Greens for Good - T!b!#2584 @TiberiusB: Talked on Discord. Didn't had a positive experience with common stack, he said he will explore, but not too excited about it (literally said that). I just asked if this is a fit then good, if not that's also ok.

The Villagers Commons: Kojak#5611 https://github.com/kojak : Sent FR on Discord. Not responsive.

Open Cultivars Commons - Chris Byrnes#4168 @reimagineIP: Twitter too undersused. FR on Discord. Not responsive

40 acres (I remember them from Gitcoin) - Catalyst#8424 https://github.com/40AcresDAO: FR on Discord. Not responsive

ReeFi Commons - kluless.eth#0013 @kluless_: replied a tweet. Already in Discord. Will reach out again tomorrow (06/22)

Metarishi | Artsect | citizend |#2621 @artsectDAO: Not sure how good fit it is for Giveth. FR on Discord

Alas! A Cyber Physical Commons for OpenGuitar. kn00t (lizard, lizard)#8297@TorstenGoerke: Already on Giveth
(invite to fundraising dev skills)

“Recovery and healing to earn” dAPP and NFT assisted - Paul in Albuquerque#4390 @Chavezpt: Already at Giveth https://giveth.io/project/social-impact-dao-llc

Matriz - alexsotodigital#7208 @alexsotodigital: Good friend I reached out by whatsapp. Interested in onboarding Matriz, but also another project that is supporting several non-profits (similar to Propel, could be a strategic partner). Call soon to schedulue.

SEEDS COMMONS - Nadim#0384 @SEEDSeconomy: engaged in a twit. FR sent

Impact(NFT) Commons - MetaMaximus#9821 @pericarus: engaged in a twit. FR sent

XRFoundation - Josh australia#2302 @HexaField: engaged in a twit

WellnessDAO commons - ericc572#8077 @wellnessdao: engaged in a twit. FR sent

OpenTEAM - JoshAFairhead#3602 @joshafairhead: engaged in a twit

Long day... Only 5 to go

The Infinite Game- Center4CollabEcon#1426, @C4CollabEcon: I think their scope is too similar to ours. Sent FR. 06/21

Save DAO- Goldenageguide#5455 @Adbongogroupllc. Engaged in a twet06/21

The RESET- HerbStephens#1204 @herbstephens. Sent FR. Engagend in a twet.06/21

The Overweb- shiftshapr#6332 @shiftshapr. Sent FR. Engaged in a tweet 06/21

GreenPandora DOA BoncoQ75#7558 @JQBonco. Sent FR. Engaged in a tweet 06/21

**Comment by Cotabe** [comment]
I will be following up this week @danelsuga

**Comment by danelsuga** [comment]
♥️🙏🏼

**Comment by Cotabe** [comment]
Sorry it took me so long to come back to this topics.

But the results are actually quite good. 10 out of 34 projects are in Giveth. I just followed up with a few more.

I made a summary in an excel sheet to import it to the CRM

https://docs.google.com/spreadsheets/d/1AzbwuFfDXqnFXCOyChlDtHWkb-BxM9HSj8FbfuX8uIQ/edit#gid=0

**Comment by richardblythman** [comment]
Hey @Cotabe. We at Algovera never got around to setting ourselves up on Giveth. Is there someone I could reach out to (e.g. on discord/telegram) for information about the process?

**Comment by danelsuga** [comment]
@richardblythman Yes!!! The connect team is here for you! @rainerhoell @Danibelle @WhyldWanderer and more!

**Comment by Cotabe** [comment]
Yes @richardblythman all the above & I think the quickest response you would get on Giveth Discord. Specially on the Makers space. Also every Wednesday at 10am CST we have an AMA session for stakeholders.

**Comment by c0ric0ri** [comment]
Hey @Cotabe @danelsuga @laurenluz if this info was imported to the CRM, do we still need this issue open?

**Comment by laurenluz** [comment]
did we actually end up onboarding any of these projects? I feel like a lot of time was spent on coorindating this... many weeks in fact - any success metrics?

if not we should discuss how to make this more impactful in the future.

Less time in for more results out. @Cotabe @danelsuga

**Comment by danelsuga** [comment]
It looks to me @Cotabe got a lot of folks out of this actually. He can confirm. It can probably be closed as well, in any case. Await his response. :)

**Comment by Cotabe** [comment]
Yes @danelsuga @laurenluz 

When I did the update last update 10 out of the 34 were on the platform. I think the results were not bad. But I also don't think that investing more time will yield significantly better results.

Here is a spreadsheet with info about the outreach and results https://docs.google.com/spreadsheets/d/1AzbwuFfDXqnFXCOyChlDtHWkb-BxM9HSj8FbfuX8uIQ/edit#gid=0

I consider we can close this issue

**Comment by laurenluz** [comment]
10/34 is pretty good! they were great projects, I hope they get some funds on the platform! Thanks everyone for the work.
