### ISSUE TITLE
Automated email to projects to remind them to send tax receipt

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#693]
Donors to registered charity/non-profits could be eligible for tax reductions (as well as GIVbacks) to verified projects. This tax saving can be significant. This issue is to investigate if this is important to donors on Giveth. If so, can we send them an automated reminder email after they have donated to contact the project to ask the project to issue a receipt for tax purposes?

**Comment by clara-zi** [comment]
@melodysongq would you like to take this one?

**Comment by melodysongq** [comment]
Sure

**Comment by laurenluz** [comment]
It is not within the scope of Giveth to advise/support with tax receipts. please provide future context as to the thinking here before actually proceeding to draft an email.

**Comment by melodysongq** [comment]
@laurenluz  Giveth should not provide tax receipts.  

However, if the donor is in the US or Canada, they should be informed that they are entitled to a tax receipt from the registered charity (if the project is registered) they donate to even on Giveth.   

They should pursuit that by contacting the project themselves if they are interested to take advantage (in addition to the Giv backs - this doesn't contradict with tax laws in those two countries as the Give backs are not from the charity but from the platform, this doesn't come in the way of the donor enjoying the tax receipting benefit directly from the charity).   From a donor-centered perspective, we feel that it's important to let them know.  

From a project perspective as tax receipt has been so far the top incentive in US and Canada especially since the crypto gains are sometimes asymetrical.  Our group feel that it would make the donor experience a little better by informing them that giving on Giveth does not "prevent" them from benefiting but rather they are benefiting from both incentives.   If Giveth is donor-centric, we may want to make this information available as a resource.

**Comment by laurenluz** [comment]
I think that sending an email to projects to ask them to create some kind of official donation receipt for their donors presents a lot of challenges.

A lot of projects wouldn't even know where to start with that.

What do you think @WhyldWanderer ? @GriffGreen ?

**Comment by laurenluz** [comment]
as per comms call:
- in our terms of use, it explicitly states that we do not facilitate tax reciepts
- could add to create a project flow "if you are a registered 501c3, reminder to provide tax receipts to donors. - @WhyldWanderer 

both donors & projects could get in trouble for requesting receipt because they recieve something for their donation - @rainerhoell 

it's a huge benefit for donors to get these tax receipts, and in Canada it's not an issue that they get rewards... because the nonprofit org is not issuing the rewards - @melodysongq

**Comment by melodysongq** [comment]
After a discussion with @clara-zi @rainerhoell,  we **r**ecommend not to provide**** any tax-receipt related content through Giveth communications as tax receipt laws and interpretations are different and could result in confusion despite of the intention to attract more donors to the platform.    If everyone agrees, we can close this issue.

**Comment by laurenluz** [comment]
works for me!
