### ISSUE TITLE
Reach out to Luke Flegg from Extinction Rebellion

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#694]

**Comment by rainerhoell** [comment]
Reached out, waiting for response.

**Comment by c0ric0ri** [comment]
@rainerhoell how are things going on this issue?

Is this something that would be moved to the CRM?

**Comment by c0ric0ri** [comment]
@SnakeGH is this something we can close? Can you confirm if it's in the CRM?

**Comment by SnakeGH** [comment]
@c0ric0ri so I coincidentally just started reached out to Extinction Rebellion at the end of August, as they were a project on our Gitcoin outreach issue and got in touch with Tatiana from their Twitter account who said she would get me in touch with the right team member but then the convo went dark. 

@rainerhoell if you have Luke's direct contact information, I'd love to reach out or please add Luke to Hubspot under the ER profile please and continue your convo

Otherwise, @c0ric0ri that is the latest on my end, how do you want to proceed with this issue?

**Comment by c0ric0ri** [comment]
@SnakeGH @rainerhoell I would like to close this issue now as it has been stagnant here for several months. 

I will move it to Done for now and I'm ok with leaving it there for a couple days before closing it until you've clarified that it's in Hubspot - does that work?

**Comment by c0ric0ri** [comment]
@SnakeGH @rainerhoell closing this issue today!
