### ISSUE TITLE
Add AMA invitation to emails

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#727]
- [ ] Project verification (approved) email

- [ ] Project verification (rejected) email

- [ ] Project created email

Include
 - link to Discord
 - link to Calendar invite
 
 **Please leave screenshots or draft here for review before publishing**

**Comment by Cotabe** [comment]
What about adding this text at the end of the emails.

"Do you have questions or comments? Go to the [Project Onboarding Channel of our Discord ](https://discord.com/channels/679428761438912522/808032358933856306)to find the answers or join the Giveth Community AMA & Orientation session on Wednesday's 2pm CST you can find the event in your local time in [our calendar.](https://discord.com/channels/679428761438912522/979783352783609866)"

**Comment by Cotabe** [comment]
Do you have questions or comments? Go to the [Project Onboarding Channel of our Discord ](https://discord.com/channels/679428761438912522/808032358933856306)to find the answers or join the Giveth Community AMA & Orientation session on Wednesday's 2pm CST you can find the event in your local time in [our calendar.](https://discord.com/channels/679428761438912522/979783352783609866)

**Comment by clara-zi** [comment]
I think getting the calendar link to point directly to AMA call is best - tested link and it seems to be pointing there now. 
I like the add of 'connect with us' too.

**Comment by WhyldWanderer** [comment]
Agree! I think this looks great!
And yes.. i think that the calendar link should link directly to the event here rather than the discord channel:
https://calendar.google.com/event?action=TEMPLATE&tmeid=ZTgyanZvNjMzYnB0bHJvODRraGFwdDdxbDhfMjAyMjA2MjlUMTkwMDAwWiB3aHlsZHdhbmRlcmVyQG0&tmsrc=whyldwanderer%40gmail.com&scp=ALL

**Comment by Cotabe** [comment]
Thanks everyone.

@NikolaCreatrix I like the suggested changes.

@clara-zi Thanks for the input. But I got confused with all the links. Which link did you mean?

@WhyldWanderer Maybe we could add both Discord and Google calendar just in case. Because when I follow your link it takes me to my calendar and says the event could not be found. 

This is what I think for each link:
Discord. I added the calendar link because the specific Orientation call is being added consistently and it makes no sense to link to a previous message. Maybe we can be more detailed to help them locate the event. 

Google. The current link is not working for me. Would be great if they could add only that event. Not all the Giveth public events, that can be a bit overwhelming. I like that they can set a reminder. But if they are unfamiliar with Discord, it can be more frustrating to join Discord just when the call is starting and have trouble with it. Does the google event has a quick explanation of how to connect to a Discord call?

**Comment by WhyldWanderer** [comment]
weird @Cotabe... it works for me and goes only to that event... 
Is anyone else havng trouble with it?

**Comment by c0ric0ri** [comment]
@WhyldWanderer @Cotabe are we all set to close this issue? Or are we still waiting on something?

**Comment by c0ric0ri** [comment]
@WhyldWanderer @Cotabe please update this and close the issue, thank you!

**Comment by NikolaCreatrix** [comment]
Hi team, yeah I just went to double check and this seems to be implemented already. This is how the email looks like after minor edits @WhyldWanderer and I did recently. As you can see the email already does have the AMA invite in it.

This is what the project owner receives when their project gets published and listed.

![image](https://user-images.githubusercontent.com/100084867/197845851-46007244-fe67-44d1-b6f0-5b98846b6a82.png)
![image](https://user-images.githubusercontent.com/100084867/197846220-f3124fa7-47ac-43e1-b66f-6c4c1db4af38.png)

So this issue can be closed @c0ric0ri
