### ISSUE TITLE
Project Owners 101 Video: Walkthrough of setting up a project

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#734]

**Comment by MoeNick** [comment]
Yeah we just add the functionality today due to problem of receiving some donations foe exchange addresses on Gnosis (we don't have xDai network anymore) 
So right know entering both addresses is required, we can change it in backend manually (if PM don't want to raise fund in any of them) but the ux-flow is in-progress by @mosaeedi to add a seamless active/deactivate network in this form.

**Comment by scottbenjd** [comment]
@ahmadabugosh @laurenluz @c0ric0ri 

[Here's the rough version of the project setup video](https://drive.google.com/file/d/1nyZgswEbmKKdz1R-SCt3P5wVo4qdwuaV/view?usp=sharing)
There are a couple specific points I could use some feedback on + any other changes you think would improve the video.

1:35 - add profile picture upload? I skip it in the video. but could be a fun addition. Maybe use a meme. Anyone remember "good guy greg"? Giveth Greg?
1:40 - "revelling in the warm glow of digital fireworks and achievement" - too much?
1:52 - reading guidelines necessary?
4:50 - different addresses by chain - do we need to update or will the simple version be sufficient? 
5:22 - visuals for listed/unlisted?

**Comment by scottbenjd** [comment]
Moving back to in-progress since I'm working on adding the multiple addresses part. Any feedback on other parts is welcome!

**Comment by MoeNick** [comment]
@scottbenjd pls hold on, we soon have another release with the latest changes on this page. 
Appreciated it @ahmadabugosh,  if any comms team members attend our daily sync call to be aware of these changes. Usually, we have @WhyldWanderer or @laurenluz  
However, for your information, this part should be like this, which @RamRamez is working on it now and we have it on stage this week.
![image](https://user-images.githubusercontent.com/80677512/179901864-41820e98-01c3-41a2-b67f-57ceff0d696d.png)
![image](https://user-images.githubusercontent.com/80677512/179901885-020dbe94-6a8a-4bb4-8dcd-2c36778eb02a.png)

**Comment by MoeNick** [comment]
Now it's merged on [Staging](https://staging.giveth.io/create)

**Comment by MoeNick** [comment]
Please be aware the categories part is also going to change, but I guess we can not have in sooner than 45 days from now. If you guys are interested in what's going on, pls take a look at [it's Epic](https://github.com/Giveth/giveth-dapps-v2/issues/452). Also, [this one #1125](https://github.com/Giveth/giveth-dapps-v2/issues/1125) is related to this exact form which is waiting for @mosaeedi to complete the design and UX

**Comment by scottbenjd** [comment]
Thanks for the update @MoeNick. No worries. I will wait to make those edits.

**Comment by ahmadabugosh** [comment]
hey @scottbenjd any updates on this? Let me know if I can help

**Comment by scottbenjd** [comment]
@ahmadabugosh slow going but have made progress on the fundraising 101 video. made a comment on that issue.

**Comment by c0ric0ri** [comment]
Thanks @oyealmond for jumping in on this one!

**Comment by oyealmond** [comment]
@ahmadabugosh [Found this very complete draft](https://drive.google.com/file/d/1nyZgswEbmKKdz1R-SCt3P5wVo4qdwuaV/view ) . 

Is this person still interested in doing the video? If not, I could just re do with my voice using the same script just adding the  multiple recipient addresses features. 

https://github.com/Giveth/giveth-planning/issues/882#issuecomment-1273659618

**Comment by ahmadabugosh** [comment]
Hey @oyealmond I think this one is fine (no need for your help), I can add a voice over or popup that explains the multi address section

**Comment by ahmadabugosh** [comment]
This is video is ready for review @WhyldWanderer @NikolaCreatrix https://youtu.be/zOYo-ZtChY4

**Comment by NikolaCreatrix** [comment]
Great work @ahmadabugosh compiling bends and your work! 

1# One thing that confused me was - when you come in with that wallet address prntscrn and start talking about recent changes - it is not clear how you have arrived at that little window printscreen. can you explain in there what is that we are looking at? Just because it doesn't look quite the same when I go to create a project...

![image](https://user-images.githubusercontent.com/100084867/197264038-493c1a38-e617-46dc-8533-3719ca9b8a86.png)


2# Also one more important thing to mention - "If you have multiple projects, you can use one address only once which means you would have to set up a unique address for each of your projects." something like this...

**Comment by ahmadabugosh** [comment]
Thanks @NikolaCreatrix great feedback! 

I just edited both of those points (added video of the platform and added more voice over about not being able to use the same address for multiple projects). Let me know if this is better: https://youtu.be/sOtvDCAqV88

**Comment by NikolaCreatrix** [comment]
So much better and clear, the transition feels also pretty smooth! Excellent work @ahmadabugosh :) I think it's good to GO!
