### ISSUE TITLE
Soundbites from ETH Barcelona

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#760]
For twitter/social media shares.

Lauren - panel
Griff, Willy, Tam, Livia - talk

**Comment by danelsuga** [comment]
Notes: https://docs.google.com/document/d/1IFuHIl0FvzyNYn7XCEYLZ5AhJDn8Jy77dGJ59cY2LRk/edit

**Comment by danelsuga** [comment]
Lauren panel: Regen Mentalities https://youtu.be/dT8ls6OONsY?t=21318

**Comment by c0ric0ri** [comment]
Thanks @danelsuga i'll talk Griff's to start because it's relevant to another issue I'll also work on

**Comment by danelsuga** [comment]
Great!

**Comment by c0ric0ri** [comment]
Transcript for Griff's talk (Crypto Anarchist Dream): https://docs.google.com/document/d/1zOk1ck4pk-wZFniKlm-SJNt19g56Vdxa4bNJxnZBXTQ/edit?usp=sharing

**Comment by c0ric0ri** [comment]
Just need time stamps mentioned here in the issue + the transcription of the 30s-45s clip:

Willy @clara-zi 
Lauren's panel @SymSL 
Griff's SBS Talk @Cotabe 
Tam @scottbenjd 
Livia @scottbenjd

**Comment by scottbenjd** [comment]
@ahmadabugosh  Here are two for Tam's presentation.  I think both could work as really short clips if you stop at the second time.

Reimagining profit to create a solarpunk future
- 52:11
If you are at this conference, you know what I mean by “solarpunk”, but for the benefit of those who may be watching at home, solar punk is the ecological and human centric vision of the future, an option we still have. When we think of profit in terms greater than what the market will pay for it, we move in the direction of solarpunk, the ecological and human prosperity. 
- 52:39
We see profit in ways that reinforce principles of sustainability, environmental impact, cultural knowledge, and community solidarity. If we are successful, the word profit associated with monetary gain may be an archaic relic of the past. 
- 52:57


What is a commons?
- 1:00:15
Very simply,  a commons is a resource, plus a community and a set of rules. The rules are social protocol for conduct in the commons. And a commons does not exist with just one or two of these. The resource and active community and the rules together create a sustainable commons. In a commons, the community treats a resource as a shared wealth. In a commons, members talk about stewardship of a commons as opposed to ownership. There’s no commons without commoning, the act of participation of a community. 
1:01:00
Thanks to the groundbreaking work of Elinor Ostrom, David Bollier, Silk Helfrich, and many others, commons are now being seen as a viable alternative to capitalism, one which puts the wellbeing of the planet and humans above financial gain…puts the well being of the planet and humans above financial gain… that is so solar punk. 
- 1:01:28

**Comment by danelsuga** [comment]
FYI here is the link for Griff's nearly same talk at ETHCC. 

https://www.youtube.com/watch?v=LxyH9u4EBzw

**Comment by clara-zi** [comment]
Willy's talk on DAO scalability. Taken from (https://ethbarcelona.com/livestream) Forest Stage, Day 3.

Soundbites: 35:30 Scalable communities, so key, so awesome!

35:51: “Why should I, as a Community member care about your community? I want to get involved’… and if you get this right, you'll find, like, Giveth does it so well, it's “Building the Future of Giving” there’s people all around the world, in this room, who are aligned with that mission and they hear about it and they’re, like, “What!? I can just come join the Discord and like, help out with ‘Building the Future of Giving, like, I've been dreaming about this for years! …And then I can get some GIV tokens and be an owner in this?”. 
It's mind blowing and it's so powerful!”

36:55 “Are community members building relationships? This is so powerful, like I love to see community members come in and meet each other and build relationships because that makes it so sticky. Right. And we're creating these bonds as family, this network. Are they learning? Are they earning? Are they growing? And rule number one: are they having fun? We always have a lot of fun at Shapeshift and Giveth DAO…….., (need to edit and cut here) so that’s vertical scaling!”

Transcript:
“Alright, scalable communities, so key, so awesome. I think there's a lot of different ways to scale a community, but I think there's kind of two core ingredients that work really well. Just start by focusing in. And the first, of course, is dank memes. You gotta have the dank memes, right? I don't just mean cartoons, those are great, but higher level than that, right? Like what is the reason that your DAO exists? What's your community about? ‘Why should me…? Why should I, as a Community member care about your community? I want to get involved’… and if you get this right, you'll find, like, Giveth does it so well, it's “Building the Future of Giving” there’s people all around the world, in this room, who are aligned with that mission and they hear about it and they’re, like, “What!? I can just come in the Discord and like, help out with ‘Building the Future of Giving, like, I've been dreaming about this for years! …And then I can get some GIV tokens and be an owner in this?”. 
It's mind blowing and it's so powerful! So get those memes right, right? ……….. And of course, you gotta have a dank community experience, right? Once people find out about your community, how can they actually get involved? What does that experience look and feel like to somebody who's just discovered about your DAO? Can they find what they're seeking quickly? Can new community members contribute and then get rewarded? And if you can just nail these top pieces like that is so powerful. Just the funnel of people finding out about your DAO, coming in, getting welcomed and then being able to contribute and add value and then get rewarded and become owners. Oh man, that's a flywheel ready to go! Are community members building relationships? This is so powerful, like I love to see community members come in and meet each other and build relationships because that makes it so sticky! Right? And we're creating these bonds as family, this network. Are they learning? Are they earning? Are they growing? And rule number one: are they having fun? We always have a lot of fun at Shapeshift and Giveth DAO…….., so that’s vertical scaling".

**Comment by SymSL** [comment]
Lauren panel: Regen Mentalities https://youtu.be/dT8ls6OONsY?t=21318, Forest stage Day 1
Loved so much here - well done Lauren!!

06:08:38 - 06:10:06

“I think one of the roadblocks that I run into with a lot of people that are in the altruism space is the idea that profit is bad, that profit is against altruism or profit is against doing something good for people, and I think what's required is actually a shift in mentality, its a paradigm shift. Its changing the way we think about providing value for the collective, from being something that requires sacrifice to something that could actually give rewards to everyone. I mean, Giveth is really focused on this mission. Right now, public goods are being provided by governments and non-profits. Governments require taxes in order to create these public goods, and non profits require donations. In both cases, somebody's having to sacrifice. People need to give up their income or put a tax on goods and services in order to fund their governments to provide things like roads. Or people need to donate and expect nothing in return because they care about this environmental cause. And this is, its an okay system, I mean we have public goods… its okay, but it’s really not great, and I think that we could have better public goods, we could have better value being built in society if we actually had it be more profitable for people involved."

06:10:06

So Giveth is a donation platform right now because its really about meeting people where they’re at right now. So its a donation platform - you can give to a verified project and donate to them in that way. But we want to start shifting this mentality so we built a system called GivBacks. When you donate to a verified project, you actually get Giv Tokens. And 100% of your donation goes to the project, and the people donating get Giv Tokens, so they actually get something back for the donation. Its like the first step on the mentality shift. You can actually get something for giving. You can get something for providing value to society. For providing capital to a public good. 

06:10:43

And the long term as I kind of mentioned in my intro is that we want to basically turn these non profits into DAOs with their own token economy so that instead of having to donate and give away, you can actually invest, you can actually invest - you can actually invest in the project. I mean if you cared about Giveth, you could donate to giveth or you could buy the Giv token which helps the economy, the ecosystem, and then ultimately you become a shareholder in the way that public good is being provided. 

06:11:15

I think that the roadblocks along the way are really just the shifting mentality from “Oh, in order to do good I must, you know, give of myself and sacrifice. I think even just the personal dynamic of a lot of people just being over givers, like, over-giving and being like “Oh no, I don't deserve anything back” but actually this is an interesting shift - when you give, you actually do receive. You’re giving energy and receiving energy back, by adding value to things. So I think public goods are such a pure thing, everybody can benefit from them and everybody can enjoy them, and if we can create systems where you support public goods and then everybody involved can profit and can experience that, that becomes something okay, then I really think that we can start to shift this entire thought process.”


6:35:00
I think projects that have really strong mission vision values that attract people when people come into the DAO and into the ecosystem, they [new people] already kind of orient themselves to that. At Giveth we have values of Decentralisation, Altruism and Community, and under each of that, there's a subset of what that means. Its our MVV doc that we share with people in hopes of inspiring them. So whenever anyone comes into the ecosystem they’re like “Yeah sure this is a donation platform but its also a DAO and it has a specific set of values, and then getting involved with this DAO, its like reading and understanding and becoming a part of this movement and part of this value system.”

**Comment by scottbenjd** [comment]
The link for Livia's talk isn't working for me. [https://youtu.be/eyAcJb7O7K8?t=24720](https://youtu.be/eyAcJb7O7K8?t=24720) Anyone have another link to Livia's talk or even the day + stage?

**Comment by scottbenjd** [comment]
Reputation Panel - Livia 

[https://youtu.be/yoWn-hDG7-Y?t=24264 ](https://youtu.be/yoWn-hDG7-Y?t=24264 )
6:44:25 - 6:46:04 - Institutional reputation an legitimacy
Who is the reputation issuer? Who are the institutions that provide legitimacy to the reputation that is being created. I feel like we don’t think so much about that because then thinking about legitimacy is a whole rabbit hole on its own. Who has legitimacy now? Academia, the state, the church. For the majority of people, these institutions provide legitimacy to the reputation they are building. That can be a modular reputation, like someone who has reputation in academia will probably have reputation in all of these other circles as well. I think the challenge now is that the organizations we are creating they are not coming from this legacy system. They don’t have this legitimate perspective to the rest of the world yet, and not even to each other sometimes. How do the projects we work on create reputation among each other for the reputation of an individual within them to be legitimate in the spaces where they circulate. 

[https://youtu.be/yoWn-hDG7-Y?t=25994](https://youtu.be/yoWn-hDG7-Y?t=25994)
7:13:15 - 7:14:14  - Importance of value diversification and inclusion in reputation protocol
 I would add that on top of being based on people work, also being based on the ways people relate with each other. The ways in which relationships happen in a community are so important to the value they are adding. Also to have value diversification. The more values we can map the more we can diversify the legitimacy layer. Having more entities that can offer legitimacy and having more values that are considered in reputation in the big spectrum of being a whole human being not just what I produce but who I am, how I behave, how I treat people and how I treat myself.

**Comment by c0ric0ri** [comment]
@ahmadabugosh we're ready for review here!

**Comment by ahmadabugosh** [comment]
Hi @c0ric0ri and team thanks for putting these together! I created soundbites for them here: [https://docs.google.com/spreadsheets/d/1KoVy2Ttvo3Q3GxnFx-6pNS01VfvgjDok95aNY9JKTik/edit#gid=0](https://docs.google.com/spreadsheets/d/1KoVy2Ttvo3Q3GxnFx-6pNS01VfvgjDok95aNY9JKTik/edit#gid=0)
(at the bottom of that sheet is also a folder to download the raw videos). 

Did anyone do Griff's SBS talk? I didn't see it anywhere

**Comment by c0ric0ri** [comment]
Thanks @ahmadabugosh ! Didn't have the link for Griff's SBS talk at that point last week, but it's on my to-do's for this week!

**Comment by danelsuga** [comment]
Griff's SBS talk transcript by Cori: 
https://docs.google.com/document/d/1GwfIic_IuC7zcOB78L8XIaHEzYMJbHjgi0f5UhnHGqA/edit

**Comment by ahmadabugosh** [comment]
Thanks @danelsuga ! Is this related to the soundbite task? Are there any short quotes you recommend I make a video with or is this more for the article?

**Comment by danelsuga** [comment]
I didn't know if this task was complete actually. I had gotten info from @c0ric0ri for the article that she had worked on the transcript for the talk, so I just wanted to paste it here since the last correspondence I read was that you were asking if anyone had done it. 

In short, I was just cleaning up/connecting the dots. :)

I haven't gotten around to the article yet. I think I need to sync with @c0ric0ri to see how that stands and also to see if she's got soundbites. I think she may have been doing both or neither. 🤣 As she's sick, let's wait for her comments next week.

**Comment by Cotabe** [comment]
I got a quota that I liked from my own interview. We might add it as a soundbite:

"We have a motto that we are building the future of giving... & for us the future of giving is turning donors into donors and impact investors with the same money that they donated.

And we are turning makers (people that are doing for good projects) from people that ask for money to do great things in the world to people that can sustain an economy that bring sustainable impact in the world... 

& I think that's the future of giving"


https://www.youtube.com/watch?v=s7ej6lRjhTo
45:10 to 45:48
