### ISSUE TITLE
Questions from ETH BCN

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#761]
What were people asking? What issues did they run into?

We want to collect a list of questions and then can use this to add to our FAQ, or improved the flow.

- what is giveth's mission?
- why do you use gnosis chain?
- how is giveth sustained/revenue?
- "verified"... people aren't sure if this means they are legit, or if they are just givbacks projects. We don't want to give the impression that other projects are not legitimate.

@NikolaCreatrix is down to ask others for the questions they received! we want feedback from @Cotabe @freshelle heather, etc.

**Comment by freshelle** [comment]
These are some of the questions asked from me:

- where does the "money" come from for paying the GIVbacks?
- what is your business model?
- what is the process of verifying the projects?
- do you only accept crypto?
- how do project owners convert their crypto to fiat?
- what can you do with the GIV tokens received from donating? (follow-up question: can you sell it or donate it back?)

**Comment by NikolaCreatrix** [comment]
These are questions I collected from Cotabe, Rodri, Zepti, and Heather:

- What are tokenomics?
- How to know which projects give them tokens when they donate?
- How do we sustain ourselves?
- In which networks can people donate?
- How is the Giveth token designed?
- Does the Givtoken have a treasury?
- How are you solvent as an organization?
- How do the projects get the money, like converting crypto to fiat?
- What type of non-profits use your platform? Where are they located?
- When donating in a specific currency, for example, ETH, DAI, or other, which currency is the one that the owner of the project receives?
- How to verify a project and what requirements were necessary to register a project.
- Once the donation was made, does Giveth take any action with this money before it goes to the project?
- How Giveth's economic model works since we do not charge fees and at the same time we give back to the donors in GIVbacks. How was this possible?

**Comment by SymSL** [comment]
I had similar questions to the above & thought it would be great to communicate some of the vision from Griffs talk as content pieces too. 

Another question I've gotten after ETH BCN is from a project signing up, they had a few questions along the way so would be good to do a very basic step-by-step article

**Comment by c0ric0ri** [comment]
@NikolaCreatrix are we still working on this? If not, would you please close this issue with a link to the final work (if needed)?

**Comment by NikolaCreatrix** [comment]
Hey @c0ric0ri I feel like my part was to gather the questions, so thats done. Now we have all the questions, but the final work IMO was to actually answer those questions and share with the giveth audience in some way, and that I am not sure, was decided?

**Comment by c0ric0ri** [comment]
@oyealmond @danelsuga let's circle back to this for Giveth Essentials

Can you please add issue 872 here?

**Comment by danelsuga** [comment]
#872 Representing Giveth External Comms

**Comment by oyealmond** [comment]
Ordered the questions, and highlighted the most repetitive ones in the How to represent Giveth guide.  - 
I answered some of them - needs to be reviewed  @danelsuga @c0ric0ri 

https://docs.google.com/document/d/1pzVEZGMLA4EgA892TIv5aTxm2aZ0ItmkxTFNwEjgjRQ/edit?usp=sharing 

Excellent to have this issue to include the Most asked questions! Ty @NikolaCreatrix !

**Comment by NikolaCreatrix** [comment]
Excellent work preparing the next essentials session. Looking forward to it!!! TY @oyealmond

**Comment by c0ric0ri** [comment]
Hey @oyealmond @NikolaCreatrix can we close this issue? It looks like we transferred all the info, right?

**Comment by oyealmond** [comment]
Yes! All the questions got answered. 
https://docs.google.com/document/d/1pzVEZGMLA4EgA892TIv5aTxm2aZ0ItmkxTFNwEjgjRQ/edit?usp=sharing 

We can close. Ty @c0ric0ri !
