### ISSUE TITLE
BitDAO proposal tweet thread

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#767]
We need to emphasize this! It's a huge opportunity for Giveth to get funding.

https://twitter.com/thegrifft/status/1547621581102272512

**Comment by laurenluz** [comment]
Yass — 07/19/2022
I was wondering if we should make it a thread and add some info in the comments as well. so something like:
1/ #Giveth and #BitDAO are incredibly aligned in vision as we both see the opportunity in the public goods space – $10.5 trillion was spent only in the US on public goods paid by taxpayers, donors, governments, nonprofits who are all sacrificing and getting nothing in return. Giveth is here to build solutions to make this industry sustainable and produce regenerative value.
2/ Giveth long-term vision is to make it easy for impact projects to launch their own micro economies. Giveth x #BitDAO partnership would help us to evolve Giveth donation platform into and impact investment platform where projects and DAOs are using GIV token as collateral for their micro economies.
3/ Since launch Giveth has built many public goods and tools for Ethereum ecosystem to eventually bring more projects into the web 3.0 space: Minime Token contract (used by Aragon, Status, etc and forked by Compound). Organized the ScalingNow! Conference to address Ethereum Scaling issues in 2018. Launched the common stack which created the token engineering commons (first public goods focused economy). Designed our internal reward system called Praise which is a perfect tool for DAOs to reward and promote good work in the community. These tools have helped foster and grow our DAO management and we'd love to cultivate it through our partnership with #BitDAO.

**Comment by c0ric0ri** [comment]
Notes from @Cotabe : 

Right now, engagement in the forum is the thing that is supposed to move things forward.

Yass made some research & realized that most of the projects that got funding were co-authored by BitDAO investors. So we are trying to see who to engage to move it forward.

I will work with Yass on this and report back.

Anyways, here are some notes from the Twitter space:

GRIFF
I see Bit DAO and Giveth aligned
10 T opportunity on public goods that is currently taken from tax contributors and non-profit donors.
Vision: Turn non-profits into DAOs not with business models, but with economic models. Microeconomies.
But that’s not where we are starting, we are meeting NGOs where they are. We have created the best donation platform in the world:
Any project in the world can raise crypto on Giveth with ZERO fees. All the money from the donor goes to the project anywhere in the world.
But even bigger than that we reward donors with up to 75% of their value back on GIV. So we are incentivizing (paying) people to donate. So we have effectively created a worldwide tax break sort of system for givers to donate to directly to projects all around the world.
We have already taken Token Engineering Commons into a tokenized microeconomy and this year we will do that for Grassroot Economics.
We are seeking to raise 2-3 Million by the Swap of GIV tokens to stablecoin to diversify our treasury in the bear market and pay salaries.
We are also about to launch an Angel Vault with ICHI, which we consider one of the best liquidity solutions to protect from the downward volatility of the market. So it’s a nice time to make an investment.

Questions? Are you charging non-profits to get onboarded? No, not at all. Giving Block charges about 5K for onboarding. We don’t and we pay givers for their donations. We aim to keep it accessible for non-profits to get onboarded and we want to educate them to stay on web3.

How do you make money? We use economic strategies rather than revenue-making strategies. So we are dogfooding our system. So we are working on creating demand for our GIV tokens. Right now we have our farms and the speculative demand for the token. Soon we will be realizing GIVpower, this will give people the power to lock tokens behind projects to boost them and at the same time multiply the APR on rewards. This will help turn donors into investors and create for the first time a win-win scenario for donors. But the real demand for the GIV token is once we start turning non-profits into microeconomies and using an augmented bonding curve collateralized on GIV token for their microeconomy.

There is VALUE in creating VALUE FOR SOCIETY.

We need to give people incredible talented people upside potential for innovating in the public good space and that's how we're gonna change the world.

We would like to get an insight on how to best way to craft a proposal that addresses everything that is important for the BitDAO members…

DREA: We have these weekly polls that we've put out in the meeting. You can look at previous polls about what the community wants to see as investors and it's we'll send out links for that, but you can also see it on the A embassy channel.

A few other questions in general a very positive attitude.

**Comment by laurenluz** [comment]
1st thread is out: https://twitter.com/Givethio/status/1556678732911452161
