### ISSUE TITLE
Angel Vault documentation 

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#775]

**Comment by Cotabe** [comment]
GM!

Here is draft for the documentation: https://docs.google.com/document/d/14Fd-GzbH8WOLyfIiXDvioWaRs3Sh9dMXc2wEdQ5KrYw/edit#

Maybe @laurenluz or @danelsuga can check it and correct what might be needed. 

:)

**Comment by danelsuga** [comment]
Thanks @Cotabe ! Will do!

**Comment by laurenluz** [comment]
Hey @Cotabe ! love that you took a lot of this from the forum post, but since this is no longer a proposal, it is a documentation, we should explain what has happened, how it works, how to use it.

We should say:
- oneGIV can be minted using 100% DAI *here*(link). You can also get oneGIV by traiding on Uniswap*(link).
- You can participate in the program by getting oneGIV & then providing liquidity(here). Note that you are providing liquidity in a uniswap v3 pool, and when you withdraw you may get some part GIV & some part liquid. *This is not single-asset staking".
- You can earn rewards in GIV by staking you LP here(link to GIVfarm).

Do you get the idea?
It would be great it you took parts of the forum post and made it a simple list of points like that. Focus on the "what"... hard, decided facts.

**Comment by laurenluz** [comment]
Thanks @Cotabe for getting this started. I picked up from where you left off.

First draft, almost ready for review is here: https://docs.google.com/document/d/1viCwIugLW9RaYDOQbTlDoQ_3afKmruY7eYrldFK8d1w/edit?usp=sharing

@danelsuga I'll just get you to review it when it's done.

**Comment by laurenluz** [comment]
@danelsuga @divine-comedian @c0ric0ri @Cotabe 

Please review:
https://docs.google.com/document/d/1viCwIugLW9RaYDOQbTlDoQ_3afKmruY7eYrldFK8d1w/edit#

**Comment by divine-comedian** [comment]
Reviewed! needs some clarifications and a bit more info in certain places

**Comment by laurenluz** [comment]
@divine-comedian let me know when this goes live, we need to add the link to the Angel Vault UI

**Comment by laurenluz** [comment]
https://docs.giveth.io/angelVault/
