### ISSUE TITLE
Video Walkthrough for NICE Token

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#777]

**Comment by c0ric0ri** [comment]
Pending when the frontend is live - @divine-comedian you can let us know

**Comment by divine-comedian** [comment]
> Pending when the frontend is live - @divine-comedian you can let us know

this is live! you may proceeed

**Comment by ahmadabugosh** [comment]
Hey @c0ric0ri @laurenluz, I made this video for the $nice token: [https://youtu.be/MpYET3a3qEo](https://youtu.be/MpYET3a3qEo) Let me know if you're ok with it, and we can add it to the donor course playlist

**Comment by laurenluz** [comment]
Hey @ahmadabugosh - thanks for putting this together! Some feedback:
- The purpose of $nice is to diversify the Giveth treasury w/ stablecoins so we can keep building the Future of Giving
- $nice gets you sweet benefits
- one is that you can buy Giveth swag
- another is that you will be added to the pre-mint list for the Giveth PFP collection if you donate over $100 (we're going to annouce that in a tweet next week)
- another is that you will be eligible for a POAP if you donate above some donation threshold (I don't remember the exact details)
- there will likley be more benefits in the future

You explained very clearly how to get $nice, but I think starting with the swag shop makes the order weird. Like the highlight feels like swag, rather than $nice. I think emphasizing that $nice is our gift to you as thanks for helping us be more sustainable (but said better than that) is important... and then saying that swag is ONE benefit, but there are and will be others.

Maybe @divine-comedian can provide a bit of feedback too.

**Comment by laurenluz** [comment]
Here is the upcoming $nice thread btw: https://docs.google.com/document/d/1ceK6_LxWYjRfwbegHNpPWsgwA4It-U_vEBk-yclnHA4/edit

**Comment by divine-comedian** [comment]
Lauren hit most of the major points, from a tokenomics side there's two interesting points

- We have our first buyback mechanism for GIV using 50% of the DAI received to buy back GIV
- We create DAO-owned liquidity by pairing bought back GIV with the other 50% of the DAI received

**Comment by ahmadabugosh** [comment]
Thanks for the feedback @laurenluz & @divine-comedian! Here's my take 2: [https://youtu.be/NV3kfo2YvoQ](https://youtu.be/NV3kfo2YvoQ)

**Comment by laurenluz** [comment]
it's awesome!! love that presentation style thing. great work @ahmadabugosh , I think unless mitch has objections, this is good to go!

**Comment by laurenluz** [comment]
@c0ric0ri it would be cool to use this, once it's officially up, in one of the tweets you're doing about $nice.

**Comment by ahmadabugosh** [comment]
Hey it's live @c0ric0ri https://www.youtube.com/watch?v=NV3kfo2YvoQ

**Comment by c0ric0ri** [comment]
https://twitter.com/Givethio/status/1565379302568378372?s=20&t=fKxCtfV1465VziCIGKonFA
