### ISSUE TITLE
Video Walkthrough for GIVpower Launch - not blocker for launch, Dec 15

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#778]

**Comment by laurenluz** [comment]
Short video walk through of how it works to launch October 4

**Comment by c0ric0ri** [comment]
@Cotabe would be great if you can set up a script to review!

**Comment by Cotabe** [comment]
@laurenluz @c0ric0ri 

Is this the site to test GIVpower & from where from draft the walk-through video script https://givpower.vercel.app/ ?

Also what are we aiming for?
1. Very high-level no live demo under 1 min.
2. High level super simple live demo (1-3 min)
3. More detailed (3+ min)

I would go for 2

**Comment by laurenluz** [comment]
@Cotabe 

Use https://giveconomy.vercel.app/

And I would go for 3.

The goal is to walk people through how to use GIVpower... stake & lock GIV to get GIVower... use it to boost projects.

I wouldn't get into edge cases like what happens when a verified project loses it's verified status (for example), but a step-by-step demo of the entire user flow. The purpose is to have this as a compliment to our documentation (though not showing nitty-gritty the math). Think of it like a how-to.

**Comment by Cotabe** [comment]
Here is the first draft of the Script. It's pretty detailed. 

In total it lasts a bit more than 11 minutes. I think it can be splitted into 3 videos to make it more digestible.

https://docs.google.com/document/d/1AR1ExQpfLz88ABjUU7sNbXcl9ecH_JIpewA6KQolrpw/edit

**Comment by Cotabe** [comment]
I reviewed the doc and made a few edits. But I believe its ready for a review @c0ric0ri @laurenluz 

https://docs.google.com/document/d/1AR1ExQpfLz88ABjUU7sNbXcl9ecH_JIpewA6KQolrpw/edit

**Comment by c0ric0ri** [comment]
@Cotabe please update this issue, it's sitting in Backlog

**Comment by Cotabe** [comment]
@c0ric0ri @laurenluz it's on Review/QA now

**Comment by c0ric0ri** [comment]
@Cotabe please make sure to open up access to the doc for everyone to review

**Comment by Cotabe** [comment]
@c0ric0ri Done, sorry about that.

**Comment by c0ric0ri** [comment]
hey @ahmadabugosh do you have some capacity to give this a review?

**Comment by ahmadabugosh** [comment]
This could be a video to record @k3shavgupta @oyealmond
