### ISSUE TITLE
Designs for social media

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#802]
Some variations on the "Building the Future of Giving" for Facebook post.

**Comment by clara-zi** [comment]
![future of giving FB post](https://user-images.githubusercontent.com/100724132/182150900-087ab99c-ca37-40e0-a056-39d271003701.png)
Thanks for this existing design. Could you please use this template with the same wording @rodricastillo9013 to create:
1) Two more designs with the same colour background (ie one with the flowers and something else)
2) When you have these 3 basic designs, please reproduce each of them with two different colour schemes
Thanks

**Comment by laurenluz** [comment]
@clara-zi @rodricastillo9013 just seeing this in my inbox. You could also make these background on a google slide deck (anyone can comment access), and then people would duplicate the presentation & change the text as-needed.

Then whoever is posting could easily just screenshot the slide for the post. I think it would be useful for comms overall.

**Comment by rodricastillo9013** [comment]
hi! how are you! I attach the images, and I have also created a google slides document, with the editable text, so that they can duplicate and modify according to each need! @laurenluz @clara-zi 

Folder:
https://drive.google.com/drive/folders/1pU2o-iaguz2wjTuNgDcg3i4KlFpvkBWP?usp=sharing

Google Slides:
https://docs.google.com/presentation/d/12wg_ovTbgkLGmz8joJDuCMUlHeC134K-kTPQa-01TvY/edit?usp=sharing

**Comment by laurenluz** [comment]
That's amazing @rodricastillo9013 - thanks!

**Comment by clara-zi** [comment]
Thanks @rodricastillo9013 this is brilliant :)
