### ISSUE TITLE
Explainer Video - Project Donation Pg

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-planning#836]
- Overview of the whole process
- “How to donate”
- Timestamps
- How GIVbacks work
- GIVbacks- what happens after donation, how it works
- GIV Calculator- how GIV works

**Comment by ahmadabugosh** [comment]
Hey @MoeNick I was going through the backlog and saw this. Is this the video that you were thinking of embedding on the donation page or having as a popup? 

We have [this video](https://www.youtube.com/watch?v=UlaXjiamHZk&ab_channel=Giveth) here from the Donor series we made earlier. If you're working on this @tropicalmangos , maybe you can make a new version of that video with anything that it's missing (especially since we made some changes to the filtering options on projects since that video was recorded)

**Comment by ahmadabugosh** [comment]
@tropicalmangos no worries!

In that case, can you look at [this video](https://www.youtube.com/watch?v=UlaXjiamHZk&ab_channel=Giveth) and see if anything is missing from what you had in mind? Then if you can make a script (just an overview in a Google doc of what you want to have mentioned in the video) we can bring it up in the comms meeting to find someone to record it.

**Comment by MoeNick** [comment]
If a user with a locked wallet (not-connected) we don't have a clue which network the user is using, so we can't list the supported token list. @tropicalmangos 
If you connect your wallet you can see them.

**Comment by MoeNick** [comment]
This has been provided by Design team, they suggested putting "connect your wallet" in the Donation button (as you can see in your picture)

**Comment by MoeNick** [comment]
just a heads up that this page will be changing soon to add a DOnation Handler to add a top-up donation for Giveth.
