### ISSUE TITLE
Write Medium blog “How is the new Giveth Platform Easier to Use?”

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#84]

**Comment by ForestSoleil** [comment]
2/5/21 Marketing call update:
- Lauren would like more clarity on everything we ARE including in Giveth 2 platform. Needs to understand all the features to make the content really clear. 
- Lauren will get started today. If she has specific questions, she will reach out 1:1 to Mateo, James, etc. 
- 1st draft ready by Tues, Feb 9th.
- Go through copy review process within 48 hours by non-technical AND technical reviewers.

**Comment by laurenluz** [comment]
First draft, needs (a bunch) more work, but open to feedback @Danibelle @divine-comedian @WhyldWanderer 
Let's discuss tomorrow in the marketing meeting

https://docs.google.com/document/d/1CWG-nUS5dS0y9fI_MaILhUkeTJP8YnbCX8Iv9wr8aGY/edit?usp=sharing

**Comment by ForestSoleil** [comment]
2/9/21 Marketing check-in:
- Terminology: Cryptosphere
- Giveth 1 = Giveth TRACE (TRansparent ACcountable Eddition) There was a vote. Dani will double check with team today.
- Plan to move from Beta to Giveth Trace URL(s) --> Update links but include both domains. trace.giveth.io AND giveth.io/trace. Will reroute.
- Would like suggestions of article title: Giveth is Growing (with a sub-title about expanding our portfolio of decentralized applications)
- Forest & Dani will review today.

**Comment by laurenluz** [comment]
Made a bunch of updates, open to review

https://docs.google.com/document/d/1CWG-nUS5dS0y9fI_MaILhUkeTJP8YnbCX8Iv9wr8aGY/edit

**Comment by tommygiveth** [comment]
Um, notes:

Tor.us changes to Torus, not sure this matters.
Also MetaMask has mobile, it works also?

“At Giveth we are committed to building the future of giving based on feedback from you”

Maybe capitalize, underline, or somehow add emphasis to You? Since everything else is bold already?

Discover our Site and Wiki... the _ starts before the word

“We have made it easy for you to give to the social good projects you love!” Change maybe to social-good

Other than those little things, the content seems on point. I guess we are now redefining yet again on names, so hah yea that might change :p

I like that it is to the point with excitement and emphasis where it needs to be. Good read

**Comment by ForestSoleil** [comment]
Reviewed multiple times from team. Copy mostly ready. Will implement Tommy's feedforward, then ready. Lauren will add this to content calendar for distribution.

**Comment by laurenluz** [comment]
This is done now. Reviewed by Dani, Mitch, Ashley, Tommy, James, Mateo, had some feedback from Kay. Maybe too many eyes haha

Some notes:
- need to wait for hype video to be completed to embed into this post (#85)
- this probably makes sense to publish on medium right w public release of giveth.io
- before, we should finalize the name "Giveth TRACE" (or whatever it may be) and move it to trace.giveth.io (or whatever it may be)

https://docs.google.com/document/d/1CWG-nUS5dS0y9fI_MaILhUkeTJP8YnbCX8Iv9wr8aGY/edit

**Comment by ForestSoleil** [comment]
Reviews complete
Content ready
Load to Medium
Wait to upload YouTube hype video until early morning day of publication
Embed to MEdium post day of publication
Magenta to hit go live day of publication

**Comment by laurenluz** [comment]
@Danibelle I already submitted this to be published by Giveth, but reviewed again just now after our comms call... I think it's pretty good. I don't allude to or talk about GIVbacks at all, nor is there much focus on the cool intricacies of our "future of giving" concepts... it's mostly focused at how user-friendly the new DApp is to get people using it... and I think that's a good first step-first message still... What do you think?

Can you give one final read through and thumbs up? Asking you since you have great big-picture vision

https://medium.com/giveth/the-future-of-giving-is-here-d480388a3338
