### ISSUE TITLE
Tweet about new UX for Verification

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#842]
Screenshots below of new UX on adding recipient addresses. They can now have different addresses or not receive the fund in any network.
Compared to the previous state, it's easier for newbies to add addresses, and for advanced users, the can differ and stop any network.

![unknown](https://user-images.githubusercontent.com/106524383/187483335-4fcfd422-2192-4981-b803-5622e9baec67.png)
![unknown1](https://user-images.githubusercontent.com/106524383/187483343-82c63383-83ca-47b3-9a1a-d91b3248b479.png)

**Comment by ahmadabugosh** [comment]
@franculio @oyealmond to take this!

**Comment by oyealmond** [comment]
@ahmadabugosh , one question, this needs update in the Giveth documentation as well? OR only a tweet. 
cc @franculio

**Comment by oyealmond** [comment]
Hey @c0ric0ri ! 
Here's a tweet thread regarding the new 2 updates (verification form and new UX for recipients) . 
@ahmadabugosh @danelsuga is this useful? 
Feel free to modify
cc @franculio 

1) 
🥳 Happy to share some of the new updates of our platform!
🧵 Check this thread around our  new verification process and the new experience for fund receiving. 

[GIF]

2) 
📝 New Verification process is here
🔓 This new process will make verified projects more reliable. We will no longer ask users to provide project name and address again. 

3)
⏺ Find the new Verification button at the right on your project page
✏️ You'll need to verify your email and complete information as wallet address, contact, social media and project milestones. 
✅ You'll receive the status of your verification at the end of the round. 

[add new verification process image]  
4) 
🔑 You can now have different addresses to receive funds in different Networks! 
💡 Now is easier to add addresses, and/or differ and choose networks.

5) 
Select:
✅ Receive funds on Mainnet and Gnosis using the same address. 
✅ Only receive funds on a Mainnet address. 
✅ Only receive fund on a Gnosis Chain address. 

6) 
Share with us your experience using this new features! 
🤔 What else would you like to see on our platform?

**Comment by ahmadabugosh** [comment]
Thanks @oyealmond !

@c0ric0ri to give you context, we discussed in the comms call yesterday that it might make sense to have a regular "platform update" tweet thread where we tell people what new features are on the website, and we thought the two new updates you flagged could be the first iteration of that. 

Also, @oyealmond I think we need to have this on the docs as well, probably added to the [create a project](https://docs.giveth.io/dapps/createproject) section

**Comment by franculio** [comment]
@ahmadabugosh I'm working on adding this to the docs, I can have it ready for tomorrow. Since I don't have access to edit the docs I'll just drop the text in this issue.

**Comment by oyealmond** [comment]
Hey @ahmadabugosh what do you mean to have this on the docs as well, probably added to the [create a project](https://docs.giveth.io/dapps/createproject) section?

**Comment by ahmadabugosh** [comment]
Hey @franculio , yes no worries, when you have it ready, maybe share it as a google doc, then we can have someone else add it to the docs. 

@oyealmond it seems Franco is already working on this, basically just to add it to our documentation section on the [https://docs.giveth.io/](https://docs.giveth.io/) site (which is sort of like a wiki site that is used by people to learn more about how the platform works in more detail)

**Comment by oyealmond** [comment]
ohh got ya. Thank youuu @franculio !

**Comment by franculio** [comment]
Here it's the change for the Giveth Docs: 
https://docs.google.com/document/d/1xQdwa-h2suaTlSeUZonHMUw_TASHKM32c9D9ZapIhB4/edit

Let me know if it's all good and I can update it in the Docs, I found a way to edit the site! @ahmadabugosh @c0ric0ri @oyealmond

**Comment by ahmadabugosh** [comment]
Thanks @franculio ! Can you please change the access to "Anyone can comment" so we can leave feedback?

**Comment by franculio** [comment]
Oh sorry about that, i just changed it! @ahmadabugosh

**Comment by c0ric0ri** [comment]
Hey @oyealmond thanks for the tweet thread, I'm reviewing it now. Please remember to move issues to Review/QA status when they are ready for review. I've also moved the thread to a google doc so that I can review and comment :)

https://docs.google.com/document/d/13Lcun5b81SF04DUhTEKRhrL165rGXcJiMLi7XJ5iqps/edit

**Comment by oyealmond** [comment]
Thank you for moving the issue @c0ric0ri! Will have in mind for the future issues I create. 
Thank you for reviewing the thread!

**Comment by franculio** [comment]
Hey @c0ric0ri ! I checked the docs and this hasn't been updated yet. 

You can find the modification I wrote here:
https://docs.google.com/document/d/1xQdwa-h2suaTlSeUZonHMUw_TASHKM32c9D9ZapIhB4/edit

Let me know if it's good to go and I'll figure out how to update it. Thanks!

**Comment by laurenluz** [comment]
@c0ric0ri @oyealmond Did you guys tweet this out yet? Noticing some slight inaccuracies in the doc I'd like to change. Can you make it "anyone can comment" access if it hasn't been sent out yet?

@franculio I'm going to make these docs changes a separate issue because it gets confusing to have it with this tweet issue :)

**Comment by c0ric0ri** [comment]
@laurenluz not yet, I just changed the doc access

**Comment by c0ric0ri** [comment]
Hey @oyealmond would you please check the reviews on the tweet thread and clean it up? 

@laurenluz would love to get your quick confirmation that the thread looks good to you (I am just still confirming the one detail about reliability)

**Comment by oyealmond** [comment]
@c0ric0ri The edits are perfect. For future issues, please feel free to edit and post without my VoBo . I'll make sure to review to keep polishing my Giveth tone

**Comment by laurenluz** [comment]
Hey beautiful friends~

So I finally dove into that thread, rewrote it, scheduled it for tomorrow morning & want to provide some constructive feedback for the future :)

First, I love providing our community at large with some updates about what is new on the DApp! Especially when something makes their lives easier. I do think it's important also to consider who would read this, and what value if provides them.

This thread as originally written has two pretty unrelated features put together in a way that's kind of like DApp updates but without any of this "why this is important" or "why you [as a donor, a project owner, a crypto nut, etc.] should care."

I revised the thread to mention only the project verification update, and then put this in a larger context of what is project verification - why get verified, why donate to verified projects, how to do it". You can see it [here](https://docs.google.com/document/d/1_cd3J48b27aeiS2lEVQNPw2uf_RQJzsCRcjVXoHVZ9I/edit)

My intention is to hit a variety of use cases like:
- provide a resource for our team to share with anyone who is curious about project verification
- encourage people to donate to projects on Giveth
- encourage projects to get verified
- tell people about a new feature (the form embedded in the DApp)
- and most importantly: be something that people will want to read and share with their friends

Try to pull the reader in next time with the first few precious words. "Hey GIVers" is often not the best way to start a tweet because people will gloss over it. Think about some creative memes or storytelling tactics that might make *you* interested in a new feature we're offering.

I'm happy to be back and help provide some more feedback throughout! This is scheduled for tomorrow & I'll write a second tweet in a few days mentioning the multiple recipient addresses (which I think can be just a short single tweet).

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1574791511170064386

**Comment by oyealmond** [comment]
@laurenluz , We also have ready a video tutorial that could be added to the thread explaining the new process: 
https://www.youtube.com/watch?v=8myBgJCKXiU&t=18s
