### ISSUE TITLE
PlutoView partnership NFT minting and selling

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#854]
Long story short:

Plutoview reached out to see if we could partner up to bring tools to help projects fundraise through minting art of collborative drawing.

We went through DAO governance to see what was the feeling about piloting the partnership to see if tis could be a tool for Makers. In a very unpopular (low ungagement) forum post votes went to minting with Doin Gud, rather than Open Sea. 

We decided to make 2 drawing one with the team & one at ETH BCN. 

Since, I sort of got my plate full and left this on the back burner. The idea would be to bring this into the market on Doin Gud or Open Sea and make the proceeds go to the Matching Fund :)

I will add @franco into the Discord thread. The tricky choice is if we will sell on Doin Gud or Open Sea. Honestly, I would go for 1 on each or Open Sea where there is more sell volume. However, you might wanna bring this into the next governance call or I can if you prefer.

**Comment by franculio** [comment]
After a call with Eve from Plutoview we decided to hold back on the by-monthly drawing parties until we test out the sell of the NFTs. 

I think doing the minting in two different platforms might be more of a hassle. So maybe we just stick to one, I suggest is brought up in the next governance meeting what was voted in the forum post (https://forum.giveth.io/t/pilot-minting-selling-nfts-for-a-cause-to-offer-it-as-a-fundraising-tool-to-out-makers-partnership-with-plutoview/722) and if nobody opposes to mint them in Doingud we should go ahead in that direction.

Since the funds from the sell are for the Giveth Matching Pool first question would be if there's an existing profile in any of those platforms for Giveth so we can give authenticity to the NFTs or we do it from any address (I can mint it from mine) and put the Matching Pool address for the receiving funds (the seller profile wouldn't be very known in this case).

@Cotabe or @WhyldWanderer please do bring this up in the next Governance meeting, I'm going to be away that day but I'll make an effort to attend to this next call and I can continue from what is decided in the call.
