### ISSUE TITLE
Recipient Address Documentation Update

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#874]
Hey @c0ric0ri ! I checked the docs and this hasn't been updated yet. 

You can find the modification I wrote here:
https://docs.google.com/document/d/1xQdwa-h2suaTlSeUZonHMUw_TASHKM32c9D9ZapIhB4/edit

Let me know if it's good to go and I'll figure out how to update it. Thanks!

_Originally posted by @franculio in https://github.com/Giveth/giveth-planning/issues/842#issuecomment-1253463889_

**Comment by laurenluz** [comment]
Hey @franculio! Thanks for taking the initiative to make these suggestions. I made a couple of small comments in the doc.

I would love it if you could copy/paste the exisitng content into a google doc, make the changes in there directly (maybe just make them a different colour) and then have that google doc up for review.

With the suggestions like this it's a bit hard to get the context of the overall documenation. Maybe we can jump on a really quick call and i can give you a little bit clearly of an explanation to empower you more. Lmk if that makes sense!

**Comment by franculio** [comment]
Thanks @laurenluz ! 

Since the recipient address part that needs to be changed is very small, the google docs with suggestions looks confusing anyways. Hopefully you can understand it : https://docs.google.com/document/d/1jKripLIYJXKXbJEXl0W7i3Md1QIrp9RD6KSNS4L_-e4/edit

If not I'm also keeping the other one with the same proposal but without suggestions (only final result): https://docs.google.com/document/d/1xQdwa-h2suaTlSeUZonHMUw_TASHKM32c9D9ZapIhB4/edit

I've also used the hackmd tool and have it ready to propose the update in github if you think the text looks correct. 

Let me know and I'll go ahead.

**Comment by laurenluz** [comment]
Hey Fraco!

I like the one with the final result thing, it's definitely easier to follow :)

I made some suggestions in the doc. That looks great, I think you can try just updating them directly (after reviewing my suggestions) in the docs.

**Comment by franculio** [comment]
This has been successfully updated! Closing this issue :)
