### ISSUE TITLE
Monthly Platform updates Tweet Thread

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#903]
Summarizing on a monthly basis what feature updates have gone live on the Giveth dApp in the past.

**Comment by c0ric0ri** [comment]
Just want to add in here that we can flush out an easier process for the future. Right now we're looking at how content requests flow to the Comms teams, and to avoid this extra work for @MoeNick I'm thinking we can have all the new issue requests that are created around feature updates simply tagged to an Epic.

This Epic can then be referenced monthly by the Comms Team when we're creating these recap threads.

But we need to flush out this process further first. If you guys prefer using a doc in Notion for now go ahead, just letting you know that we're currently looking at the process as a whole.

**Comment by c0ric0ri** [comment]
Not yet, need a little more time to properly sort out the process. Just wanted to indicate that we're working on it. Will provide updates once I have them!

**Comment by MoeNick** [comment]
Hey all, sorry I was not aware of this. These days I'm struggling with Internet Connection and playing with VPNs more than everything...
So, what I got from your comments, I have to prepare some DApps updates content for tweets. I can do it. Do we have a template over it so that I can have a clue what to do? 
So we have to tweet updates for Sep and Oct ? and the end of this month?
