### ISSUE TITLE
Giving Block partnership coordination modification

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#912]

**Comment by ahmadabugosh** [comment]
On the Giving Block site, i was surprised to see they accept over 100 tokens but no $GIV :( https://thegivingblock.com/resources/cryptocurrency-we-accept/

As a partner of ours, we should be there. @SnakeGH can you check with the team on who our contact was at the Giving Block and see if you can get us listed? 🙏

**Comment by SnakeGH** [comment]
Great idea and point, Ahmad! I believe it is either @WhyldWanderer or @laurenluz that are running with TGB. 

ladies, do you mind putting the contact information in this google shared doc from GH issue #902? 

https://docs.google.com/document/d/1iq1cWGWqxGRl4DuP15bYc-D5ZT2231Ic0dK-FmrtV8M/edit

Also, do you mind if I start a new communication thread with them about Ahmad's point?

**Comment by laurenluz** [comment]
@SnakeGH - Ashely & I both have kind of failed on the giving block comms tbh. If you are willing to take it on, it would be great. 

I don't have access to that doc, can you please make it (and all similar future docs) "anyone can comment" access?

We have a telegram group with some people from the giving block, I can add you in there but tbh it's been tough getting their responses. Here are some notable contacts for telegram:

@pmoran - director of crypto partnerships
@zoenawar - their social media person
@AlexWilsonTGB - giving block co-founder

Last we spoke with them, we were asking them to send an email to their projects (who are on Giveth) to let them know about their GIveth project. Giving block projects with donors outside of the US may want to get donors to give to them via Giveth because the donors will get GIVbacks (where as with through the giving block they could get the tax deduction... but that applies only to the US.

After that call, they made a telegram group (in June)... saying they'd get back to us. I followed up in August... no response. I don't have energy to push against that tbh.

Also FYI, we were considering modifying our integration entirely. @CarlosQ96 & @WhyldWanderer know a lot about it. The issues being, mainly:
- Giving block projects not being removed or updated on Giveth when they are removed or updated on TBG
- low donation influx for Giving Block projects on Giveth (likely due to project owners' lack of awareness of their Giveth project)

And from our side, an issue being that Giving block projects are rich in number & low in quality of project description... diluting the pool of our own verified projects, attracting few donors... with no communication and apparently benefits... limited to only mainnet donations and a few tokens (with GIV not being one...)

**Comment by laurenluz** [comment]
@SnakeGH - Ashely & I both have kind of failed on the giving block comms tbh. If you are willing to take it on, it would be great. 

I don't have access to that doc, can you please make it (and all similar future docs) "anyone can comment" access?

We have a telegram group with some people from the giving block, I can add you in there but tbh it's been tough getting their responses. Here are some notable contacts for telegram:

@ pmoran - director of crypto partnerships
@ zoenawar - their social media person
@ AlexWilsonTGB - giving block co-founder

Last we spoke with them, we were asking them to send an email to their projects (who are on Giveth) to let them know about their GIveth project. Giving block projects with donors outside of the US may want to get donors to give to them via Giveth because the donors will get GIVbacks (where as with through the giving block they could get the tax deduction... but that applies only to the US.

After that call, they made a telegram group (in June)... saying they'd get back to us. I followed up in August... no response. I don't have energy to push against that tbh.

Also FYI, we were considering modifying our integration entirely. @CarlosQ96 & @WhyldWanderer know a lot about it. The issues being, mainly:
- Giving block projects not being removed or updated on Giveth when they are removed or updated on TBG
- low donation influx for Giving Block projects on Giveth (likely due to project owners' lack of awareness of their Giveth project)

And from our side, an issue being that Giving block projects are rich in number & low in quality of project description... diluting the pool of our own verified projects, attracting few donors... with no communication and apparently benefits... limited to only mainnet donations and a few tokens (with GIV not being one...)

**Comment by laurenluz** [comment]
Anyway, I am happy to add you to the tg group w/ then, send a message to introduce you and the situation, and let you take it away from there on comms.

**Comment by laurenluz** [comment]
oh!! and sorry, just realizing this issue's content... $GIV is not listed because it is not listed on Gemini - an exchange that the Giving Block uses. In order for GIV to be accepted by their projects, we would need to get it listed on Gemini... which we have not yet been successful in yet. We could get support from the giving block or try to pursue it... but it's not about the giving block listing GIV... it's about gemini listing GIV.

**Comment by laurenluz** [comment]
FYI - we are working on getting GIV on gemini in the GIVeconomy research group w/ Grapefuit: https://github.com/Giveth/GIVeconomy/issues/719

**Comment by SnakeGH** [comment]
Thank you for taking the time to provide such amazing details @laurenluz , even though not the best TGB results at the moment from their side. Please do connect me with them and I will take over point in that relationship, as I definitely would love to stay on them and make this relationship more mutual. 

Ill DM you in Discord my Telegram handle to add.

**Comment by SnakeGH** [comment]
@ahmadabugosh - @laurenluz has added me to the telegram group and I have added all of TGB participants to our CRM...now we wait for a response. Consider this issue closed now?

**Comment by SnakeGH** [comment]
Cool, those questions have all been addressed / proposed in the latest TG message, let's see if / when they respond then :) @ahmadabugosh

**Comment by divine-comedian** [comment]
I would and have been in favour of removing the integration - especially with mandatory updates coming this just going to get messier

if they haven't taken any effort to work with us in the last 4 months they probably won't do anything meaningful in the short-term and this just going to make more headaches for comms and devs alike.

**Comment by laurenluz** [comment]
Griff's objection is that we will lose many verified projects... going from "over 1000" to "200"? @WhyldWanderer @NikolaCreatrix what are they actual numbers here? What is our rate of increase for verified projects?

I like the idea of working with another org to get pre-vetted projects integrated... and hopefully they would be a better collaborative partner.

**Comment by CarlosQ96** [comment]
We have 205 verified projects today. Two weeks ago it was 195. This is excluding any imported projects from third parties like givingblocks and change.

Change suggested in a chat, making like a voting system so people can browse their projects and vote to include it in the platform.

**Comment by WhyldWanderer** [comment]
yeah... I think we can replace GB projects with Change projects. I have a call with supahshah to talk about what the integration could look like.

As far as rate of increase... like 2 - 7 per round

I would have to agree with Griff here that we should be able to proudly say that we have over 1000 verified projects even if it means holding on the the GB integration until we find a solution. Its a mahor talking point for investors

**Comment by GriffGreen** [comment]
Yeah. If the investor convos weren't happening, i would go for quality of quantity... but there is no need to unintegrate with TGB until we have already integrated with someone more cooperative that brings our total to over 1000

Also, until we are added to Gemini it might be best to keep the integration as that helps our case to be added.

**Comment by laurenluz** [comment]
alright, so we can icebox this and make a new issue for integrating Change

**Comment by SnakeGH** [comment]
So that communication on the telegram thread doesn't get stale or weird, should I do anything to keep it alive at this point or ice box that as well?

**Comment by laurenluz** [comment]
I would just say something like "ok, thanks for letting us know" ish... then let it die.

**Comment by SnakeGH** [comment]
I sent this follow up to leave the door open but also put a little damper on the broken relationship

"Thanks for the response, Alex, as we appreciate it, but definitely unfortunate to hear, as it would have been really great to see this partnership grow and strengthen ASAP. 

I'm sure we will all be back in touch, but until then, we will look forward to the time, when these mutual projects will increase in financial support."

**Comment by laurenluz** [comment]
cool, that's all good. Although the line "when these mutual projects will increase in financial support" is really confusing to me.

**Comment by SnakeGH** [comment]
@laurenluz since we are moving forward in another direction, should we close this issue?
