### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by franculio** [Giveth/giveth-planning#934]
Update https://docs.giveth.io/dapps/gettingStarted

**Comment by franculio** [comment]
Thank you @tropicalmangos !! 

I am getting the same error message when trying to connect with Gnosis safe, maybe ask the devs in the support channel?

**Comment by franculio** [comment]
Hey I added the image that was missing from the error you were getting but I think this is good and ready for review.

**Comment by ahmadabugosh** [comment]
hey @franculio,  I think for this one, we should also have a more beginner-friendly paragraph or section **before** we get into them signing in with Metamask or Torus. I'm just thinking of the "beginner  / new to web3" persona of donor or project and how they would get lost if they right away if we tell them to sign in with a web wallet (and they don't even know that that is).

We should probably have a "complete beginner" section or something lthat on top, where we mention how if you're new to web3 you need something called a wallet and you need to load it with funds etc. (similar to what you did for the 2nd email in the onboarding campaign @tropicalmangos , taking content from the Donors 101 course). 

Also, I think it would flow better, to combine that new beginner section with the current [Cryptocurreny donations](https://docs.giveth.io/dapps/crypto) section, since at the moment it doesn't flow well (the first section of getting started right away talks about the wallet and the dapp, then the second section talks about what cryptocurrency is and why it's important when they should probably be flipped).

**Comment by franculio** [comment]
This doc has been updated.

@ahmadabugosh I think what you're suggesting makes sense, it would be switching the "Cryptocurrency donations" section with the "Getting started" one right? It would definitely flow better.

**Comment by ahmadabugosh** [comment]
@franculio Well I think the current "Getting Started" is more to do with getting started with the app, but I think we should also have an even more beginner section like "New to Crypto?" for example for complete newbies. We could keep the current section about cryptocurrency donations there and add a link to the [Donors 101 video series](https://www.youtube.com/playlist?list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ).

**Comment by franculio** [comment]
@ahmadabugosh I get you mean. I think the [FAQ section](https://docs.giveth.io/dapps/faq) has a pretty solid explanation for newbies, I could add a paragraph saying something like "New to crypto? Check our FAQ section to understand better" in the "Getting Started". Wdyt? 

And I'll definitely add the Donors 101 course to the donations section, that's a great idea!

**Comment by ahmadabugosh** [comment]
@franculio That makes sense! Especially since a lot of people would go to Getting Started if they are new. I would also remove the current "Cryptocurrency donations" section (I think it's not worth having its own section if you're including it in the FAQs)

**Comment by danelsuga** [comment]
Hi @franculio ! Do you have this issue covered? Let me know if you need help. (As you may already know, tropicalmangos is no longer on it.)

**Comment by franculio** [comment]
Thank you @danelsuga ! I've already updated this doc with tropicalmango's version, but it never hurts having you double check it 😄 
Here is a google doc with the updated version where you can make the necessary changes https://docs.google.com/document/d/1-vY9WJ11H-buBApbWa1sM0yzNiPLD8ANpI6GtCa183E/edit?usp=sharing

Thank you again!

**Comment by c0ric0ri** [comment]
Hey @franculio what's going on with this issue? Do you still need support to move it to Closed?

**Comment by franculio** [comment]
Sorry @c0ric0ri, this issue has been done. I just kept it open because there's a comment from Ahmad that he mentions deleting one of the section of the docs. But i've changed it in the next PR for the docs. Closing the issue now.
