### ISSUE TITLE
Verification Workshop email invitation ⭐️

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#993]
Hey @ahmadabugosh ! Hope you're doing good :) 
Could you please help me send this email to promote our Verification Process Workshop please? 

Will be good if we can schedule this email to be send on November 4th. 

[The text is here](https://docs.google.com/document/d/1MLWs_Z_NzS3alui0gideXWP7kCLM8gpBCU8IgQvG28o/edit?usp=sharing). 

Thank you! :)

**Comment by ahmadabugosh** [comment]
Hey @tropicalmangos can you take this one on? It would be a good one to help you understand how Autopilot works. Let me know if you can and if you need any support!

**Comment by ahmadabugosh** [comment]
hey @tropicalmangos yes I know, but I thought it would be a nice one for you to test out how Autopilot works before you get deeper into the automation and sequences you're planning. If you're busy this week no worries I can take on this one, but it would be nice to have you get started on some of these email tasks since I know you have the skills for it and it aligns with some of the things you mentioned you wanted to work on like the Onboarding series (also maybe we can align with @laurenluz if you'd like to take on more of the email work) 🙏

**Comment by laurenluz** [comment]
@tropicalmangos I will send you a DM to check in w/ you on priorities.

@ahmadabugosh - will get back to you, I agree w/ your point on autopilot context.

@oyealmond - can you double check the content/times in this email and confirm that it ready to blast off? As a reminder, please get at least 1-2 reviewers to QA emails before they go out (not sure if this was done as I don't see it in the issue)

**Comment by oyealmond** [comment]
hey L! Thank you so much, didn't know about the 2 ppl reviewing before. That's great feedback. 
@c0ric0ri , before sending this invitation out, could you help me [checking the email draft first? ](https://docs.google.com/document/d/1MLWs_Z_NzS3alui0gideXWP7kCLM8gpBCU8IgQvG28o/edit?usp=sharing)Thank you!

**Comment by ahmadabugosh** [comment]
Hey @tropicalmangos, 

1) Audience, yes the Projects one is correct 
2) For the template, I don't believe we have one for this. I think a simple text one would be fine since it doesn't have any images and is just a single column.  
3) For the Add to Calendar, I got the link from the Sesh bot on Discord (when you click on the + on the event on Discord it gives you a link to add to Google calendar, I just include that) 
4) For the preview you sent, I think the email is a bit too long and could be punchier. I left some comments on the doc: https://docs.google.com/document/d/1MLWs_Z_NzS3alui0gideXWP7kCLM8gpBCU8IgQvG28o/edit

**Comment by oyealmond** [comment]
Hey dear team! Thank you for taking care of this! @ahmadabugosh @tropicalmangos . 
We are still checking the email draft as maybe it will worth to add smth around the Verification Course 101. 
Please don't send the invitation until is reviewed & good to go :) 
Ty!

**Comment by oyealmond** [comment]
Hey @ahmadabugosh :) I changed the body to include the Giveth Projects 101 course launch as well. [Could you help me review?](https://docs.google.com/document/d/1MLWs_Z_NzS3alui0gideXWP7kCLM8gpBCU8IgQvG28o/edit?usp=sharing) After this, I believe will be good to go @tropicalmangos .

**Comment by oyealmond** [comment]
No is great! Thank you for reviewing as well @tropicalmangos ! 
And thanks for the suggestions @ahmadabugosh . 
After knowing @danelsuga we're good to go! :D

**Comment by danelsuga** [comment]
All good!

**Comment by ahmadabugosh** [comment]
@tropicalmangos Looks good, I think it's ready to send! (i just edited it to make the font smaller, I think normal fonts should max be 16px otherwise they look too big in emails)

In terms of timing I would suggest in maybe 4 hours from now (in the morning US / South America time)

**Comment by oyealmond** [comment]
uhooo you're the best! Thank you team! @danelsuga @tropicalmangos @ahmadabugosh @laurenluz

**Comment by c0ric0ri** [comment]
Thanks @tropicalmangos since you've posted it, please close this issue when you're ready!

**Comment by laurenluz** [comment]
Hey everyone! saw this went out already - all good, just... let's not use hashtags in emails... and no "$GIV"

It's just GIV & GIVbacks... not $GIV & #GIVbacks for emails....

Imo, the only logical place we should write $GIV is on Twitter because putting the "$" makes it a tag for that cryptocurrency.... it doesn't make sense in other contexts like emails & documentation where you don't get the link.

Same with hashtags... since nothing is being linked on #GIVbacks... it doesn't really make sense to write it as text in an email, imo, and I think it makes the email feel a little messy.

@oyealmond @danelsuga @c0ric0ri @ahmadabugosh @tropicalmangos
